### ISSUE TITLE
Package `open-telemetry/opentelemetry-auto-slim` misses `open-telemetry/sem-conv` as dependency

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry-php#1001]
**Describe your environment** 
MacOS
PHP 8.2.5
composer 2.5.5
opentelemetry module

**Steps to reproduce**
```sh
echo '{"require": {}, "minimum-stability": "beta"}' > composer.json
composer require slim/slim:"4.*"
composer require slim/psr7
composer require open-telemetry/opentelemetry-auto-slim
```

Create a sample application like the following in index.php:

```php
<?php
use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use Slim\Factory\AppFactory;

require __DIR__ . '/vendor/autoload.php';

$app = AppFactory::create();

$app->get('/', function (Request $request, Response $response, $args) {
    $response->getBody()->write("Hello world!");
    return $response;
});

$app->run();
```

Now run the webserver `php -S localhost:8080`

Sending a `curl localhost:8080` gives me the following error:

```sh
Uncaught Error: Class "OpenTelemetry\SemConv\TraceAttributes" not found in vendor/open-telemetry/opentelemetry-auto-slim/src/SlimInstrumentation.php:42
Stack trace:
#0 vendor/slim/slim/Slim/App.php(197): OpenTelemetry\Contrib\Instrumentation\Slim\SlimInstrumentation::OpenTelemetry\Contrib\Instrumentation\Slim\{closure}(Object(Slim\App), Array, 'Slim\\App', 'handle', '/Users/neumanns...', 197)
#1 vendor/slim/slim/Slim/App.php(183): Slim\App->handle(Object(Slim\Psr7\Request))
#2 index.php(15): Slim\App->run()
#3 {main}
  thrown invendor/open-telemetry/opentelemetry-auto-slim/src/SlimInstrumentation.php on line 42
```

**What is the expected behavior?**
No error

**What is the actual behavior?**
The error described above

**Additional context**
The issue goes away when I install the sdk or semconv package manually

**Comment by brettmc** [comment]
Thanks for the bug report, should be fixed by https://github.com/open-telemetry/opentelemetry-php-contrib/pull/156 (along with most other auto-instrumentation modules)

**Comment by svrnm** [comment]
TY @brettmc

**Comment by brettmc** [comment]
@svrnm the changes are in the latest version now, [`1.0.0beta8`](https://github.com/opentelemetry-php/contrib-auto-slim/releases/tag/1.0.0beta8)

**Comment by svrnm** [comment]
thx for fixing @brettmc
