### ISSUE TITLE
composer require open-telemetry/opentelemetry-logger-monolog failed

### ISSUE THREAD

**Issue by runtu666** [open-telemetry/opentelemetry-php#1007]
composer require open-telemetry/opentelemetry-logger-monolog

Problem 1
- Root composer.json requires open-telemetry/opentelemetry-logger-monolog * -> satisfiable by open-telemetry/opentelemetry-logger-monolog[0.0.1].
- open-telemetry/opentelemetry-logger-monolog 0.0.1 requires open-telemetry/api >=1.0.0beta7 <2 -> found open-telemetry/api[dev-main, 1.0.0beta7, 1.0.0beta8, 1.0.0beta9, 1.0.x-dev (alias of dev-main)] but it does not match your minimum-stability.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require open-telemetry/opentelemetry-logger-monolog:*" to figure out if any version is installable, or "composer require open-telemetry/opentelemetry-logger-monolog:^2.1" if you know which you need.

**Comment by brettmc** [comment]
You can [set minimum-stability](https://getcomposer.org/doc/04-schema.md#minimum-stability) to dev here.
How did you create your initial composer.json (is there some documentation or examples that we need to update)?

**Comment by brettmc** [comment]
@runtu666 closing this, feel free to re-open if you're still having issues.
