### ISSUE TITLE
[TC Review] Consider relocating Globals

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-php#1012]
Currently globals exist in `OpenTelemetry\API\Common\Instrumentation\Globals`, which a rather long path. In other SIGs it's at the top level though, i.e. `OpenTelemetry\API`. Consider changing its location, _unless_ globals usage will be a rather unusual functionality piece, e.g. tracer/meter/log providers are passed around manually.

**Comment by brettmc** [comment]
I don't see why `Globals` couldn't be moved up to the top-level API namespace, `OpenTelemetry\API\Globals`. @Nevay ?
