### ISSUE TITLE
[TC Review] Consider wrapping `TraceFlags`

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-php#1013]
Even though trace key is only a small numerical value (with none and sampled values), in a few languages it's functionality is wrapped in its own class **through static methods**, e.g. `TraceFlags.getSampled()`. An int is actually used underneath, and this provides all related functionality to be in a single location.

**Comment by pdelewski** [comment]
@carlosalberto That's an implementation detail IMO.
