### ISSUE TITLE
[TC Review] Consider renaming `SpanInterface.getContext()`

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-php#1015]
`getContext()` _could_ cause confusion as it may hint `Context`, rather than `SpanContext`. A few languages use `getSpanContext()` instead (although it's longer, etc)

**Comment by brettmc** [comment]
@carlosalberto if `getSpanContext()` is in common usage in other SIGs, should we update the spec to mention this?

**Comment by carlosalberto** [comment]
I don't think so - this is _mostly_ a subjective thing. If you yourselves are happy with `getContext()`, let's go with that.

**Comment by brettmc** [comment]
I think we're happy with `getContext()`, and will stick with what we have :)
