### ISSUE TITLE
[opentelemetry-php-contrib][auto-pdo] post hook causes another exception when PDO::__construct threw an exception

### ISSUE THREAD

**Issue by siketyan** [open-telemetry/opentelemetry-php#1017]
**Describe your environment**
```
PHP 8.2.6 (cli) (built: May 11 2023 12:51:38) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.6, Copyright (c), by Zend Technologies
```

**Steps to reproduce**
- Install `open-telemetry/opentelemetry-auto-pdo` and setup.
- Call PDO::__construct with INVALID connection string, the constructor will throw an error.
- The post hook of PDO auto instrumentation throws an exception

**What is the expected behavior?**
The actual exception PDO::__construct thrown is logged into the console or caught by catch stmt.

**What is the actual behavior?**
An another exception is thrown and logged into the console.

<img width="1015" alt="Screenshot 2023-06-02 at 18 29 25" src="https://github.com/open-telemetry/opentelemetry-php/assets/12772118/fba10a47-b756-40b7-992d-9f77d40d3f83">

**Additional context**
My composer.json:
```json
        "open-telemetry/exporter-otlp": "^1.0.0beta8",
        "open-telemetry/opentelemetry": "^1.0",
        "open-telemetry/opentelemetry-auto-io": "^0.0.6",
        "open-telemetry/opentelemetry-auto-laravel": "^0.0.5",
        "open-telemetry/opentelemetry-auto-pdo": "^0.0.5",
        "open-telemetry/sdk": "^1.0.0beta10",
```

**Comment by brettmc** [comment]
@siketyan thanks for the bug report, I've submitted a PR that should fix it. If you're able to test it against your code, I'd appreciate it.
