### ISSUE TITLE
[TC Review] Consider moving Context impl classes to a nested package

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-php#1019]
(Disclaimer: I ignore the limitations/features of PHP package organization) Quite a few concrete classes exist under the `Context\` package, e.g. `FiberBoundContextStorage.php `, and it may make sense to move such classes to a nested package. Maybe `Context\Internal`?

**Comment by brettmc** [comment]
All the fiber stuff is core, but relates to newer versions of PHP (while we still support older versions without fiber support). In the future I think this will be the only implementation, so I'd prefer to keep it within the Context package.
