### ISSUE TITLE
Context Implementation - Create the Data Structure in the Overview

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#102]
The [Overview](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/context/context.md#overview) of the context specification explains to us what a Context is supposed to contain for the OpenTelemetry API.  As far as I'm aware, PHP does not have something like this out of the box, so we'll have to implement it.  

This object needs to be an immutable object, so I'd think that we would want to have a php class with a constructor and a getter, but without a setter.

This implementation should live separately from the Context API as defined in the spec.

Success criteria - being able to create a `Context` Object from within the code base.

**Comment by bobstrecansky** [comment]
I believe that @michaelorr has started working towards this goal.

**Comment by michaelorr** [comment]
That's right. This would be the underlying data storage mechanism for the `CorrelationContext` I hope to have a WIP PR open early next week for discussion. I don't have permissions to change the "assignee" of the Issue but if someone else wants to set it to me, that would be alright by me.

**Comment by bobstrecansky** [comment]
This has been completed with #137
