### ISSUE TITLE
[TC review] Consider hiding `ContextKeys`

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-php#1020]
Usually we try to hide the context keys in other languages, to allow ourselves future changes - while exposing helper methods/functions to access such fields in a `Context` object. Hence consider hiding the actual keys in `API/Common/Instrumentation/ContextKeys` (and maybe keep this functionality as a helper method returning the key's values? e.g. `logerProvider`).

**Comment by brettmc** [comment]
I think this is covered, as the `ContextKeys` class is marked as `@internal`
