### ISSUE TITLE
[TC Review] Logs/Metrics in the API artifact

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-php#1022]
I'm wondering what's the plan regarding release, as tracing is soon to be ready, while logging/metrics components are in the same package:

1) If logs/metrics are ready to go stable, we should do an extra review cycle
2) If logs/metrics are not ready, we shouldn't include them in the initial API package

(Disclaimer: again, I'm not very well versed in PHP packages)

**Comment by brettmc** [comment]
Discussed in SIG meeting today. We think we should aim to go stable with Logs and Metrics signals, too. We're not aware of any development required for these signals, they just need more usage and user testing to give us more confidence in them.
We will ask TC for a review of these signals.

**Comment by brettmc** [comment]
Related and awaiting:
https://github.com/open-telemetry/community/issues/1536
https://github.com/open-telemetry/community/issues/1537

**Comment by bobstrecansky** [comment]
We have issues in the community repo for the other two signals as well.
