### ISSUE TITLE
Watchers register event listener more than once

### ISSUE THREAD

**Issue by brettmc** [open-telemetry/opentelemetry-php#1032]
_copied from @alejandro-mejias issue over in https://github.com/opentelemetry-php/contrib-auto-laravel/issues/1 _

About traces. In a fresh Laravel 10 application, Watcher register methods are executed twice. This assumes that they listen twice for the same event. For example, in the src/QueryWatcher watcher, the register method listens for the Illuminate/Database/Events/QueryExecuted event. Since it runs twice, it doubles the event listener and the traces are recorded duplicates. Look at the attached screenshot.

![242855098-b6f64b4f-563f-443b-b077-1358a6d0b15c](https://github.com/open-telemetry/opentelemetry-php/assets/4978962/07194d1d-fe55-4c68-be91-f1d276e34b18)

You can see listeners `app()[events]->getRawListeners()` and check watchers are duplicated.

**Comment by brettmc** [comment]
@alejandro-mejias can you test this out using dev-main and let us know if it resolves your issue?

**Comment by alejandro-mejias** [comment]
@brettmc Sure! It's working! Thank you.

![Screenshot 2023-06-15 11 12 24](https://github.com/open-telemetry/opentelemetry-php/assets/63665312/3917c1e7-d9aa-49d0-b616-535dec92b4bf)
