### ISSUE TITLE
Context Implementation API - Getting a Value

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#104]
We should be able to get a value within a `Context` object.

The spec describes this particular feature [here](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/context/context.md#get-value)

Success criteria - The API MUST return the value in the Context for the specified key.

*note* - We need to have https://github.com/open-telemetry/opentelemetry-php/issues/102 Completed first before we can get a value within our context object.

**Comment by bobstrecansky** [comment]
This will be solved with https://github.com/open-telemetry/opentelemetry-php/pull/111

**Comment by artem-prozorov** [comment]
https://github.com/open-telemetry/opentelemetry-php/pull/111 is merged, we can close this one I guess?

**Comment by bobstrecansky** [comment]
Yup, thanks!
