### ISSUE TITLE
Cannot make getting started example to work

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-php#1040]
**Describe your environment** 
$ php -v
PHP 8.2.7 (cli) (built: Jun  8 2023 20:05:45) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.7, Copyright (c), by Zend Technologies

**Steps to reproduce**
1. Follow steps at https://opentelemetry.io/docs/instrumentation/php/getting-started/
2. Open http://localhost:8080/rolldice
3. No output it produced. HTTP response is 200, with empty body.

**What is the expected behavior?**
Expected output of random number written to the response body in the /rolldice handler.

**What is the actual behavior?**
No output.

**Additional context**
Testing for https://github.com/open-telemetry/community/issues/1537

I am probably doing something wrong, haven't touched php for more than a decade, so will need your help to figure it out.

**Comment by brettmc** [comment]
I think the problem might be the file name (the documentation is confusing, I'll fix it). If your file name is `index.php`, does it work? 

I see that it refers to `index.php` but the next line tells you to name it `GettingStarted.php`: for that to work, you'd need to run `php -S localhost:8080 GettingStarted.php`

**Comment by brettmc** [comment]
getting-started docs updated in https://github.com/open-telemetry/opentelemetry.io/pull/2883

**Comment by tigrannajaryan** [comment]
`php -S localhost:8080 GettingStarted.php` works, thank you.
