### ISSUE TITLE
Cannot make getting started manual instrumentation example to work

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-php#1042]
**Describe your environment** 
```
$ php -v
PHP 8.2.7 (cli) (built: Jun  8 2023 20:05:45) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.7, Copyright (c), by Zend Technologies
```

**Steps to reproduce**
Follow instruction at https://opentelemetry.io/docs/instrumentation/php/manual/
Copy example from https://opentelemetry.io/docs/instrumentation/php/manual/#example to GetttingStarted.php
Run `https://opentelemetry.io/docs/instrumentation/php/manual/#example`
Open http://localhost:8080/rolldice

**What is the expected behavior?**
Page to load without errors

**What is the actual behavior?**
The following error is shown: 
```
Fatal error: Uncaught Error: Class "ResourceInfoFactory" not found in /Users/tnajaryan/work/experiments/otel-php/GettingStarted.php:2 Stack trace: #0 {main} thrown in /Users/tnajaryan/work/experiments/otel-php/GettingStarted.php on line 2
```

**Additional context**
Testing for https://github.com/open-telemetry/community/issues/1537
I started with trace example, the next step would be adding logs, but I didn't get there.

**Comment by tigrannajaryan** [comment]
Sorry for dumb bug reports. For now I am following the Getting Started instructions to the letter without trying to troubleshoot myself, just to make sure our instructions are good.

**Comment by brettmc** [comment]
This is because we haven't put all of the import statements in for brevity. To make the example work via copy/paste, we will need to add this (plus the `<?php` opening tag)

**Comment by brettmc** [comment]
The docs have been thoroughly updated, and in my testing all of the examples are now runnable.
