### ISSUE TITLE
Exporting to LightStep Development satellites is failing

### ISSUE THREAD

**Issue by filakhtov** [open-telemetry/opentelemetry-php#1047]
👋🏻 hey everyone!

I ran into a problem when trying to instrument a project with OpenTelemetry, exporting traces to LightStep via OTLP protocol using Protobuf-over-HTTP transport.

Essentially getting the:
```
Warning: Export failure: Error occurred during parsing in OpenTelemetry\Contrib\Otlp\SpanExporter in vendor/open-telemetry/api/Behavior/LogsMessagesTrait.php on line 43
```

I am using PHP 8 (8.1.19), and using latest LightStep Development satellites with their recommended `/traces/otlp/v0.9` endpoint.

After some debugging, I have narrowed the problem down to protobuf deserialization, here:
https://github.com/open-telemetry/opentelemetry-php/blob/1caf77b436bc45eacd6a5265d4c519d22e25f5ff/src/Contrib/Otlp/ProtobufSerializer.php#L102

Upon further inspection, I have noticed that `$payload` in this context is an empty JSON object `{}`, which is the response sent back by the LightStep satellite. I don't have the same problem with implementations in other languages, so before going and bringing this up with LightStep, I have decided to check how things are done in other languages. What I have noticed, none of the other language implementations check or care about the response body, they just check the HTTP status and move on:
- [Ruby](https://github.com/open-telemetry/opentelemetry-ruby/blob/ac9b36aaed25d56cdac6ca59f5f1e822aae9c235/exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb#L164) is reading and discarding the body;
- [Python](https://github.com/open-telemetry/opentelemetry-python/blob/6b9f389940ec0123d5dafc7cb400fc23c6f691c6/exporter/opentelemetry-exporter-otlp-proto-http/src/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py#L155-L156) doesn't even bother about the body;
- [Rust](https://github.com/open-telemetry/opentelemetry-rust/blob/a08c6406bb8eadcb8568740a377cfce913a1b66f/opentelemetry-otlp/src/span.rs#L504) only checks the status as well;
- [JS/TS](https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/otlp-exporter-base/src/OTLPExporterBase.ts#L93-L100) seems to care about statuses only as well;
- [Golang](https://github.com/open-telemetry/opentelemetry-go/blob/6b262b44ac70a432891d041cd146231a7b731216/exporters/otlp/otlptrace/otlptracehttp/client.go#L169-L192) actually cares about the body and partial success;
- [Java](https://github.com/open-telemetry/opentelemetry-java/blob/93eac2538c665d164cfddb44a75fd99c2b3267c0/exporters/common/src/main/java/io/opentelemetry/exporter/internal/http/HttpExporter.java#L85-L89) only cares if the response isn't between 200 and 300;

So I wanted to check what is actually the correct expected behaviour here?.. before I go and start changing PHP implementation or chase down LightStep to change something in their satellites.

Thanks in advance 🙇🏻‍♂️

**Comment by brettmc** [comment]
Hi @filakhtov 
The spec https://github.com/open-telemetry/opentelemetry-proto/blob/v0.20.0/docs/specification.md#otlphttp-response talks about how a server should respond. There are a few "MUST"s in there, this one seems relevant:

> The response body MUST be a Protobuf-encoded [ExportServiceResponse](https://github.com/open-telemetry/opentelemetry-proto/blob/v0.20.0/opentelemetry/proto/collector) message (ExportTraceServiceResponse for traces, ExportMetricsServiceResponse for metrics and ExportLogsServiceResponse for logs)

I think the question then becomes "is `{}` a valid protobuf-encoded `ExportTraceServiceResponse`?" Also, I'm assuming that you sent json data and received a json response (with all the right content-type headers).

We don't have a unit test for this, but I just whipped one up, and it seems happy with an empty json response:

```php
<?php

namespace OpenTelemetry\Tests\Unit\Contrib\Otlp;

use OpenTelemetry\Contrib\Otlp\ProtobufSerializer;
use Opentelemetry\Proto\Collector\Trace\V1\ExportTraceServiceResponse;
use OpenTelemetry\SDK\Common\Export\TransportInterface;
use PHPUnit\Framework\TestCase;

class ProtobufSerializerTest extends TestCase
{
    public function test_empty_json_response(): void
    {
        $transport = $this->createMock(TransportInterface::class);
        $transport->method('contentType')->willReturn('application/json');
        $serializer = ProtobufSerializer::forTransport($transport);
        $response = new ExportTraceServiceResponse();
        $serializer->hydrate($response, '{}');

        $this->assertNull($response->getPartialSuccess());
    }
}
```

**Comment by filakhtov** [comment]
Also just double-checked `application/x-ndjson` works as expected, so definitely looks like a dev satellite problem.
