### ISSUE TITLE
Monolog integration adds "channel" attribute to every log record

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-php#1049]
I am evaluating the monolog integration. I used the following code:

```php
$handler = new \OpenTelemetry\Contrib\Logs\Monolog\Handler(
    $loggerProvider,
    \Psr\Log\LogLevel::INFO,
);
$logger = new \Monolog\Logger('example', [$handler]);

$logger->info('hello, world');
$logger->error('oh no', [
    'foo' => 'bar',
    'exception' => new \Exception('something went wrong'),
]);
```

Every log record created has an attribute `channel` that is set equal to Monolog's channel. I wonder if this is a desirable approach.

Should we instead set the Scope name to Monolog's channel instead of adding it to every attribute? The [definition of Monolog's channel](https://github.com/Seldaek/monolog/blob/main/doc/01-usage.md#leveraging-channels) is the following:
>Channels are a great way to identify to which part of the application a record is related.

I think this nicely fits our definition of [Scope](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/glossary.md#instrumentation-scope):
>A logical unit of the application code with which the emitted telemetry can be associated.

We currently set Scope's name to "monolog". I think this is a useful information, but perhaps instead of recording as the Scope name we can record it as a Scope attribute (attribute name TBD, need to create an issue in semconv repo).

Alternatively, if we think Scope's name should really be tied to the instrumentation name then I think we should at the very least use the fully qualified "opentelemetry-logger-monolog". In that case we should record the channel name as an attribute, but we need a proper semantic convention (file an issue in semconv repo to decide on the name), I don't think using just `channel` as the attribute name works (attribute naming rules [require attributes to be in namespaces](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-naming.md#recommendations-for-opentelemetry-authors)).

@open-telemetry/specs-logs-approvers what do you think? Should log integrations set integration's name as the Scope name (e.g. "monolog" in this case) or should they use the corresponding equivalent concept from the integrated library as the Scope name (the monolog's Channel concept in this case matches our Scope Name concept).

**Comment by tigrannajaryan** [comment]
I created an issue in the spec to discuss since it is not limited to PHP: https://github.com/open-telemetry/opentelemetry-specification/issues/3562

**Comment by brettmc** [comment]
It sounds like using the channel attribute as the scope name is what's expected, so I've done that in the referenced PR.

**Comment by tigrannajaryan** [comment]
FYI, spec PR merged: https://github.com/open-telemetry/opentelemetry-specification/pull/3583
