### ISSUE TITLE
What's the format of Logs/Exporter/ConsoleExporter?

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-php#1050]
Logs/Exporter/ConsoleExporter.php outputs logs to console in a json format.

What json format is this? Is it a json format that you chose yourself or is it OTLP/JSON (it looks very similar)? 

If it is intended to be OTLP/JSON then the capitalization of the fields is incorrect. OTLP/JSON [requires camelCase for all field names](https://github.com/open-telemetry/opentelemetry-proto/blob/main/docs/specification.md#json-protobuf-encoding).

Example current output for reference (see snake case field names):
```json
{
    "resource": {
        "attributes": {
            "service.name": "__root__",
            "service.version": "1.0.0+no-version-set",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.language": "php",
            "telemetry.sdk.version": "1.0.0beta11",
            "process.runtime.name": "cli-server",
            "process.runtime.version": "8.2.7",
            "process.pid": 23876,
            "process.executable.path": "\/usr\/local\/Cellar\/php\/8.2.7\/bin\/php",
            "process.owner": "tnajaryan",
            "os.type": "darwin",
            "os.description": "22.5.0",
            "os.name": "Darwin",
            "host.arch": "x86_64"
        },
        "dropped_attributes_count": 0
    },
    "scope": {
        "name": "monolog",
        "version": null,
        "attributes": [],
        "dropped_attributes_count": 0,
        "schema_url": null,
        "logs": [
            {
                "timestamp": 1687438441233783000,
                "observed_timestamp": 1687438441237067008,
                "severity_number": 9,
                "severity_text": "INFO",
                "body": "hello, world",
                "trace_id": "d56af3394e1d0bea33c92e93efea1640",
                "span_id": "5e7fe39b2a03b082",
                "trace_flags": 1,
                "attributes": {
                    "channel": "example"
                },
                "dropped_attributes_count": 0
            }
        ]
    }
}
```

**Comment by tigrannajaryan** [comment]
Looking more into it, this does not seem like OTLP/JSON in structure too. "resource" and "scope" are not supposed to be siblings in OTLP/JSON.

I think it is OK to have your own json format in ConsoleExporter, if that is the intent. I just wanted to clarify. On the other hand it may be useful to stay closer to OTLP/JSON where it makes sense. It may be useful to follow the same field naming/capitalization as OTLP/JSON even if for readability reasons you choose to have a different structure (I realize that OTLP/JSON's 3-level nesting can lead to less readable output).

**Comment by brettmc** [comment]
@tigrannajaryan It is indeed a home-grown format for human consumption. We do the same for traces, so that users can test out telemetry without needing the OTLP package installed.

Adding to the confusion, we do have two different methods of sending logs to the console: this one, plus the otlp exporter can be configured to write JSON or NDJSON output to console.

My initial feeling is that if it looks too much like OTLP/JSON then people might try to use it like it _is_ OTLP/JSON? Better documenting the class and the examples could help to avoid that, though.

**Comment by tigrannajaryan** [comment]
OK, that answers my question.

I wonder if we should introduce a human-readable format for console output and have a specification for it that all languages can follow.

I will open an issue in spec repo to discuss it.

**Comment by tigrannajaryan** [comment]
I think we can close this for now. Should spec maintainers decide that we want a standard format we can file a new issue to implement it.
