### ISSUE TITLE
BatchLogsProcessor doesn't seem to send on timeout (or I am using it incorrectly)

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-php#1064]
**Describe your environment** 
$ php -v
PHP 8.2.7 (cli) (built: Jun  8 2023 20:05:45) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.7, Copyright (c), by Zend Technologies

API:
```
            "name": "open-telemetry/api",
            "version": "1.0.0beta10",
```
SDK:
```
            "name": "open-telemetry/sdk",
            "version": "1.0.0beta12",
```

**Steps to reproduce**
Run the following script:
```php
<?php

declare(strict_types=1);

use OpenTelemetry\API\Logs\LogRecord;
use OpenTelemetry\SDK\Sdk;
use OpenTelemetry\SDK\Common\Attribute\Attributes;
use OpenTelemetry\SDK\Common\Instrumentation\InstrumentationScopeFactory;
use OpenTelemetry\SDK\Common\Time\ClockFactory;
use OpenTelemetry\SDK\Logs\Exporter\ConsoleExporterFactory;
use OpenTelemetry\SDK\Logs\LoggerProvider;
use OpenTelemetry\SDK\Logs\Processor\BatchLogsProcessor;

require 'vendor/autoload.php';

$loggerProvider = new LoggerProvider(
    new BatchLogsProcessor(
        (new ConsoleExporterFactory())->create(),
        ClockFactory::getDefault()
    ),
    new InstrumentationScopeFactory(Attributes::factory())
);

Sdk::builder()
    ->setLoggerProvider($loggerProvider)
    ->setAutoShutdown(true)
    ->buildAndRegisterGlobal();

$logger = $loggerProvider->getLogger('demo', '1.0', 'http://schema.url', ['scopefoo' => 'scopebar']);

$record = (new LogRecord(['foo' => 'bar', 'baz' => 'bat', 'msg' => 'hello world']))
    ->setSeverityText('INFO')
    ->setSeverityNumber(9);

$logger->emit($record);

sleep(10);
```

**What is the expected behavior?**
Expect to see the log output in 1 second (default batch processor timeout).

**What is the actual behavior?**
Log is output after 10 seconds, when the script execution ends.

**Additional context**
Filed while reviewing https://github.com/open-telemetry/community/issues/1537

**Comment by brettmc** [comment]
All of our batch processors are not async, so they will only send after the delay when the next record is processed. We have a bit of a plan on how to do it async, but it will likely mean dropping support for PHP7.4, so I'd like to deal with it after GA, eg in a `1.x` release.

**Comment by tigrannajaryan** [comment]
OK, sounds good. I verified that it works as you described with this code:
```php
$record = (new LogRecord(['foo' => 'bar', 'baz' => 'bat', 'msg' => 'hello world']))
    ->setSeverityText('INFO')
    ->setSeverityNumber(9);

$logger->emit($record);

$record = (new LogRecord(['foo' => 'bar', 'baz' => 'bat', 'msg' => 'hello world 2']))
    ->setSeverityText('INFO')
    ->setSeverityNumber(9);

$logger->emit($record);

sleep(2);

$record = (new LogRecord(['foo' => 'bar', 'baz' => 'bat', 'msg' => 'hello world 3']))
    ->setSeverityText('INFO')
    ->setSeverityNumber(9);

$logger->emit($record);

sleep(10);
```
Now I get all 3 records when the third emit() is executed after 2 seconds.

I think the behavior is fine for php where most scripts are short-lived anyway, so you will get the output once the script terminates.

I am going to close this, feel free to open a separate issue that describes how you want to change to work async.
