### ISSUE TITLE
ShutdownHandler: Warning: Export failure: Not Found

### ISSUE THREAD

**Issue by lhintzsc** [open-telemetry/opentelemetry-php#1075]
**Describe your environment**
env: 
Docker container for http/protobuf

OTEL_EXPORTER_OTLP_ENDPOINT http://192.168.100.10:4318 
OTEL_EXPORTER_OTLP_INSECURE true 
OTEL_EXPORTER_OTLP_PROTOCOL http/protobuf 
OTEL_LOGS_EXPORTER otlp 
OTEL_METRICS_EXPORTER otlp 
OTEL_PHP_AUTOLOAD_ENABLED true 
OTEL_RESOURCE_ATTRIBUTES service.name=php-app,service.namespace=php-tier 
OTEL_SERVICE_NAME php-test 
OTEL_TRACES_EXPORTER otlp 

RUN composer require \
    slim/slim:"^4" \
    slim/psr7:"^1" \
    php-http/guzzle7-adapter:"1.0.0" \
    grpc/grpc:"^1.38" \
    open-telemetry/sdk:"1.0.0beta13" \
    open-telemetry/opentelemetry:"1.0.0beta1" \
    open-telemetry/exporter-otlp:"1.0.0beta11" 
    
-- install OTEL packages
RUN pecl install \
    opentelemetry-1.0.0beta6 \
    protobuf-3.23.3 

-- write config for OTel
RUN echo "[opentelemetry]" >> /usr/local/etc/php/conf.d/docker-fpm.ini && \
    echo "extension=opentelemetry.so" >> /usr/local/etc/php/conf.d/docker-fpm.ini && \
    echo "extension=protobuf.so" >> /usr/local/etc/php/conf.d/docker-fpm.ini    
    
**Steps to reproduce**
Describe exactly how to reproduce the error. Include a code sample if applicable.

I used the example script from https://opentelemetry.io/docs/instrumentation/php/manual/#exporter:

I tried with with autoshutdown and ShutdownHandler. In both cases, I run into an exception that I find difficult to debug (Warning: Export failure: Not Found).

I kindly ask for a hint where the problem might be.

Console output and test.php file: 

weaken: {closure}weaken: {closure}weaken: {closure}weaken: {closure}weaken: {closure}weaken: {closure}handler == NULL
weaken: shutdownhandler != NULL
weaken: shutdownhandler != NULL
weaken: shutdowngettype: object
Warning: Undefined variable $meterProvider in /script/test.php on line 69

Fatal error: Uncaught TypeError: OpenTelemetry\SDK\SdkBuilder::setMeterProvider(): Argument #1 ($meterProvider) must be of type OpenTelemetry\SDK\Metrics\MeterProviderInterface, null given, called in /script/test.php on line 69 and defined in /script/vendor/open-telemetry/sdk/SdkBuilder.php:45
Stack trace:
#0 /script/test.php(69): OpenTelemetry\SDK\SdkBuilder->setMeterProvider(NULL)
#1 {main}
  thrown in /script/vendor/open-telemetry/sdk/SdkBuilder.php on line 45
ABdoLog

Warning: Export failure: Not Found
#0 /script/vendor/open-telemetry/exporter-otlp/MetricExporter.php(55): OpenTelemetry\SDK\Common\Export\Http\PsrTransport->send('\n\xE7\x12\n\xA8\x05\n\x1A\n\fservi...')
#1 /script/vendor/open-telemetry/sdk/Metrics/MetricReader/ExportingReader.php(109): OpenTelemetry\Contrib\Otlp\MetricExporter->export(Array)
#2 /script/vendor/open-telemetry/sdk/Metrics/MetricReader/ExportingReader.php(129): OpenTelemetry\SDK\Metrics\MetricReader\ExportingReader->doCollect()
#3 /script/vendor/open-telemetry/sdk/Metrics/MeterProvider.php(102): OpenTelemetry\SDK\Metrics\MetricReader\ExportingReader->shutdown()
#4 /script/vendor/open-telemetry/sdk/Common/Util/functions.php(37): OpenTelemetry\SDK\Metrics\MeterProvider->shutdown()
#5 [internal function]: OpenTelemetry\SDK\Metrics\MeterProvider->OpenTelemetry\SDK\Common\Util\{closure}()
#6 /script/vendor/open-telemetry/sdk/Common/Util/functions.php(51): Closure->call(Object(OpenTelemetry\SDK\Metrics\MeterProvider))
#7 /script/vendor/open-telemetry/sdk/Common/Util/ShutdownHandler.php(82): OpenTelemetry\SDK\Common\Util\{closure}()
#8 [internal function]: OpenTelemetry\SDK\Common\Util\ShutdownHandler::OpenTelemetry\SDK\Common\Util\{closure}(Array)
#9 {main} in /script/vendor/open-telemetry/api/Behavior/LogsMessagesTrait.php on line 47

<?php

declare(strict_types=1);

use OpenTelemetry\API\Common\Instrumentation\Globals;
use OpenTelemetry\API\Logs\EventLogger;
use OpenTelemetry\API\Logs\LogRecord;
use OpenTelemetry\API\Trace\Propagation\TraceContextPropagator;
use OpenTelemetry\Contrib\Otlp\LogsExporter;
use OpenTelemetry\Contrib\Otlp\MetricExporter;
use OpenTelemetry\Contrib\Otlp\SpanExporter;
use OpenTelemetry\SDK\Common\Attribute\Attributes;
use OpenTelemetry\SDK\Common\Export\Stream\StreamTransportFactory;
use OpenTelemetry\SDK\Logs\LoggerProvider;
use OpenTelemetry\SDK\Logs\Processor\SimpleLogsProcessor;
use OpenTelemetry\SDK\Metrics\MeterProvider;
use OpenTelemetry\SDK\Metrics\MetricReader\ExportingReader;
use OpenTelemetry\SDK\Resource\ResourceInfo;
use OpenTelemetry\SDK\Resource\ResourceInfoFactory;
use OpenTelemetry\SDK\Sdk;
use OpenTelemetry\SDK\Trace\Sampler\AlwaysOnSampler;
use OpenTelemetry\SDK\Trace\Sampler\ParentBased;
use OpenTelemetry\SDK\Trace\SpanProcessor\SimpleSpanProcessor;
use OpenTelemetry\SDK\Trace\TracerProvider;
use OpenTelemetry\SemConv\ResourceAttributes;
use OpenTelemetry\SDK\Common\Util\ShutdownHandler;

require 'vendor/autoload.php';

function returnEnvironmentVariables(){
        $envvars=getenv($name=null,$local_only=false);
        ksort($envvars);
        foreach($envvars as $key => $value){
                $format="%50s %s \n";
                printf($format,$key,$value);
        }
}

returnEnvironmentVariables();

$tracerProvider = Globals::tracerProvider();

ShutdownHandler::register([$tracerProvider, 'shutdown']);

Sdk::builder()
    ->setTracerProvider($tracerProvider)
    ->setMeterProvider($meterProvider)
    ->setLoggerProvider($loggerProvider)
    ->setPropagator(TraceContextPropagator::getInstance())
    ->setAutoShutdown(true)
    ->buildAndRegisterGlobal();

**What is the expected behavior?**
Script with OTel collector runs through.

**What is the actual behavior?**
I get and exception because there is a problem in the shutdown handler.

**Additional context**
* I added a couple of echos in the src folder to understand the code better
* I was not successful so far

**Comment by brettmc** [comment]
A "not found" when exporting is almost certainly a http 404 error. I can see from the backtrace that it's when shutting down a meter provider.
https://opentelemetry.io/docs/instrumentation/php/sdk/#autoloading mentions this, but what's happening is that the batch processor emits metrics about its internal state. It uses [default config](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Common/Configuration/Defaults.php#L60) if you don't provide any, which is localhost.

Short answer: `OTEL_METRICS_EXPORTER=none` will disable metrics.

**Comment by lhintzsc** [comment]
@brettmc: You are my hero. Problem resolved.

**Comment by scofield-ua** [comment]
I my case the problem was related to encoding.

On application side I had:
```
OTEL_EXPORTER_OTLP_PROTOCOL=http/json
```

when grafana alloy by [default](https://grafana.com/docs/alloy/latest/reference/components/otelcol/otelcol.exporter.otlphttp/#arguments) exporting as `protobuf`. So changing `http/json` to `http/protobuf` fixed the issue.

Would be great to see a more detailed error message in such case, because at first I thought the problem was related to observability :(

**Comment by brettmc** [comment]
> when grafana alloy by [default](https://grafana.com/docs/alloy/latest/reference/components/otelcol/otelcol.exporter.otlphttp/#arguments) exporting as protobuf

@scofield-ua that should not be a problem - the opentelemetry collector can accept telemetry in one encoding and export as another so I'd have thought alloy would be the same. I think it's more likely that alloy doesn't accept (or was not configured to accept) http/json encoding, and is responding with an http error. In your case, was there any detail in the alloy response that indicated the problem?

**Comment by scofield-ua** [comment]
@brettmc 

Interesting that I can't reproduce it anymore. 
It is working both with `OTEL_EXPORTER_OTLP_PROTOCOL=http/json` and `OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf`

So path looks like this:
```
Laravel app -> grafana alloy -> grafana tempo <- grafana 

env:
OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy.monitoring:4318
OTEL_EXPORTER_OTLP_PROTOCOL=http/json
```

Sorry for bothering.
