### ISSUE TITLE
MetricReader.ForceFlush is not part of the spec

### ISSUE THREAD

**Issue by brettmc** [open-telemetry/opentelemetry-php#1086]
From https://github.com/open-telemetry/community/issues/1536#issuecomment-1621988512

> MetricReader.ForceFlush is not part of the spec.
* https://github.com/open-telemetry/opentelemetry-php/blob/cc92a07eac5294055b0d477fb7e47d6480381505/src/SDK/Metrics/MetricReaderInterface.php#L13.
* https://github.com/open-telemetry/opentelemetry-specification/pull/3563

update: issue has been replaced by https://github.com/open-telemetry/opentelemetry-specification/pull/3609

**Comment by brettmc** [comment]
@reyang It looks like our implementation matches what [that PR is proposing](https://github.com/open-telemetry/opentelemetry-specification/pull/3563), should we just wait and watch? It also looks like we're doing what java does: https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/MetricReader.java#L54

**Comment by pellared** [comment]
In .NET SDK only the exporters implement `ForceFlush`. This is why https://github.com/open-telemetry/opentelemetry-specification/pull/3563 was rejected.

I think there is nothing wrong in your implementation. You may be interested in https://github.com/open-telemetry/opentelemetry-go/pull/4375 for inspiration.

**Comment by brettmc** [comment]
Thanks @pellared that was helpful. I think I understand now, and I'll look at splitting off another interface so that ForceFlush need only be implemented by a Push Metric Exporter. It's not required by a Pull exporter (although we don't actually have an implementation of one).

**Comment by pellared** [comment]
@brettmc FYI https://github.com/open-telemetry/opentelemetry-specification/pull/3563 is back in business, but it also supports the change. I would be thankful if you could review the specification PR.
