### ISSUE TITLE
When add the php tracing,  the pressure test shows the CPU usage increased  from 10% to 80%. is this normal？

### ISSUE THREAD

**Issue by commonfurture** [open-telemetry/opentelemetry-php#1103]
I have do a php performance testing about tracing and no-tracing，the details are presented below:
test performance tool：jmeter
concurrency users：10
business path：/api/php-api-1.php

The pressure test results are as follows
no tracing:
![1](https://github.com/open-telemetry/opentelemetry-php/assets/37206678/17498d13-a2ad-46ce-8f8c-2d0bdb799dfa)
![2](https://github.com/open-telemetry/opentelemetry-php/assets/37206678/a844ad6a-a815-4591-9bc0-c0345b1c00bb)

tracing（just add one span）：
![image](https://github.com/open-telemetry/opentelemetry-php/assets/37206678/48df755c-8c6c-4d9a-afd3-4b3c42152d17)
![image](https://github.com/open-telemetry/opentelemetry-php/assets/37206678/913168e0-2366-459a-b5c5-16ed423a8369)

From the above results, it can be seen that CPU consumption increases from 10% to 80% when add tracing. Is this normal？

**Comment by brettmc** [comment]
Can you add some more details about your setup for tracing? Such as:

- web server setup (apache, nginx, other)
- auto or manual tracing?
- batch or simple exporter
- how many spans per trace?
- where are you exporting to?
- export protocol? (otlp, zipkin)

If you can get any profiling data from php (eg via xdebug) which shows where the resources are being consumed, that would be very helpful.

**Comment by brettmc** [comment]
Also, can you confirm whether you are using the native protobuf library, or the C extension?

**Comment by brettmc** [comment]
@commonfurture ??

**Comment by brettmc** [comment]
Closing due to lack of response, please reopen or create a new issue if you have more info.

My best guess is that this is related to using the native protobuf library, which is known to perform terribly.
