### ISSUE TITLE
How is the export of opentelemetry sdk for php?

### ISSUE THREAD

**Issue by dwpoint** [open-telemetry/opentelemetry-php#1104]
Hello, tell me, please, in which files can I see the logic of exporting data from a request?

I'm very interested in how the following happens:
1. Is a local user queue created in the export request?
2. Export happens through a socket?

So, I guess it looks like this:
The user, for example, updates the page. Objects are created during execution. Tracer first. Further, based on it, spans are created. And, for example, some attributes are written to the span:
$span->setAttribute('name', $name);
$span->setAttribute('id', $email);

That's it, we have an object with data. And the question is how after they are exported? Is it just that the data at the end of the request is transferred through the socket in order of priority? Or how does it happen?

**Comment by brettmc** [comment]
You should also read the documentation for a general overview of how OpenTelemetry for PHP works: https://opentelemetry.io/docs/instrumentation/php/

Specifically, the info you are after is in multiple files, but this one is a good place to start for what you are asking about: https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Trace/SpanProcessor/BatchSpanProcessor.php

When a span is completed, it is sent to a span processor. For performance reasons, a batch processor is usually used. The completed span is queued in memory in the processor, and when some conditions are met (number of spans, time-based, or as part of request shutdown) the batch is sent to one or more exporters.
The exporter is responsible for converting the span into the correct format and sending it to a backend. We officially support zipkin and OTLP formats (protobuf over http, protobuf over grpc, JSON over http).

**Comment by brettmc** [comment]
Batch exporting uses an [SplQueue](https://www.php.net/manual/en/class.splqueue.php), which you can see in the file I linked earlier.

>And in any case, the user waits a little longer than without OpenTelemetry, right?

Right.

**Comment by brettmc** [comment]
> That is, during the request process, all information is collected in a queue, and at the end the queue is processed and exported. Right?

Yes, that's right. There are circumstances where it can be exported not at the end, which you can read about in [the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#batching-processor)

> Can I ask you, please, one more question on optimization? Maybe parameters (for example, sql) are logged before export in order to compress the data and export was faster? That is, maybe some "zip" algorithms are used to process SplQueue?

Compressing exported data is supported. Please read the spec, or the code.
