### ISSUE TITLE
php stack trace and traces' name with path

### ISSUE THREAD

**Issue by AwakenedViskasha** [open-telemetry/opentelemetry-php#1109]
Hello, maintainers and contributors ! I hope you are having a wonderful day !

I am currently using php auto instrumentation for a big Symfony project and I am quite happy with it since I am able to send my traces to ES/k stack with minimal coding. ( I can't  afford to manually instrument each endpoint...)

But I have a few questions : 

First, is it possible to retrieve php stack trace of every php method called since the original user call without manual instrumentation ? (e.g : user call /myInstrumentedEndpoint from a web client, in symfony, /myInstrumentedEndpoint call the method myprocessing(), I need to see a trace from myprocessing() too)

Second, my trace's name only mention the http method (get, post, etc...). How can I configure the auto instrumentation in order to name traces with their calling http path (like /myInstrumentedEndpoint) ?

I'm not sure if it's the right place to ask. If it's not, please guide me to somewhere or someone able to respond me.
Thank you for your time !

**Comment by brettmc** [comment]
Hello @AwakenedViskasha 
1. auto-instrumentation does not retrieve the current stack trace, except when an exception occurs. It sounds like you are actually asking about creating instrumentation for `myprocessing()` function, though? If that's the case, then the answer is that you can write your own auto-instrumentation code to listen on calls to `myprocessing()`, much like the auto-instrumentation modules do. We don't auto-instrument all calls, that would be a lot of instrumentation!
2. That's not a configuration option. We're currently discussing what might be a good name for trace names. Symfony _should_ be using the route name, if you have one configured. It's part of the OpenTelemetry specification that span names have low cardinality: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.24.0/specification/trace/api.md#span
Also keep in mind that the full URI is stored against the span as an attribute.

**Comment by AwakenedViskasha** [comment]
Thank you @brettmc !

I agree with you about 1 maybe it's not a good idea. Adding PDO and I-O auto-instrumentation might be enough for our needs. 

About question 2, I will just rewrite the span name in the otel collector.

Also we MAY plan to contribute on the project with Redis and PSQL auto instrumentation for php later this year...
