### ISSUE TITLE
[OpenTelemetry PHP Extention]: PHP Extention issue in CENT OS 

### ISSUE THREAD

**Issue by venkata-ramana** [open-telemetry/opentelemetry-php#1117]
**Describe your environment** 
OS - CentOS Linux release 7.9.2009 (Core)
Spinning up on docker
Docker version 20.10.23

PHP Version 8.1

Configuration File (php.ini) Path: /etc/opt/remi/php81
Loaded Configuration File:         /etc/opt/remi/php81/php.ini
Scan for additional .ini files in: /etc/opt/remi/php81/php.d
Additional .ini files parsed:      /etc/opt/remi/php81/php.d/15-xdebug.ini

PEAR AND PECL VERSION

PEAR Version: 1.10.13
PHP Version: 8.1.23
Zend Engine Version: 4.1.23
Running on: Linux d4ed702be027 5.15.128-81.144.amzn2.x86_64 #1 SMP Wed Sep 6 21:02:12 UTC 2023 x86_64

**Steps to reproduce**
pecl install channel://pecl.php.net/opentelemetry-1.0.0RC1

**What is the expected behavior?**
it should install open telemetry

**What is the actual behavior?**
throwing following exceptions shared in the additional context

**Additional context**
/bin/sh /tmp/pear/install/pear-build-defaultuser2iBx1b/opentelemetry-1.0.0beta6/libtool --mode=compile cc -I. -I/tmp/pear/install/opentelemetry -I/tmp/pear/install/pear-build-defaultuser2iBx1b/opentelemetry-1.0.0beta6/include -I/tmp/pear/install/pear-build-defaultuser2iBx1b/opentelemetry-1.0.0beta6/main -I/tmp/pear/install/opentelemetry -I/opt/remi/php81/root/usr/include/php -I/opt/remi/php81/root/usr/include/php/main -I/opt/remi/php81/root/usr/include/php/TSRM -I/opt/remi/php81/root/usr/include/php/Zend -I/opt/remi/php81/root/usr/include/php/ext -I/opt/remi/php81/root/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2    -DZEND_COMPILE_DL_EXT=1 -c /tmp/pear/install/opentelemetry/otel_observer.c -o otel_observer.lo  -MMD -MF otel_observer.dep -MT otel_observer.lo
libtool: compile:  cc -I. -I/tmp/pear/install/opentelemetry -I/tmp/pear/install/pear-build-defaultuser2iBx1b/opentelemetry-1.0.0beta6/include -I/tmp/pear/install/pear-build-defaultuser2iBx1b/opentelemetry-1.0.0beta6/main -I/tmp/pear/install/opentelemetry -I/opt/remi/php81/root/usr/include/php -I/opt/remi/php81/root/usr/include/php/main -I/opt/remi/php81/root/usr/include/php/TSRM -I/opt/remi/php81/root/usr/include/php/Zend -I/opt/remi/php81/root/usr/include/php/ext -I/opt/remi/php81/root/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -DZEND_COMPILE_DL_EXT=1 -c /tmp/pear/install/opentelemetry/otel_observer.c -MMD -MF otel_observer.dep -MT otel_observer.lo  -fPIC -DPIC -o .libs/otel_observer.o
/tmp/pear/install/opentelemetry/otel_observer.c: In function ‘observer_begin’:
/tmp/pear/install/opentelemetry/otel_observer.c:151:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (zend_llist_element *element = hooks->head; element;
     ^
/tmp/pear/install/opentelemetry/otel_observer.c:151:5: note: use option -std=c99 or -std=gnu99 to compile your code
/tmp/pear/install/opentelemetry/otel_observer.c:181:25: error: ‘for’ loop initial declarations are only allowed in C99 mode
                         for (uint32_t i = arg_count; i < idx; i++) {
                         ^
/tmp/pear/install/opentelemetry/otel_observer.c:216:13: error: ‘for’ loop initial declarations are only allowed in C99 mode
             for (uint32_t i = 0; i < arg_count; i++) {
             ^
/tmp/pear/install/opentelemetry/otel_observer.c:228:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < param_count; i++) {
     ^
/tmp/pear/install/opentelemetry/otel_observer.c: In function ‘observer_end’:
/tmp/pear/install/opentelemetry/otel_observer.c:251:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (zend_llist_element *element = hooks->tail; element;
     ^
/tmp/pear/install/opentelemetry/otel_observer.c:303:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < param_count; i++) {
     ^
/tmp/pear/install/opentelemetry/otel_observer.c: In function ‘find_observers’:
/tmp/pear/install/opentelemetry/otel_observer.c:357:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (zend_llist_element *element = observer->pre_hooks.head; element;
         ^
/tmp/pear/install/opentelemetry/otel_observer.c:362:34: error: redefinition of ‘element’
         for (zend_llist_element *element = observer->post_hooks.head; element;
                                  ^
/tmp/pear/install/opentelemetry/otel_observer.c:357:34: note: previous definition of ‘element’ was here
         for (zend_llist_element *element = observer->pre_hooks.head; element;
                                  ^
/tmp/pear/install/opentelemetry/otel_observer.c:362:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (zend_llist_element *element = observer->post_hooks.head; element;
         ^
/tmp/pear/install/opentelemetry/otel_observer.c: In function ‘find_class_observers’:
/tmp/pear/install/opentelemetry/otel_observer.c:383:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (uint32_t i = 0; i < ce->num_interfaces; i++) {
         ^
make: *** [otel_observer.lo] Error 1
ERROR: `make' failed

**Comment by vijay94** [comment]
ENV CC="c99" should fix this.

**Comment by brettmc** [comment]
Also, @venkata-ramana I see that you're installing PHP and some extensions via remi repo. The OpenTelemetry extension is available in that repo, you could try installing it from there.
If you do, please report back on how you went (I'd like to add instructions to our docs over on opentelemetry.io)

**Comment by venkata-ramana** [comment]
@brettmc remi repo was smooth to install PHP 

for php extentions I suggest not to use pear or pecl in CENTOS. 

pecl tries to run make file on your machine this cause a lot of issues due to gcc dependencies.

fortunately there are alternatives we can use

`RUN yum install php81-php-pecl-opentelemetry -y`
`RUN echo "extension=opentelemetry.so" >> //etc/opt/remi/php81/php.ini`
`RUN php -m | grep opentelemetry`

to install GRPC 

`RUN yum install php81-php-pecl-grpc -y`
`RUN echo "extension=grpc.so" >> //etc/opt/remi/php81/php.ini`

**Comment by brettmc** [comment]
This is great info, thanks @venkata-ramana
I will add this to our documentation to help others.
