### ISSUE TITLE
Is there any documentation or example for implementing Logs in stable versions of Opentelemetry?

### ISSUE THREAD

**Issue by vanessafsphp** [open-telemetry/opentelemetry-php#1123]
I'm having difficulty finding content that indicates this, because in the project I'm working on I can't use the versions with minimum stability indicated.

What do I do to generate logs with Opentelemetry version 0.0.17?

**Comment by brettmc** [comment]
Hi @vanessafsphp
"stable" is a bit misleading here, 0.0.17 is an alpha version (but, composer considers it stable).
Logs (as in, the OpenTelemetry Logging signal) was not introduced until 03/2023 (eg https://github.com/opentelemetry-php/api/releases/tag/1.0.0beta5)
So, if you can't install the latest RC versions of the packages, then you'll need to wait for 1.0.0 which I think is a couple of weeks away.

**Comment by vanessafsphp** [comment]
@brettmc  Any predictions for the official release of version 1.0.0?

**Comment by brettmc** [comment]
It's very close, but I don't have a date for you. It was discussed at our weekly SIG meeting last week, and will be again tomorrow. My guess is in about a week, if nothing goes wrong.

**Comment by brettmc** [comment]
1.0.0 is out, so you should be able to update and start using Logs now :)
