### ISSUE TITLE
Implement a Meter Interface

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#113]
We need to implement a meter interface, as defined in: 
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#meter-interface

Success criteria: Creating a Meter Interface in the API.

**Comment by Fahmy-Mohammed** [comment]
I've started work on this.

**Comment by artem-prozorov** [comment]
@Fahmy-Mohammed Hi, any news on this issue?

**Comment by bobstrecansky** [comment]
Talked to Amber in our SIG meeting today; Fahmy is on vacation this week but is almost completed with the work on this PR.  Amber said to expect some information next week.

**Comment by bobstrecansky** [comment]
@artem-prozorov made a stub for this [here](https://github.com/open-telemetry/opentelemetry-php/blob/master/sdk/Metrics/Meter.php) and @Fahmy-Mohammed mentioned his PR was almost ready for review.

**Comment by Fahmy-Mohammed** [comment]
Apologies for the delay. PR is ready for a look 👍🏾

**Comment by bobstrecansky** [comment]
Fahmy completed this work in https://github.com/open-telemetry/opentelemetry-php/pull/165, closing this ticket.
