### ISSUE TITLE
Breaking change with package open-telemetry/sem-conv

### ISSUE THREAD

**Issue by alejandro-mejias** [open-telemetry/opentelemetry-php#1130]
The package open-telemetry/sem-conv (https://github.com/opentelemetry-php/sem-conv/) has made a breaking update. In this package, constants from src/SemConv/ResourceAttributes.php and src/SemConv/TraceAttributes.php have been removed. There are packages like open-telemetry/opentelemetry-auto-laravel or open-telemetry-exporter-otlp  that are failing for requiring constants that no longer exist in the latest version of open-telemetry/sem-conv.

Thank you.

**Comment by brettmc** [comment]
I've tagged 1.22.1 of SemConv, which adds back the removed attributes (they are marked as deprecated). I don't believe any ResourceAttributes were removed?
There is also a PR over in -contrib to update the affected packages.

**Comment by brettmc** [comment]
All of the contrib packages should be fixed now. Thanks for the bug report, @alejandro-mejias

**Comment by alejandro-mejias** [comment]
Everything is ok now. Thank you so much @brettmc
