### ISSUE TITLE
Creating a MeterProvider API

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#114]
We need to implement a MeterProvider, as perscribed in:
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#meter-provider

Success criteria - Creating a MeterProvider Implementation in the API and tying it to the eventual SDK.  This part is slightly ambiguous with the documentation, so it may be best to look at other SIG implementations for inspiration.

**Comment by artem-prozorov** [comment]
@bobstrecansky I'll take this one

**Comment by artem-prozorov** [comment]
@bobstrecansky hey I just realized this task has already been coompleted in this PR: https://github.com/open-telemetry/opentelemetry-php/pull/155

MeterProvider: https://github.com/open-telemetry/opentelemetry-php/blob/884648cfd5d75553b4af77ba0a076288372897b2/sdk/Metrics/Providers/MeterProvider.php
GlobalMeterProvider: https://github.com/open-telemetry/opentelemetry-php/blob/884648cfd5d75553b4af77ba0a076288372897b2/sdk/Metrics/Providers/GlobalMeterProvider.php

We need a `Meter` class to be implmented to finish the `getCreatedMeter` method.

I'll continue with this one as soon I have a Meter class and once my PR https://github.com/open-telemetry/opentelemetry-php/pull/155 is merged

**Comment by bobstrecansky** [comment]
Sounds good to me!

**Comment by artem-prozorov** [comment]
Looks like this one can be closed
