### ISSUE TITLE
Install opentelemetry on windows, but get ERROR: The DSP opentelemetry.dsp does not exist.

### ISSUE THREAD

**Issue by aibooster0** [open-telemetry/opentelemetry-php#1143]
I try to install php auto opentelemetry on windows with pecl, but get this error. Is it possible to use auto instrement on windows?

```
 ./pecl.bat install http://pecl.php.net/get/opentelemetry-1.0.0.tgz
downloading opentelemetry-1.0.0.tgz ...
Starting to download opentelemetry-1.0.0.tgz (21,924 bytes)
........done: 21,924 bytes
9 source files, building
ERROR: The DSP opentelemetry.dsp does not exist.

```

**Comment by brettmc** [comment]
Yes, some folks have been able to install and use the extension under windows. Try the pre-built DLLs: https://github.com/open-telemetry/opentelemetry-php-instrumentation/releases/tag/1.0.0

**Comment by aibooster0** [comment]
But after I download the dll and put it in the ext directory, and add the extension config to php.ini(I also tried the absolute path). It shows cannot find the dll when I execute php command.

PHP Warning:  PHP Startup: Unable to load dynamic library 'd:/Programs/WinNMP/bin/php/php-8.2.10-Win32-vs16-x64/ext/php_opentelemetry.dll' (tried: d:/Programs/WinNMP/bin/php/php-8.2.10-Win32-vs16-x64/ext/php_opentelemetry.dll (找不到指定的模块。), ext\php_d:/Programs/WinNMP/bin/php/php-8.2.10-Win32-vs16-x64/ext/php_opentelemetry.dll.dll (找不到指定的模块。)) in Unknown on line 0

but the file path exists.

 ls -l 'd:/Programs/WinNMP/bin/php/php-8.2.10-Win32-vs16-x64/ext/php_opentelemetry.dll'
-rwxr-xr-x 1 pp 197121 25088 11月 20 09:53 d:/Programs/WinNMP/bin/php/php-8.2.10-Win32-vs16-x64/ext/php_opentelemetry.dll*

ldd 'd:/Programs/WinNMP/bin/php/php-8.2.10-Win32-vs16-x64/ext/php_opentelemetry.dll'
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7ffc4a270000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7ffc498b0000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7ffc47750000)
        php_opentelemetry.dll => /d/Programs/WinNMP/bin/PHP/php-8.2.10-Win32-vs16-x64/ext/php_opentelemetry.dll (0x7ffc42b40000)
        ucrtbase.dll => /c/Windows/System32/ucrtbase.dll (0x7ffc47ea0000)
        vcruntime140.dll => /c/Windows/System32/vcruntime140.dll (0x7ffc30f00000)

**Comment by brettmc** [comment]
I'm curious about the `Win32` in your path - does that mean this is a 32bit windows install? That could be the problem, as the dlls are built for 64bit (non-thread-safe)

**Comment by aibooster0** [comment]
```
php8 -v
PHP 8.2.10 (cli) (built: Aug 29 2023 21:51:44) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.10, Copyright (c) Zend Technologies
```

**Comment by aibooster0** [comment]
`php8 -i | grep -i architecture
Architecture => x64
PROCESSOR_ARCHITECTURE => AMD64
$_SERVER['PROCESSOR_ARCHITECTURE'] => AMD64
`

**Comment by brettmc** [comment]
> PHP 8.2.10 (cli) (built: Aug 29 2023 21:51:44) (ZTS Visual C++ 2019 x64)

ZTS = thread-safe, right? The DLLs are built for NTS so I'm pretty sure it won't be compatible. Is thread safety important to you?

**Comment by aibooster0** [comment]
No, I'll try the non NTS version.

**Comment by aibooster0** [comment]
@brettmc Thankyou very much, when i change the php to the nts version, it works.

**Comment by brettmc** [comment]
> Hi did you ever build thread safe dlls? I am using WAMP64 and they always deliver Thread Safe versions of php.

Hi @ben-tripcity I just threw up a branch which does TS builds, and it seems to have built and tests passed - can you:
1. test it out: https://github.com/open-telemetry/opentelemetry-php-instrumentation/actions/runs/10440051412
2. create an issue (over in opentelemetry-php) for threadsafe builds where we can discuss, rather than re-using this issue

**Comment by ben-tripcity** [comment]
Sorry for not responding sooner I had a email rule that puts all my github stuff in a folder.  I will check it when I get a chance.  Thanks!

**Comment by brettmc** [comment]
@ben-tripcity thanks. It's not in a branch anymore, you should find it in releases since this PR got merged.
