### ISSUE TITLE
[contrib-auto-symfony] Subrequests 

### ISSUE THREAD

**Issue by DrLuke** [open-telemetry/opentelemetry-php#1147]
I'd like to start a discussion on how to handle [symfony subrequests](https://symfony.com/doc/6.3/components/http_kernel.html#sub-requests).

One great example of subrequests is the `ErrorController` that renders the red exception page with a stack trace when you have an uncaught exception in your application.

Because the `ErrorController` has no route set, it's span name is just "GET", which is not helpful at all:

<img width="1219" alt="Example trace from APM showing the main HttpKernel::handle() span labelled GET app_wip_wip, and a second trace below that for the error controller that is just labelled as GET" src="https://github.com/open-telemetry/opentelemetry-php/assets/1679780/e7e787d0-9a78-4943-a189-bd60f6ed5a80">

## Discussion points
1. Should `HttpKernel::handle()` span names contain the controller as well?
2. Does it make sense that a subrequest gets `SpanKind::KIND_SERVER`?
3. Should the `ErrorController` span really be marked as failed even though it correctly output a stack trace?

**Comment by brettmc** [comment]
> Should HttpKernel::handle() span names contain the controller as well?

Not if they're treated like other requests, since the spec tells us how root spans should be named. It's quite possible that we just haven't considered sub-requests and they should be handled differently though - can you tell from the Request whether it's a main or subrequest? I think it would be fine to do that so that sub requests are more meaningfully named.

> Does it make sense that a subrequest gets SpanKind::KIND_SERVER?

Maybe INTERNAL? see https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#spankind

> Should the ErrorController span really be marked as failed even though it correctly output a stack trace?

That probably depends on the response code of the controller? It it a 20x or a 50x? I don't have a strong opinion, though - what makes the most sense?

**Comment by dkarlovi** [comment]
@brettmc 

> can you tell from the Request whether it's a main or subrequest?

Yes, when the request is being handled, [the request type is passed into the method](https://github.com/symfony/symfony/blob/37d91c760bd91c431f91999c243d3d2ee76853dc/src/Symfony/Component/HttpKernel/HttpKernel.php#L155).

**Comment by brettmc** [comment]
@dkarlovi @DrLuke Can you please review the linked PR for this? I don't have a symfony app to test this against, but it looks like you do. I added tests and they pass, which is a start.

**Comment by dkarlovi** [comment]
I do not have a Symfony app with subrequests which is also OTEL instrumented available ATM, sorry. Hopefully @DrLuke can help.

**Comment by DrLuke** [comment]
@brettmc Great work, this is what it looks like in my APM:
<img width="1212" alt="image" src="https://github.com/open-telemetry/opentelemetry-php/assets/1679780/43af064d-ce20-4c69-8f4b-c484c313d568">

The sub-request is displayed as internal 👍

**Comment by dkarlovi** [comment]
@DrLuke what APM app / UI is that?

**Comment by DrLuke** [comment]
> @DrLuke what APM app / UI is that?

Elastic APM

**Comment by brettmc** [comment]
@DrLuke @dkarlovi I've just released a new beta of the symfony auto-instrumentation. If you're happy with it, report back as I plan to release `1.0.0` if there are no other issues.
