### ISSUE TITLE
Associating Spans with their TracerProvider

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#115]
In [The Initial Resource SDK PR](https://github.com/open-telemetry/opentelemetry-php/pull/101), @lalex added the Resource SDK to Tracer and TracerProvider. The spec states:

> When used with distributed tracing, a resource can be associated with the TracerProvider when it is created. That association cannot be changed later. When associated with a TracerProvider, all Spans produced by any Tracer from the provider MUST be associated with this Resource.

This issue is to track the work of associating Spans with their TracerProvider.

**Comment by bobstrecansky** [comment]
@zsistla is working on is.

**Comment by zsistla** [comment]
I'll work on this :)

**Comment by bobstrecansky** [comment]
Closing this because we are going to eventually skip more towards a more recent alpha release.

**Comment by zsistla** [comment]
Hi Bob, I think this was erroneously closed when the alpha 0.2s were closed last week.

See PR: https://github.com/open-telemetry/opentelemetry-php/pull/215

status should be `pending review`.

**Comment by bobstrecansky** [comment]
Sorry Amber.  I'll merge that tomorrow if I don't hear any gripes from the other maintainers and I'll close this at that time.
