### ISSUE TITLE
 [opentelemetry-php-instrumentation] - memory leak in tests/multiple_hooks_modify_returnvalue.phpt

### ISSUE THREAD

**Issue by brettmc** [open-telemetry/opentelemetry-php#1154]
When running the tests with valgrind, `tests/multiple_hooks_modify_returnvalue.phpt` reports a memory leak:
[valgrind.txt](https://github.com/open-telemetry/opentelemetry-php-instrumentation/files/12138566/valgrind.txt)

I checked against the current release (1.0.0beta6) and it is also an issue there.

**Comment by agoallikmaa** [comment]
@brettmc I tried reproducing this (latest main branch, on debug build of 8.2) but get a clean report from valgrind. There have been plenty of changes since you reported it. Can you double-check that you don't get this anymore either?

**Comment by brettmc** [comment]
re-tested, and no memory leak was reported.
