### ISSUE TITLE
Implement a Counter Instrument for the Metrics API

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#116]
We would like to implement a Counter Instrument for the Metrics API.  The spec for the counter API is defined at the following URL:

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#counter

**Comment by zsistla** [comment]
I'm working on this.

**Comment by zsistla** [comment]
It looks like Artem is already working on this in his PR, so I'll work on something else.

**Comment by bobstrecansky** [comment]
@artem-prozorov assigning this to ya.

**Comment by bobstrecansky** [comment]
For some reason it won't let me assign Artem; but we know he is working on this.

**Comment by artem-prozorov** [comment]
@bobstrecansky I think this one can be closed, the Counter has been implemented
