### ISSUE TITLE
Implement an UpDownCounter Instrument for the Metrics API

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#117]
We would like to implement an UpDownCounter Instrument for the Metrics API.   The spec for the UpDownCounter API is defined at the following URL:

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#updowncounter

**Comment by zsistla** [comment]
I've uploaded a PR for this.

**Comment by bobstrecansky** [comment]
This should be ready and can be merged after #155 is merged.

**Comment by bobstrecansky** [comment]
This has been completed with #157
