### ISSUE TITLE
 Implement a ValueRecorder Instrument for the Metrics API

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#118]
We would like to implement a ValueRecorder Instrument for the Metrics API.  The spec for the ValueRecorder API is defined at the following URL:

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#valuerecorder

**Comment by zsistla** [comment]
I am working on this one now.

**Comment by bobstrecansky** [comment]
This should be ready and can be merged after #155 is merged.

**Comment by bobstrecansky** [comment]
This has been completed with #158
