### ISSUE TITLE
Support for Jaeger Propagator

### ISSUE THREAD

**Issue by weslenteche** [open-telemetry/opentelemetry-php#1187]
The [OpenTelemetry specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#propagators-distribution) suggests that a propagator for Jaeger MUST be implemented.

**Is your feature request related to a problem?**

Some applications, typically third party, rely on "older" implementations of Opentracing using the Jaeger tracing context and this information is not being linked to the current PHP library.

**Describe the solution you'd like**

Adding a propagator that implements, understands and propagate the [Jaeger (uber header)](https://www.jaegertracing.io/docs/latest/client-libraries/#propagation-format) format.

**Additional context**
If it really hasn't been implemented, I'd love to contribute a PR

**Comment by brettmc** [comment]
I don't remember us ever having a jaeger propagator. We removed the jaeger exporter in #890 when the client libraries were abandoned, but that doesn't mean the propagator can't be implemented. It can go in the Extension dir alongside B3 and CloudTrace if you'd like to have a go at implementing.

**Comment by weslenteche** [comment]
Thanks for the answer, I'll start working on it
