### ISSUE TITLE
 Implement a SumObserver Instrument for the Metrics API

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#119]
We would like to  Implement a SumObserver Instrument for the Metrics API.  The spec for the SumObserver API is defined at the following URL:

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#sumobserver

**Comment by YashKumarVerma** [comment]
Hello there, i believe I can work on this.

Are there any specific things to keep in mind while implementing this?

**Comment by bobstrecansky** [comment]
Not that I'm aware of! Feel free to ask questions in the gitter channel if you get stuck.

**Comment by YashKumarVerma** [comment]
alright, I went through the codebase, also took references from implementation in the js version, and have a few queries.

1. in the js version, there is a class named [`BaseObserverMetric`](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-metrics/src/BaseObserverMetric.ts#L31) which has been extended to implement observer* instruments. Should we do something similar here as well?
2. how do we ensure the `asynchronous` nature?

**Comment by bobstrecansky** [comment]
1.). Seems reasonable.  You can always read through the specification to verify:

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md

2.) Async programming is notorious for being burdensome for php.  The spatie library night be a good jumping off point:

https://dev.to/webong/using-asynchronous-processes-in-php-7io

**Comment by bobstrecansky** [comment]
This was removed from the spec, removing here.
