### ISSUE TITLE
Add auto instrumentation for PSR-6 (Caching Interface) and PSR-16 (Simple Cache)

### ISSUE THREAD

**Issue by xvilo** [open-telemetry/opentelemetry-php#1190]
## Overview:
Currently, the OpenTelemetry PHP repository does not have libraries to enable auto-instrumentation for PSR-6 (Caching Interface) and PSR-16 (Simple Cache) standards. Adding support for these PSR standards would be beneficial to the observability of caching systems used in PHP applications

## Expected Behavior:
When OpenTelemetry is integrated into a PHP application, it should automatically instrument and trace operations related to caching using PSR-6 and PSR-16 standards.

## Additional Context:
The adoption of PSR-6 and PSR-16 is widespread in PHP applications, and caching is a critical aspect of performance optimization. Incorporating auto-instrumentation for these standards will enable developers to gain insights into caching behaviors, identify performance bottlenecks, and troubleshoot issues efficiently.

## Proposal:
- Integrate auto-instrumentation for PSR-6, covering common caching operations such as get, set, delete, etc.
- Integrate auto-instrumentation for PSR-16, capturing key caching operations.

## References:
- [PSR-6: Caching Interface](https://www.php-fig.org/psr/psr-6/)
- [PSR-16: Simple Cache](https://www.php-fig.org/psr/psr-16/)

## Impact:
This enhancement will benefit developers by providing detailed traces and metrics related to caching operations, contributing to a more comprehensive understanding of application performance.

**Comment by weslenteche** [comment]
@brettmc Do you know if anyone is working on this issue? Anything I would like to contribute to this issue

**Comment by brettmc** [comment]
I don't think that anybody is working on it - I will assign it to you.
