### ISSUE TITLE
Segfault with phpunit when a test uses @runInSeparateProcess

### ISSUE THREAD

**Issue by ArtemisMucaj** [open-telemetry/opentelemetry-php#1195]
**Describe your environment** 

I'm observing a segmentation fault when using _phpunit_ with the _opentelemetry_ extension, the error happens when the test is annotated with @runInSeparateProcess. My code inside a docker container with the following PHP version.

```
PHP 8.1.26 (cli) (built: Dec 16 2023 06:00:50) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.26, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.26, Copyright (c), by Zend Technologies
    with Xdebug v3.3.1, Copyright (c) 2002-2023, by Derick Rethans
```
I have installed the _opentelemetry_ extension through PECL, during my test I have disabled the OTEL autoloader through the environment variable OTEL_PHP_AUTOLOAD_ENABLED=false

```
opentelemetry

opentelemetry hooks => enabled
extension version => 1.0.0

Directive => Local Value => Master Value
opentelemetry.conflicts => no value => no value
opentelemetry.validate_hook_functions => On => On
```

**Steps to reproduce**

Command to run
`./vendor/bin/phpunit test/Test.php`

Output
```
HPUnit 9.6.15 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 00:00.279, Memory: 6.00 MB

There was 1 error:

1) Root\TestPhpSegfault\Test::testSegfault
PHPUnit\Framework\Exception: Segmentation fault (core dumped)

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

test/Test.php file
```
<?php

namespace Root\TestPhpSegfault;

use PHPUnit\Framework\TestCase;

final class Test extends TestCase
{
    /**
     * A test that creates a segmentation fault
     *
     * @runInSeparateProcess
     */
    public function testSegfault(): void
    {
        // Do nothing
    }
}
```

composer.json file
```
{
    "name": "root/test-php-segfault",
    "autoload": {
        "psr-4": {
            "Root\\TestPhpSegfault\\": "src/"
        }
    },
    "require": {
      "phpunit/phpunit": "^9.5"
    }
}
```
Describe exactly how to reproduce the error. Include a code sample if applicable.

**What is the expected behavior?**
No segmentation fault

**What is the actual behavior?**
Test case errors due to a segmentation fault

**Comment by brettmc** [comment]
If you were to run this via a debugger, can you see what code is being run when the segfault occurs?

**Comment by ArtemisMucaj** [comment]
I tried running it with GDB however I couldn't get anything else except that it segfaults. I've never used gdb with PHP before however so I may have been doing it wrong.

If you have some advice or links to material I can investigate a bit further.

**Comment by agoallikmaa** [comment]
Some context from reproducing with gdb attached:

```
(gdb) bt
#0  0x00005555558bfd25 in zend_restore_ini_entry_cb (ini_entry=0x555555cb2d60, stage=stage@entry=8) at ./Zend/zend_ini.c:61
#1  0x00005555558c0673 in zend_ini_deactivate () at ./Zend/zend_ini.c:136
#2  0x000055555584e4d5 in zend_deactivate () at ./Zend/zend.c:1262
#3  0x00005555557e7809 in php_request_shutdown (dummy=dummy@entry=0x0) at ./main/main.c:1863
#4  0x0000555555933e3d in do_cli (argc=1, argv=0x555555aea150) at ./sapi/cli/php_cli.c:1135
#5  0x000055555567bfd7 in main (argc=1, argv=0x555555aea150) at ./sapi/cli/php_cli.c:1333
(gdb) x/i $pc
=> 0x5555558bfd25 <zend_restore_ini_entry_cb+293>:	call   *0x8(%rax)
(gdb) p *(zend_ini_entry*)$rax
$12 = {name = 0x555555cb2, on_modify = 0xf4701629a7848fac, mh_arg1 = 0x20, mh_arg2 = 0x7ffff52412c0 <opentelemetry_globals>, mh_arg3 = 0x0, value = 0x555555af45c0, orig_value = 0x555555af45c0, displayer = 0x0, 
  module_number = 17, modifiable = 7 '\a', orig_modifiable = 7 '\a', modified = 1 '\001'}
(gdb) x/i 0xf4701629a7848fac
   0xf4701629a7848fac:	Cannot access memory at address 0xf4701629a7848fac

```

The referenced line (zend.ini.c:61):
https://github.com/php/php-src/blob/php-8.2.7/Zend/zend_ini.c#L61
```c
static zend_result zend_restore_ini_entry_cb(zend_ini_entry *ini_entry, int stage) /* {{{ */
// L61:
result = ini_entry->on_modify(ini_entry, ini_entry->orig_value, ini_entry->mh_arg1, ini_entry->mh_arg2, ini_entry->mh_arg3, stage);
```

So it seems there is some issue with the way `@runInSeparateProcess` launches processes combined with INI entries of the extension. If the extension is compiled with all INI entries removed, this case no longer reproduces.

The documentation for `@runInSeparateProcess` has this paragraph:

> Note: By default, PHPUnit will attempt to preserve the global state from the parent process by serializing all globals in the parent process and unserializing them in the child process. This can cause problems if the parent process contains globals that are not serializable. See [@preserveGlobalState](https://docs.phpunit.de/en/9.6/annotations.html#appendixes-annotations-preserveglobalstate) for information on how to fix this.

Indeed, when also adding `@preserveGlobalState disabled`, then the crash goes away. What that setting did when enabled, among others, is get all INI settings, and set them in the new process (even if they had default values). This made it seem like the issue was triggered by `ini_set`. Indeed I seem to be able to reproduce the crash with a simple:

```php
<?php
ini_set('opentelemetry.conflicts', 'test');
```

This should make it simpler to investigate further.

**Comment by brettmc** [comment]
@ArtemisMucaj the fix is in https://github.com/open-telemetry/opentelemetry-php-instrumentation/releases/tag/1.0.1beta1 - could you test and verify?

**Comment by ArtemisMucaj** [comment]
Tested with 1.0.1beta1 and it works as expected.

Thank you :)
