### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by runtu666** [open-telemetry/opentelemetry-php#1196]
1.Is there any example that I can refer to? Can I automatically access the yii2 framework with zero code?
2.I found that I set the environment variable
OTEL_EXPORTER_OTLP_TIMEOUT=1
OTEL_EXPORTER_OTLP_TRACES_TIMEOUT=1
It has no effect. I hope to set a timeout. When the timeout expires, data will no longer be sent to the collector.

3.After I used Automatic Instrumentation, I found that the CPU usage doubled. Is this normal?

**Comment by brettmc** [comment]
Hello.
1. Yes, if https://github.com/open-telemetry/opentelemetry-php-contrib/tree/main/src/Instrumentation/Yii is installed, you should get a single root span for each request
2. Timeouts are not implemented yet for HTTP transport, but is for gRPC
3. No, that's not expected. The usual explanation for this is that you're using the native protobuf library, which is very slow. Could that be your issue?

**Comment by runtu666** [comment]
@brettmc 

1. How to download this library? Is there any detailed access document that I can refer to?
2. I am using grpc, but this environment variable still does not work. My environment variables:
OTEL_PHP_AUTOLOAD_ENABLED=true
OTEL_SERVICE_NAME=otel-demo-php
OTEL_TRACES_EXPORTER=otlp
OTEL_EXPORTER_OTLP_PROTOCOL=grpc
OTEL_EXPORTER_OTLP_ENDPOINT=xxxx
OTEL_PROPAGATORS=baggage,tracecontext
OTEL_EXPORTER_OTLP_TIMEOUT=1
OTEL_EXPORTER_OTLP_TRACES_TIMEOUT=1
3.Maybe yes

**Comment by brettmc** [comment]
You can install the autp-instrumentation package via composer: `composer require open-telemetry/opentelemetry-auto-yii`
https://opentelemetry.io/docs/instrumentation/php/getting-started/ uses a different framework (Slim instead of Yii), but otherwise everything should be the same
Can you also confirm that you have installed the opentelemetry extension? That's covered in https://opentelemetry.io/docs/instrumentation/php/automatic/#installation

**Comment by runtu666** [comment]
@brettmc 
# php -m | grep open
openssl
opentelemetry

yes I do have installed the opentelemetry extension，I have installed this ext and package of tand yii, what else do I need to do?Can this be implemented with zero code?

**Comment by runtu666** [comment]
I suggest writing a document to teach you how to access the yii2 framework with zero code. If I can do it, I will write a document for you.

**Comment by brettmc** [comment]
https://github.com/opentelemetry-php/example-auto-yii
Can you run that and then compare to your setup? If it works, then we'd love a documentation patch that clarifies the setup please :)

**Comment by runtu666** [comment]
ok I'll try it

**Comment by runtu666** [comment]
@brettmc 
This is indeed useful. I will write a document for you later. Where should the document be placed?
By the way,
1. How do we set the timeout in this way?
2. Is this method of reporting data synchronously or asynchronously? Will it affect the business because the data reporting time is too long?

**Comment by bobstrecansky** [comment]
> This is indeed useful. I will write a document for you later. Where should the document be placed?

You can place the document in the [Yii contrib folder](https://github.com/open-telemetry/opentelemetry-php-contrib/tree/main/src/Instrumentation/Yii)


> How do we set the timeout in this way?
What are you attempting to set a timeout for?  Are you using OTLP or HTTP? 

In your original question, you mentioned: `It has no effect. I hope to set a timeout. When the timeout expires, data will no longer be sent to the collector.` - the timeout isn't for turning off the communication between the application and the server, it's the timeout for the client before it no longer sends that particular trace to the server.

> Is this method of reporting data synchronously or asynchronously? Will it affect the business because the data reporting time is too long?

This happens asynchronously.  It should not affect the business because data reporting time is too long.  There are many clients that use this library with large volume.

> How do I get the traceId in the code? I want to record the traceId in the log to facilitate troubleshooting.

You should be able to call `getTraceID` from the `context` variable.

**Comment by brettmc** [comment]
> This is indeed useful. I will write a document for you later. Where should the document be placed?

Also please look at https://opentelemetry.io/docs/instrumentation/php/automatic/ - that's where we try to centralize all documentation, and we want people to go there first. So please also check whether the existing doco there is ok (is there anything missing that could have helped you solve your problem?), and possibly link to that documentation from the README in Yii contrib dir which Bob mentioned.

> This happens asynchronously. It should not affect the business because data reporting time is too long. There are many clients that use this library with large volume.

It's synchronous and blocking, see https://opentelemetry.io/docs/instrumentation/php/exporters/#minimizing-export-delays
We hope to implement async sending in the future, but first we need to drop 7.4 support. In the meantime, please look at the opentelemetry collector to help you deal with volume.

**Comment by runtu666** [comment]
@brettmc  ok,
cloud you also give me an example of how to record the traceId in each log in this way, and how to set the traceparent? For example, if I want to request other services, how do I bring it there?

**Comment by runtu666** [comment]
https://github.com/opentelemetry-php/example-auto-yii/pull/1
here is the pr for nginx demo, I'll write the document next week

**Comment by brettmc** [comment]
>cloud you also give me an example of how to record the traceId in each log in this way

https://opentelemetry.io/docs/instrumentation/php/manual/#logs is the overview, I hope you've already found and read this. You might also be interested in https://packagist.org/packages/open-telemetry/opentelemetry-logger-monolog

> and how to set the traceparent

https://opentelemetry.io/docs/instrumentation/php/propagation/

**Comment by runtu666** [comment]
yes, We are doing it this way, but we are using Yii's own log instead of monolog. At present, we cannot use yii-auto directly because it will block our application. I look forward to supporting asynchronous data reporting soon.

We now use fastcgi_finish_request() to return results in advance，Maybe we need to consider deploying collector with agents

**Comment by runtu666** [comment]
https://github.com/open-telemetry/opentelemetry-php-contrib/pull/225 
https://github.com/open-telemetry/opentelemetry.io/pull/3712
@bobstrecansky @brettmc
