### ISSUE TITLE
Alpha 0.2 Propagators Requirement - API

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#12]
The  Propagators API needs to created, using [The Propagators API OpenTelemetry Specification](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-propagators.md) as reference.

**Comment by Wizofgoz** [comment]
I've started some work on this, just waiting for #56 to be merged in and I can make a PR.

**Comment by bobstrecansky** [comment]
@Wizofgoz - that PR is merged; you should be good to go.

**Comment by bobstrecansky** [comment]
@Wizofgoz - looks like the propagators API has had some more additions since you completed your work.  Would you like to continue doown this road?  Updated spec:

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-propagators.md

**Comment by bobstrecansky** [comment]
Closing this because we are going to eventually skip more towards a more recent alpha release.
