### ISSUE TITLE
Implement an UpDownSumObserver Instrument for the Metrics API

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#120]
We would like to Implement an UpDownSumObserver Instrument for the Metrics API. The spec for the UpDownSumObserver API is defined at the following URL:

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#sumobserver

**Comment by tanweeralii** [comment]
Hey @bobstrecansky , I would like to work on this issue. Is this still open?

**Comment by bobstrecansky** [comment]
Sure is!  Let us know if you have any questions!

**Comment by tanweeralii** [comment]
Yeah, So far I got that I have to change [api/UpDownCounter.php](https://github.com/open-telemetry/opentelemetry-php/blob/main/api/Metrics/UpDownCounter.php) file. Should I remove `UpDownCounter.php` and create `UpDownSumObserver.php`. Or Just add `UpDownSumObserver.php`.

**Comment by tanweeralii** [comment]
And replace `add()` with `Observer()`

**Comment by bobstrecansky** [comment]
@tanweeralii - [UpDownCounter](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#updowncounter) and [UpDownSumObserver](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#updowncounter) are two separate things.  I think creating a new `UpDownSumObserver.php` would make sense.

**Comment by tanweeralii** [comment]
ok got it

**Comment by alolita** [comment]
@bobstrecansky should this issue be closed given #257 is merged.
