### ISSUE TITLE
Unable to hook into a PHP extension

### ISSUE THREAD

**Issue by gnumoksha** [open-telemetry/opentelemetry-php#1224]
I'm trying to create an instrumentation code for the [phalcon](https://github.com/phalcon/cphalcon) framework, which is a PHP extension, but the hook never works.

```php
hook(
    \Phalcon\Mvc\Application::class,
    'handle',
    function (
        \Phalcon\Mvc\Application $app,
        array        $params,
        string       $class,
        string       $function,
        ?string      $filename,
        ?int         $lineNumber,
    ) {
        // the following will never be executed
        var_dump($app, $params, $class, $function, $filename, $lineNumber);
    }
);
```

**Comment by agoallikmaa** [comment]
Which PHP version are you running this on? Hooking internal functions (such as those provided by an extension) is only supported on PHP 8.2+.

**Comment by gnumoksha** [comment]
> Which PHP version are you running this on? Hooking internal functions (such as those provided by an extension) is only supported on PHP 8.2+.

8.1. I'm working on updating the version.

**Comment by gnumoksha** [comment]
It worked, thank you

**Comment by gnumoksha** [comment]
Is the exception catch expected to work in the post hook, @agoallikmaa?

**Comment by brettmc** [comment]
Pre and post hooks are not expected to throw exceptions - if they do, it will be logged and discarded (as of 1.0.1beta2). If the function _being hooked_ throws an exception, then that exception is available in the post hook.

**Comment by gnumoksha** [comment]
I've tested throwing an exception in a controller, called by the hooked method, and the post hook didn't receive the exception. Instrumenting an PHP code works as expected (i.e. it receives the exception).

**Comment by brettmc** [comment]
That should definitely work: https://github.com/open-telemetry/opentelemetry-php-instrumentation/blob/main/ext/tests/007.phpt (the exception will be the 4th parameter to the post hook).
