### ISSUE TITLE
Export data manually

### ISSUE THREAD

**Issue by bigkase** [open-telemetry/opentelemetry-php#1232]
Hello, there.

Is there a  way in opentelemetry to export traces immediately by calling a function?

In laravel there is a problem when "timeout event" occurred no traces send to jaeger, for after this event code call `exit` function and shutdown the script.
And because of this I think It could  be a great thing if I'd manually could export data to jaeger.

**Comment by ChrisLightfootWild** [comment]
I've not tested this, but you might try calling [forceFlush()](https://github.com/open-telemetry/opentelemetry-php/blob/b20c45df10137927a031de4e27a0228e945c09f3/src/SDK/Trace/TracerProviderInterface.php#L12)

Do you have any more information on why you are facing such timeouts? I am not sure I fully understand what is happening.

**Comment by bigkase** [comment]
@ChrisLightfootWild 
Thank you a lot! Now, it's working. I can see traces in jaeger after "timed out" error.

Of course I have info, I simply emulate this. I sat job timeout and then add call of the `sleep` method in a job's `handle` method with value greater than set timeout.
I wanted to understand what will be going on with traces if I'd got this error.

And laravel inside use signal handler with `pcntl_signal` and `pcntl_alarm` functions to drop any script after certain timeout.
