### ISSUE TITLE
Drupal 7 does not seem to work without writing code

### ISSUE THREAD

**Issue by susanmonnelly** [open-telemetry/opentelemetry-php#1233]
**Describe your environment** 

PHP 8.1.25 (cli) (built: Oct 24 2023 21:51:16) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.1.25, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.25, Copyright (c), by Zend Technologies
    with Xdebug v3.2.2, Copyright (c) 2002-2023, by Derick Rethans

php extension:
module_opentelemetry"
opentelemetry hooks | enabled
extension version | 1.0.1
/etc/php.d/40-opentelemetry.ini

REDIRECT_OTEL_PHP_AUTOLOAD_ENABLED 	true
REDIRECT_OTEL_SERVICE_NAME 	nb_otel_dev
REDIRECT_OTEL_TRACES_EXPORTER 	otlp
REDIRECT_OTEL_EXPORTER_OTLP_PROTOCOL 	http/json
REDIRECT_OTEL_EXPORTER_OTLP_ENDPOINT 	http://10.166.23.70:4318
REDIRECT_OTEL_PROPAGATORS 	baggage,tracecontext 

OTEL_PHP_AUTOLOAD_ENABLED 	true
OTEL_SERVICE_NAME 	nb_otel_dev
OTEL_TRACES_EXPORTER 	otlp
OTEL_EXPORTER_OTLP_PROTOCOL 	http/json
OTEL_EXPORTER_OTLP_ENDPOINT 	http://10.166.23.70:4318
OTEL_PROPAGATORS 	baggage,tracecontext 

Drupal 7.95

Cloud hosting - aws 

packages installed:
   "open-telemetry/sdk": "^1.0@dev",
    "symfony/http-client": "6.4.x-dev",
    "nyholm/psr7": "^1.8@dev",
    "open-telemetry/opentelemetry-auto-http-async": "dev-main",
    "open-telemetry/opentelemetry-instrumentation-installer": "dev-main",
    "open-telemetry/opentelemetry-auto-slim": "dev-main",
    "open-telemetry/exporter-otlp": "^1.0@dev"

config: 
  "config": {
    "allow-plugins": {
      "composer/installers": true,
      "php-http/discovery": true
    }

**Steps to reproduce**
Configured this as described and ran through the application website 

**What is the expected behavior?**

Documentation indicates that Auto-Instrumentation provides hook mechanism, which will trace whatever we would like to verify, without changing single line of code.

**What is the actual behavior?**
I am not able to see this work as described in the documentation

**Additional context**
To prove that the connection to observe is working, I wrote some example code  in the index.php file pulled from some documentation:

/**
 * Root directory of Drupal installation.
 */
define('DRUPAL_ROOT', getcwd());

use OpenTelemetry\API\Logs\EventLogger;
use OpenTelemetry\API\Logs\LogRecord;

require __DIR__ . "/vendor/autoload.php";

$instrumentation = new \OpenTelemetry\API\Instrumentation\CachedInstrumentation('demo');

$instrumentation->tracer()->spanBuilder('root')->startSpan()->end();
$instrumentation->meter()->createCounter('cnt')->add(1);

$eventLogger = new EventLogger($instrumentation->logger(), 'my-domain');
$eventLogger->logEvent('foo', new LogRecord('hello, otel'));

require_once DRUPAL_ROOT . '/includes/bootstrap.inc';
drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);
menu_execute_active_handler();

Adding screen shots to prove it made it through to Observe

![Screenshot 2024-02-12 at 4 15 49 PM](https://github.com/open-telemetry/opentelemetry-php/assets/12297503/1abfb775-777b-484c-aa9c-98a1666bca67)
![Screenshot 2024-02-12 at 4 14 20 PM](https://github.com/open-telemetry/opentelemetry-php/assets/12297503/63e26fd9-839d-4380-8a69-fe25be8807a1)

Please provide instructions on how to make this work.

Thanks

**Comment by agoallikmaa** [comment]
There is currently no auto-instrumentation module that would create spans for incoming requests for Drupal 7. For Drupal 8+, using `opentelemetry-auto-symfony` might work as it started using Symfony internally from version 8. There is also no auto-instrumentation module currently that would create spans without relying on instrumenting a specific framework.

**Comment by susanmonnelly** [comment]
ok thanks for the answer
