### ISSUE TITLE
Add auto instrumentation for CakePHP

### ISSUE THREAD

**Issue by AA2512** [open-telemetry/opentelemetry-php#1234]
# Overview:

The current state of the OpenTelemetry PHP repository lacks dedicated support for auto-instrumentation in CakePHP, a widely used PHP web framework. The absence of native instrumentation for CakePHP hinders the seamless integration of OpenTelemetry for tracing and monitoring purposes.

# Expected Behavior:

Upon integration of OpenTelemetry with a CakePHP application, it is expected that the framework's core functionalities, including request handling, database queries, and other key components, should be automatically instrumented and traced. This will enable developers to gain valuable insights into the performance and behavior of CakePHP applications.

# Additional Context:

CakePHP is a popular PHP framework known for its simplicity, convention over configuration, and rapid development capabilities. As developers increasingly rely on CakePHP for building web applications, the need for robust tracing and observability becomes paramount. Auto-instrumentation will empower developers to identify and resolve performance bottlenecks efficiently.

# Proposal:

Integrate auto-instrumentation for CakePHP core components, covering key areas such as:

1. Request handling
2. Database queries (e.g., SQL queries executed through CakePHP's ORM)

References:

CakePHP Official Documentation: https://book.cakephp.org/4/en/

# Impact:

The proposed enhancement will provide CakePHP developers with detailed traces and metrics related to core framework operations. This will contribute to a more comprehensive understanding of application performance and aid in the efficient identification and resolution of issues.

**Comment by AA2512** [comment]
@brettmc I can take this issue up as I have already started working on the same.

**Comment by ChrisLightfootWild** [comment]
Just to prevent this from being closed automatically by the bot, there is some progress on this via https://github.com/open-telemetry/opentelemetry-php-contrib/pull/253

**Comment by bobstrecansky** [comment]
This should be completed!
