### ISSUE TITLE
Failed to compile: 'save_state.opline' may be used uninitialized

### ISSUE THREAD

**Issue by mlocati** [open-telemetry/opentelemetry-php#1260]
Within a docker container started with:

```
docker run --rm -it php:8.0-cli-alpine3.13 sh
```

I can't compile the opentelemetry PHP extension with PECL: I have this error:

```
 cc -I. -I/tmp/pear/temp/opentelemetry -I/tmp/pear/temp/pear-build-defaultuseraFkENc/opentelemetry-1.0.2beta2/include -I/tmp/pear/temp/pear-build-defaultuseraFkENc/opentelemetry-1.0.2beta2/main -I/tmp/pear/temp/opentelemetry -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -Wall -Wextra -Werror -Wno-unused-parameter -c /tmp/pear/temp/opentelemetry/otel_observer.c  -fPIC -DPIC -o .libs/otel_observer.o
/tmp/pear/temp/opentelemetry/otel_observer.c: In function 'observer_begin':
/tmp/pear/temp/opentelemetry/otel_observer.c:285:30: error: 'save_state.opline' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  285 |         execute_data->opline = save_state->opline;
      |         ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/tmp/pear/temp/opentelemetry/otel_observer.c:470:30: note: 'save_state.opline' was declared here
  470 |         otel_exception_state save_state;
      |                              ^~~~~~~~~~
/tmp/pear/temp/opentelemetry/otel_observer.c: In function 'observer_end':
/tmp/pear/temp/opentelemetry/otel_observer.c:285:30: error: 'save_state.opline' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  285 |         execute_data->opline = save_state->opline;
      |         ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/tmp/pear/temp/opentelemetry/otel_observer.c:644:30: note: 'save_state.opline' was declared here
  644 |         otel_exception_state save_state;
      |                              ^~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:210: otel_observer.lo] Error 1
```

**Steps to reproduce**

```
$ apk add $PHPIZE_DEPS
$ pecl install opentelemetry-beta
```

**Comment by brettmc** [comment]
I was able to replicate this, and tested a few other variants as well.
`8.0.13-cli-alpine3.13` + `beta1`: ok
`8.0.13-cli-alpine3.13` + `beta2`: fail
`8.0.14-cli-alpine3.14` + `beta2`: fail
`8.0.14-cli-alpine3.15` + `beta2`: fail
`8.0.19-cli-alpine3.16` + `beta2`: ok
`8.1.0-cli-alpine3.15` + `beta2`: fail

I think this points to the compiler from alpine 3.13|14|15 not liking that code.

We could also consider expanding our tests to use a wider range of alpine versions. We currently test against our own docker image with debug build (since there isn't an official one). That's convenient for local development, but I don't think it's required to run the github actions.

**Comment by mlocati** [comment]
I've seen this happening on Debian bullseye too (`php:8.1-cli-bullseye`, `php:8.2-cli-bullseye` and `php:8.3-cli-bullseye`) - see https://github.com/mlocati/docker-php-extension-installer/actions/runs/8326192552

**Comment by mlocati** [comment]
I checked the GCC versions of some successful/failed cases:

| OS | GCC | Result |
|---|---|---|
| Debian 10 (buster) | 8.3.0 | ✅ |
| Debian 11 (bullseye) | 10.2.1 | ❌ |
| Debian 12 (bookworm) | 12.2.0 | ✅ |
| Alpine 3.12 | 9.3.0 | ✅ |
| Alpine 3.13 | 10.2.1 | ❌ |
| Alpine 3.14 | 10.3.1 | ❌ |
| Alpine 3.15 | 10.3.1 | ❌ |
| Alpine 3.16 | 11.2.1 | ✅ |

Maybe GCC 10 signals some warnings that other versions don't? And I think that https://github.com/open-telemetry/opentelemetry-php-instrumentation/pull/134 aborts the compilation in case of warnings.

**Comment by mlocati** [comment]
https://github.com/open-telemetry/opentelemetry-php-instrumentation/pull/138 should fix this issue
