### ISSUE TITLE
opentelemetry-auto-laravel  Export failure

### ISSUE THREAD

**Issue by EternalSuno** [open-telemetry/opentelemetry-php#1261]
run in docker,  program start got this error, can't find out reason, endpoint is working
OpenTelemetry: [error] Export failure [exception] Not Found
#0 /www/vendor/open-telemetry/exporter-otlp/SpanExporter.php(41): OpenTelemetry\SDK\Common\Export\Http\PsrTransport->send('{"resourceSpans...', NULL)
#1 /www/vendor/open-telemetry/sdk/Trace/SpanProcessor/BatchSpanProcessor.php(255): OpenTelemetry\Contrib\Otlp\SpanExporter->export(Array)
#2 /www/vendor/open-telemetry/sdk/Trace/SpanProcessor/BatchSpanProcessor.php(198): OpenTelemetry\SDK\Trace\SpanProcessor\BatchSpanProcessor->flush('shutdown', NULL)
#3 /www/vendor/open-telemetry/sdk/Trace/TracerSharedState.php(98): OpenTelemetry\SDK\Trace\SpanProcessor\BatchSpanProcessor->shutdown(NULL)
#4 /www/vendor/open-telemetry/sdk/Trace/TracerProvider.php(92): OpenTelemetry\SDK\Trace\TracerSharedState->shutdown(NULL)
#5 /www/vendor/open-telemetry/sdk/Common/Util/functions.php(36): OpenTelemetry\SDK\Trace\TracerProvider->shutdown()
#6 [internal function]: OpenTelemetry\SDK\Trace\TracerProvider->OpenTelemetry\SDK\Common\Util\{closure}()
#7 /www/vendor/open-telemetry/sdk/Common/Util/functions.php(50): Closure->call(Object(OpenTelemetry\SDK\Trace\TracerProvider))
#8 /www/vendor/open-telemetry/sdk/Common/Util/ShutdownHandler.php(76): OpenTelemetry\SDK\Common\Util\{closure}()
#9 [internal function]: OpenTelemetry\SDK\Common\Util\ShutdownHandler::OpenTelemetry\SDK\Common\Util\{closure}(Array)

**Comment by brettmc** [comment]
> run in docker, program start got this error, can't find out reason, endpoint is working

That looks like it got a 404 error when trying to export your traces. How did you configure the endpoint? By default, it will try to export to `localhost:4318` unless you've provided another value via `OTEL_EXPORTER_OTLP_ENDPOINT` or `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` (assuming you're using SDK autoloading and providing configuration via environment variables)

**Comment by EternalSuno** [comment]
i was set OTEL_EXPORTER_OTLP_ENDPOINT , after set OTEL_EXPORTER_OTLP_TRACES_ENDPOINT  it works !!!!!!!
thx a lot bro!!!!!!

**Comment by brettmc** [comment]
What value did you use for `OTEL_EXPORTER_OTLP_ENDPOINT`? I'm guessing that it had `/v1/traces` appended? Internally, `OTEL_EXPORTER_OTLP_ENDPOINT` has a path or gRPC method appended (depending on the protocol), whereas `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` is not modified. So, the usage is not quite the same for each!
