### ISSUE TITLE
Add host.id for non-containerized systems

### ISSUE THREAD

**Issue by matt-hensley** [open-telemetry/opentelemetry-php#1263]
**Is your feature request related to a problem?**
`host.id` is only populated for containers, via the [Container Detector](https://github.com/open-telemetry/opentelemetry-php-contrib/tree/main/src/ResourceDetectors/Container).

`host.id` is a recommended attribute, and should be populated for non-containerized systems.

**Describe the solution you'd like**
A new resource detector to populate `host.id` on non-containerized systems.

[The specification has a list of required sources](https://opentelemetry.io/docs/specs/semconv/resource/host/#collecting-hostid-from-non-containerized-systems) if `host.id` is collected outside containers.

**Describe alternatives you've considered**
`host.id` injection via the `OTEL_RESOURCE_ATTRIBUTES` environment variable. This would require OS-specific configuration changes across applications.

**Additional context**
I'm available to implement this feature.

**Comment by brettmc** [comment]
It looks like our `Host` detector would be the right place for this to be added, and should only set it if available.

**Comment by brettmc** [comment]
Depending on the overhead of trying to detect host ID where it's not available (ie, in a container), we may want to consider having this in its own detector so that users can opt out.
I'm also not sure whether a server counts as a "generic platform" per spec: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.31.0/specification/resource/sdk.md#detecting-resource-information-from-the-environment (ie, should it live in contrib or core?)

**Comment by matt-hensley** [comment]
IMO the overhead is pretty low for typical cases, namely a VM running Linux. There are two files are to check whether they contain an ID.

For other platforms it's either checking files and/or shelling out and running a process to get the ID. Those cases are definitely slower, though probably not too bad being a single check at startup.

The cloud resource detectors are much slower since they rely on HTTP calls to metadata APIs.

It looks like the spec is ambiguous on whether the bare metal host detector should be a separate package, will defer to the SIG on that one.
