### ISSUE TITLE
[opentelemetry-php-instrumentation] Segmentation Fault on BadMethodCallException

### ISSUE THREAD

**Issue by iamacarpet** [open-telemetry/opentelemetry-php#1279]
**Describe your environment** 

PHP 8.3.0
OpenTelemetry extension 1.0.0

**Steps to reproduce**

While tracing Laravel 11.x, with this hook:

```php
        hook(
            Route::class,
            'run',
            pre: function (Route $route, array $params, string $class, string $function, ?string $filename, ?int $lineno): void {
                $attributes = [];

                $class = $route->getControllerClass();
                if (!empty($class)) {
                    $attributes['callable']  = $class.'::'.$route->getControllerMethod();
                } else {
                    $attributes['callable'] = 'Closure';
                }

                SimpleSpan::pre(
                    $this->instrumentation,
                    'laravel/controller',
                    $attributes,
                );
            },
            post: static function (Route $route, array $params, mixed $response, ?\Throwable $exception): void {
                SimpleSpan::post();
            },
        );
```

I was getting `php-fpm` SIGSEGV messages.

Putting a try/catch around the middle bit:

```php
        try {
                $class = $route->getControllerClass();
                if (!empty($class)) {
                    $attributes['callable']  = $class.'::'.$route->getControllerMethod();
                } else {
                    $attributes['callable'] = 'Closure';
                }
        } catch (\Throwable $ex) {
            report($ex);
        }
```

eventually threw:

`BadMethodCallException: Method Illuminate\Routing\Route::getControllerMethod does not exist.`

Which was fixed by swapping to:

```php
                try {
                    $class = $route->getControllerClass();
                    if (!empty($class)) {
                        $callback                = Str::parseCallback($route->action['uses']);
                        $attributes['callable']  = $class.'::'.$callback[1];
                    } else {
                        $attributes['callable'] = 'Closure';
                    }
                } catch (\Throwable $ex) {
                    report($ex);
                }
```

I've tried to create a smaller reproducible sample without Laravel and I can't get it to segfault, however, doing it with Laravel in that scenario makes it reliably segfault when the route is configured in such a way that it gets a value back from `$route->getControllerClass()`.

There is some part of the problem missing that I think involves `Macroable`, along with accessing a method that is actually protected/private as if it was public (`getControllerMethod()` does actually exist, it just isn't public), but I wanted to report this in the meantime in case anyone else spots a similar problem.

**What is the expected behavior?**

Exception thrown gracefully.

**What is the actual behavior?**

Segmentation Fault - SIGSEGV

**Additional context**

This was running in an environment I can't easily capture a core dump to explore the segfault.

**Comment by brettmc** [comment]
I think this was fixed by https://github.com/open-telemetry/opentelemetry-php-instrumentation/pull/118 which is in extension version 1.0.1 (and we're up to 1.0.2 now)

**Comment by iamacarpet** [comment]
Thanks @brettmc ,

I appreciate you confirming that.

I don’t directly have control of the extension version we are using, as it’s on Google’s App Engine runtime: I’ll forward them this thread including your comment and ask for an upgrade.

On that note, is there a particular release cadence for the extension, where they should check for updates, or is it just as and when you have something?

**Comment by brettmc** [comment]
> is there a particular release cadence for the extension

No, just "as required".
