### ISSUE TITLE
[opentelemetry-php-contrib] Disable Messenger and HttpClient auto-intrumentation only

### ISSUE THREAD

**Issue by iosifch** [open-telemetry/opentelemetry-php#1284]
Hi! Is there any way to deactivate Messenger and HttpClient auto-instrumentation and still keeping the rest of auto-instrumentation offered by `open-telemetry/opentelemetry-auto-symfony`? I know I can disable the whole extension by `OTEL_PHP_DISABLED_INSTRUMENTATIONS=symfony`.

**Comment by brettmc** [comment]
Hi @iosifch no, there is not yet a way to do that. We've discussed it previously, and there's [an issue](https://github.com/open-telemetry/opentelemetry-specification/issues/3205) over in the spec talking about it too.

**Comment by iosifch** [comment]
I see. Thank you, @brettmc !
