### ISSUE TITLE
Emit schema_url during exports

### ISSUE THREAD

**Issue by sudol** [open-telemetry/opentelemetry-php#1290]
Can we emit the schema_url for spans/metrics/logs?

I'm using the slim auto instrumentation and schema_url is not included in the export.

I'm happy to help make this change if it's in line with the vision here. Can someone suggest where best to make this change?

**Comment by brettmc** [comment]
For auto-instrumentation, the place to set this would be instances of `new CachedInstrumentation()` - the guzzle package sets it based on `TraceAttributes::SCHEMA_URL`. I can't think of a reason not to apply it to all auto-instrumentations.

**Comment by sudol** [comment]
I made a PR with the change that I had in mind. Can you let me know if this is in line with the vision for the project and the specifications? https://github.com/open-telemetry/opentelemetry-php/pull/1292/files
