### ISSUE TITLE
Why does just php sdk have the concept of scope for span?

### ISSUE THREAD

**Issue by changzee** [open-telemetry/opentelemetry-php#1295]
I checked the official documentation and found that unlike other languages ​​​​(go, python), PHP SDK has two more APIs for scope activation and deativation, which is an unnecessary burden for users.
Is it a bad idea?

**Comment by brettmc** [comment]
I think it's this part:

https://github.com/open-telemetry/opentelemetry-specification/tree/v1.32.0/specification/context#attach-context

> The API MUST return a value that can be used as a Token to restore the previous Context

**Comment by changzee** [comment]
thanks for ur answer
