### ISSUE TITLE
Feature - OpenTelemetry Exporter

### ISSUE THREAD

**Issue by atrauzzi** [open-telemetry/opentelemetry-php#130]
It probably goes without saying that every OpenTelemetry library should should ship an OpenTelemetry exporter. :smile: 

The benefit to the PHP library in this would be that at some point, pure OpenTelemetry configurations are going to be possible, and desirable. Having an "ecosystem-native" exporter ensures that the PHP library doesn't contribute any delay towards widespread adoption.
It also helps simplify setup for newcomers by not forcing them into ecosystems and terminology outside of OpenTelemetry.

**Comment by bobstrecansky** [comment]
@atrauzzi - are you planning on working on this effort?

**Comment by atrauzzi** [comment]
I'm not sure I'd be the best person for it as I'm not intimately familiar with what's involved.

**Comment by bobstrecansky** [comment]
@atrauzzi - were you referring to [this](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/protocol/README.md) or were you referring to something else?

**Comment by atrauzzi** [comment]
Something like this: https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/README.md

**Comment by bobstrecansky** [comment]
I think it may be worth it to wait until the spec is hashed out to implement this.  Thoughts?

**Comment by atrauzzi** [comment]
Definitely logic to that. Also gives this library a chance to settle on its API.

**Comment by bobstrecansky** [comment]
The OTEP maintainers are discussing this now: https://github.com/open-telemetry/opentelemetry-specification/pull/699

**Comment by codeboten** [comment]
The OTLP exporter is now part of the spec: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/protocol/exporter.md

**Comment by bobstrecansky** [comment]
The specification for OTLP is found [here](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/protocol/otlp.md)

The specification for the exporter is found [here](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/protocol/exporter.md)

**Comment by bobstrecansky** [comment]
OTLP Trace Data format: https://github.com/open-telemetry/oteps/blob/master/text/trace/0059-otlp-trace-data-format.md

**Comment by bobstrecansky** [comment]
The HTTP version of this has been completed in https://github.com/open-telemetry/opentelemetry-php/pull/210

@riticksingh is now working on the gRPC implementation.

**Comment by bobstrecansky** [comment]
This has been completed by @SeanHood in https://github.com/open-telemetry/opentelemetry-php/pull/272
