### ISSUE TITLE
OpenTelemetry Specification 1.34.0 Release - Compatibility - Prometheus: Clarify location of unit suffix within metric names

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#1330]
Clarify location of unit suffix within metric names

We need to follow the following specification change:
Prometheus: Clarify location of unit suffix within metric names.
https://github.com/open-telemetry/opentelemetry-specification/pull/4057

**Comment by brettmc** [comment]
We don't have prometheus or openmetrics exporting (except indirectly via OTLP), so I think this can be closed.
