### ISSUE TITLE
OpenTelemetry Specification 1.34.0 Release - Common - Rename "Experimental" to "Development" according to OTEP 0232

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#1332]
Rename "Experimental" to "Development" according to OTEP 0232.
We need to follow the following specification change:
Rename "Experimental" to "Development" according to OTEP 0232.
https://github.com/open-telemetry/opentelemetry-specification/pull/4061
https://github.com/open-telemetry/opentelemetry-specification/pull/4069

**Comment by brettmc** [comment]
We have a few `@experimental` tags in our codebase (in the metrics signal) which we could consider changing to `@development`. Personally, I don't think it's obvious what `@development` means as a phpdoc tag, so maybe we just do nothing here? To discuss at SIG...

**Comment by bobstrecansky** [comment]
We decided that `@experimental` is easier to reason about from a PHP context, so we will take no action here.
