### ISSUE TITLE
OpenTelemetry Specification 1.34.0 Release - Supplementary Guidelines - Clarify that it is permissible to extend SDK interfaces without requiring a major version bump

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#1333]
Clarify that it is permissible to extend SDK interfaces without requiring a major version bump

We need to follow the following specification change:
Clarify that it is permissible to extend SDK interfaces without requiring a major version bump
https://github.com/open-telemetry/opentelemetry-specification/pull/4030

**Comment by brettmc** [comment]
No changes required from this, closing.
