### ISSUE TITLE
Can I use sqlcommenter with laravel ?

### ISSUE THREAD

**Issue by moeyashi** [open-telemetry/opentelemetry-php#1345]
I'm new to OpenTelemetry.

I'm using https://github.com/google/sqlcommenter/tree/master/php/sqlcommenter-php/packages/sqlcommenter-laravel .

However, this repository is not maintained.

I am having trouble because the alternative repo https://github.com/open-telemetry/opentelemetry-sqlcommenter does not have code that corresponds to Laravel.

I wondered if the sqlcommenter functionality was already available in the contrib repository and I just didn’t know about it, so I created an issue here.

**Comment by brettmc** [comment]
Hi @moeyashi 
No, we don't have an instrumentation package for sqlcommenter.

The closest thing we do have is auto-instrumentation for PDO, and auto-instrumentation for pure Laravel (which supports creating spans for database queries, but not the sql commenter aspect).

**Comment by moeyashi** [comment]
Thank you @brettmc .
I made new issue as a feature request.
