### ISSUE TITLE
Missing return types annotations with #[ReturnTypeWillChange]

### ISSUE THREAD

**Issue by dkarlovi** [open-telemetry/opentelemetry-php#1348]
**Steps to reproduce**

See https://github.com/symfony/symfony/issues/57624

**What is the expected behavior?**

No deprecations.

**What is the actual behavior?**

Deprecations.

**Additional context**

Symfony sees the bug reported there as expected behavior, meaning OTEL is in the wrong. It does make sense to add `@return` annotations where they're missing, that makes static analysis happier too.

I'm guessing `#[ReturnTypeWillChange]` was added to signal this missing information, but, as noted in the issue, it only signals the return type will change, it doesn't signal what it will change to.

**Comment by bobstrecansky** [comment]
Thanks for the issue report @dkarlovi - are you planning on working through this issue or are you hoping for assistance from the community?
