### ISSUE TITLE
Add `#[WithSpan]` attribute support for PHP methods

### ISSUE THREAD

**Issue by tom-diacono** [open-telemetry/opentelemetry-php#1355]
## Background
Currently, to instrument a method manually in PHP- we have to manually start and end a span. This is fine in small methods- however in large methods with many returns or potential exceptions being thrown; it can be difficult to ensure that we end the span(s) in all the places where the method may return or throw. This can lead to an 'unclosed span exception' (OWTTE), and creates quite a lot of cognitive load.

Having worked with the Java implementation of OpenTelemetry, one of the features I really enjoyed was the [`@WithSpan` annotation](https://opentelemetry.io/docs/zero-code/java/agent/annotations/)- which allows us to really quickly setup spans for the lifecycle of a method; without having to think about where to close it.

## Proposed Solution
It would be great to have a similar method in PHP, that's run via PHP attributes. Ideally, when a method is annotated awith `#[WithSpan]`, it would generate a trace for the method. Exception recording would also be great, (IE adding `->recordException();`).

Ideally, this span would become active, so that we could _get it_ from the tracer in the PHP code, and add attributes and events to it.

One more potential idea is adding another attribute called `#[SpanAttribute]`- which could be assigned to method parameters. Again- similar to the Java implementation. Personally this would be a nice to have more than a requirement, as it's not solving the core problem that I outlined in the background section. Interested to see what the community think on that one however!

After a [brief discussion](https://cloud-native.slack.com/archives/C01NFPCV44V/p1722336367749329) on the Slack channel, I think the general consensus is that this would be better implemented in extension, over implementing in PHP code (unfortunately that slightly rules me out for contributing).

## Alternatives
In the Slack conversation, there was discussion of the approach of having a [callback wrapper](https://cloud-native.slack.com/archives/C01NFPCV44V/p1722441272005779?thread_ts=1722336367.749329&cid=C01NFPCV44V). Effectively, the 'calling class' wraps a method call with an instrumentation. This looks great- and maybe there's an argument that something like this is added in also. Having said which, I think the problem is that when you're in the context of the method that's had a span created for it- you never know if your 'calling class' created a span, so adding attributes etc could be difficult.

**Comment by brettmc** [comment]
comment from slack thread:

> The most efficient way to implement attribute based hooks should be within `observer_fcall_init`(/`resolve_observer`) of the opentelemetry extension (fwiw early prototypes of the extension were using a very basic attribute-based approach instead of the current registration via `hook()`+lookup-based approach).
The extension could provide generic `PreHook`/`PostHook` interfaces that match the `hook()` callbacks; `resolve_observer` could then check whether the `execute_data` function has attributes implementing these interfaces and add them to the `pre_hooks`/`post_hooks` lists.
