### ISSUE TITLE
Introduce support for `google/protobuf` `^4.x`

### ISSUE THREAD

**Issue by ldebrouwer** [open-telemetry/opentelemetry-php#1359]
Due to the current version constraints it's not possible for us to upgrade to `google/protobuf` `^4.x`, it be good to open up this upgrade path as not supporting it might lock people into older versions of other dependencies.

**Comment by brettmc** [comment]
Thanks @ldebrouwer - have you tested it out yet with protobuf v4? If so, does it work with/without any code changes, and if code changes required will it be backwards compatible with v3?
