### ISSUE TITLE
Implement AddLazyEvent

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#138]
We need to implement AddLazyEvent [here](https://github.com/open-telemetry/opentelemetry-php/blob/master/api/Trace/Span.php#L68)

More implementation details about LazyEvents in the API can be found in the specification [here](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#add-events)

Success Criteria : Implement lazy events as prescribed by the specification.

**Comment by codeboten** [comment]
This issue can probably be closed as per the spec change to remove lazy events from the API https://github.com/open-telemetry/opentelemetry-specification/pull/840

**Comment by bobstrecansky** [comment]
Thanks @codeboten ! Closing.
