### ISSUE TITLE
Implement Attributes and Links in the Samplers

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#139]
We have a TODO in the Trace Samplers to hook up attributes and links to our samplers.

https://github.com/open-telemetry/opentelemetry-php/blob/master/sdk/Trace/Sampler/AlwaysOnSampler.php#L34
https://github.com/open-telemetry/opentelemetry-php/blob/master/sdk/Trace/Sampler/ProbabilitySampler.php#L48
https://github.com/open-telemetry/opentelemetry-php/blob/master/sdk/Trace/Sampler/AlwaysParentSampler.php#L34

Success Criteria : Hook up attributes and links into our samplers.

**Comment by wRLSS** [comment]
I would suggest to migrate `SpanKind` to a better ValueObject solution using 
https://github.com/myclabs/php-enum

**Comment by artem-prozorov** [comment]
I'm not sure I understood the issue correctly, but anyway here is my PR :)
