### ISSUE TITLE
[opentelemetry-php-contrib] [contrib-aws] Warning indicating something went wrong when calling s3client->getObjectUrl()

### ISSUE THREAD

**Issue by gwharton** [open-telemetry/opentelemetry-php#1390]
**Describe your environment** 
Ubuntu 24.04
Php 8.3.11 with opentelemetry module version 1.0.3
open-telemetry/contrib-aws 1.0.0beta11

When instrumenting S3 client, calls to s3client->getObjectUrl fail with the error

`Warning: Trying to access array offset on null in /home/ubuntu/test/vendor/open-telemetry/contrib-aws/src/AwsSdkInstrumentation.php on line 113`

**Steps to reproduce**
composer.json
```
{
    "require": {
        "open-telemetry/contrib-aws": "1.0.0beta11",
        "google/protobuf": "*",
        "ext-opentelemetry": "*",
        "aws/aws-sdk-php": "*",
	"open-telemetry/exporter-otlp": "*",
	"open-telemetry/api": "*",
        "php-http/guzzle7-adapter": "*"
    },
    "minimum-stability": "dev",
    "prefer-stable" : true,
    "config": {
        "allow-plugins": {
            "php-http/discovery": true
        }
    }
}
```
test.php
```
<?php
# Run using
# OTEL_PHP_AUTOLOAD_ENABLED=true OTEL_SERVICE_NAME=test OTEL_TRACES_EXPORTER=otlp OTEL_METRICS_EXPORTER=none OTEL_LOGS_EXPORTER=none php test.php

require __DIR__ . '/vendor/autoload.php';

use OpenTelemetry\API\Globals;
use Aws\S3\S3Client;
use OpenTelemetry\API\Trace\SpanKind;
use OpenTelemetry\Aws\AwsSdkInstrumentation;
use OpenTelemetry\Aws\Xray\Propagator;

$awssdkinstrumentation = new AwsSdkInstrumentation();
$awssdkinstrumentation->setPropagator(new Propagator());
$awssdkinstrumentation->setTracerProvider(Globals::tracerProvider());

$root = $awssdkinstrumentation->getTracer()->spanBuilder('AwsSDKInstrumentation')->setSpanKind(SpanKind::KIND_SERVER)->startSpan();
$rootScope = $root->activate();

$s3Client = new S3Client([
    'region' => 'eu-west-2',
]);

$awssdkinstrumentation->instrumentClients([$s3Client]);
$awssdkinstrumentation->activate();

$result = $s3Client->getObjectUrl('testbucket','./');

$root->end();
$rootScope->detach();
```

**What is the expected behavior?**
No warnings

**What is the actual behavior?**
`Warning: Trying to access array offset on null in /home/ubuntu/test/vendor/open-telemetry/contrib-aws/src/AwsSdkInstrumentation.php on line 113`
The span is not sent to otlp endpoint.

**Additional context**
Tracing the issue with xdebug, it looks like the call to getObjectUrl results in a Middleware::mapResult callback with an empty Aws/Result object. Is the callback being called before the async Guzzle request has fulfilled?

![image](https://github.com/user-attachments/assets/c1a4a427-87bb-4d6d-93f5-a6f34a8291c5)

**Comment by gwharton** [comment]
Currently working around this with the following hack
```
--- vendor/open-telemetry/contrib-aws/src/AwsSdkInstrumentation.original.php	2024-09-26 11:46:57.957094400 +0100
+++ vendor/open-telemetry/contrib-aws/src/AwsSdkInstrumentation.php	2024-09-26 11:51:53.974424003 +0100
@@ -109,9 +109,11 @@
 
             /** @psalm-suppress PossiblyInvalidArgument */
             $end_middleware = Middleware::mapResult(function (ResultInterface $result) {
-                $this->span->setAttributes([
-                    'http.status_code' => $result['@metadata']['statusCode'], //@phan-suppress-current-line PhanTypeMismatchDimFetch
-                ]);
+                if (isset($result['@metadata'])) {
+                    $this->span->setAttributes([
+                        'http.status_code' => $result['@metadata']['statusCode'], //@phan-suppress-current-line PhanTypeMismatchDimFetch
+                    ]);
+                }
 
                 $this->span->end();
                 $this->scope->detach();
```

**Comment by brettmc** [comment]
Hi @gwharton I don't have any experience with AWS SDKs - is a result without the `@metadata` option an expected/possible response here? I don't have an issue with applying your suggested change either way, just wanting to check whether there's an upstream issue to be investigated?

**Comment by brettmc** [comment]
Thanks for doing that investigation, @gwharton 
I'm happy with your proposed change - do you want to create a PR?
