### ISSUE TITLE
Only spans with SampleFlag == True should be exported

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#140]
We need to only export spans that have a `SampleFlag == True`.  This is located at the following [todo](https://github.com/open-telemetry/opentelemetry-php/blob/master/sdk/Trace/SpanProcessor/SimpleSpanProcessor.php#L41).

Success criteria: implement this flagging logic

**Comment by wRLSS** [comment]
this can be closed btw

**Comment by bobstrecansky** [comment]
Thanks @wRLSS !
