### ISSUE TITLE
Finish the isRemote function

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#141]
Currently the `isRemote` function just returns false:
https://github.com/open-telemetry/opentelemetry-php/blob/master/sdk/Trace/Span.php#L183-L191

More details about `isRemote` can be found in the SpanContext section of the spec:
[SpanContext](https://github.com/open-telemetry/opentelemetry-specification/blob/4daee3af756be75edbd17085f6d382d963027bc8/specification/trace/api.md#spancontext)

Success criteria:
Implement `isRemote` functionality

**Comment by bobstrecansky** [comment]
@michaelorr is working on this.

**Comment by bobstrecansky** [comment]
This function has a signature but still needs to be completed:
https://github.com/open-telemetry/opentelemetry-php/blob/3a83788a4026e55c9eea88d0625c9193f0ad9113/sdk/Trace/Span.php#L202

**Comment by zsistla** [comment]
I'll work on this.

**Comment by bobstrecansky** [comment]
Thanks Amber! Updated the ticket accordingly.

**Comment by zsistla** [comment]
[PR](https://github.com/open-telemetry/opentelemetry-php/pull/194/) is up and current status is `pending review`.
