### ISSUE TITLE
Implement the setSpanKind Method

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#142]
The [specification for SpanKind](
https://github.com/open-telemetry/opentelemetry-specification/blob/4daee3af756be75edbd17085f6d382d963027bc8/specification/trace/api.md#spankind) has been firmed up, so we should implement the setSpanKind method.

Success criteria:  Implement the SpanKind method as defined [here](https://github.com/open-telemetry/opentelemetry-php/blob/master/sdk/Trace/SpanOptions.php#L36-L39).

**Comment by wRLSS** [comment]
I would suggest to migrate `SpanKind` to a better Enum solution
https://github.com/myclabs/php-enum

**Comment by bobstrecansky** [comment]
@wRLSS - Would you like to create a PR to show this?

**Comment by artem-prozorov** [comment]
@bobstrecansky I would gladly contribute and start with this issue. Would you grant me access to make a PR?

**Comment by bobstrecansky** [comment]
@artem-prozorov - you should be able to access this and make a PR in the current state! If you can't make a PR for some reason, please let me know and I'll work with you to ensure you have the ability to!
