### ISSUE TITLE
"OTEL_PHP_AUTOLOAD_ENABLED=true" not working in php.ini

### ISSUE THREAD

**Issue by Willhang23** [open-telemetry/opentelemetry-php#1431]
"true" in php.ini are evaluated to "1" by get_cfg_var() (OpenTelemetry\SDK\Common\Configuration\Resolver\PhpIniAccessor) while the OpenTelemetry\SDK\Common\Configuration\Parser\BooleanParser only accepts "true" as true value.

**Comment by brettmc** [comment]
Discussed a little in the linked PR... are you sure you're correctly quoting "true" in php.ini? The opentelemetry spec says we have to use "true" and not other things that could also mean true, and in my testing double-quoting resolves this. We might need a documentation patch to clarify this, though.

**Comment by brettmc** [comment]
Related to #1442 and fixed by https://github.com/open-telemetry/opentelemetry.io/pull/5849 - that is, the required format for php.ini would be `OTEL_PHP_AUTOLOAD_ENABLED="true"`, noting that the value is double-quoted
