### ISSUE TITLE
PHP Zero Code Implementation for YII Framework - Single Trace Depth Only

### ISSUE THREAD

**Issue by mxw-sec** [open-telemetry/opentelemetry-php#1432]
**Describe your environment** 
Running a multi-tiered Yii2 PHP Application with multiple self registered API's. 

**Steps to reproduce**
Build a Multi-tiered PHP8.2 Application using Yii2 with OpenAPI support

**What is the expected behavior?**
Multi-tiered Spans and Traces similar to the way it works with other frameworks

**What is the actual behavior?**
All calls are single stack, their is no Traceparent or Tracestate on any of the calls. 
**Additional context**

**Comment by bobstrecansky** [comment]
@mxw-sec - I don't believe this is a bug - we'd have to add auto-instrumentation for the Yii2 framework.  Pull requests for this are welcome, you can see examples of auto-instrumentation for the YII framework [here](https://github.com/open-telemetry/opentelemetry-php-contrib/tree/main/src/Instrumentation/Yii/src)

**Comment by mxw-sec** [comment]
I thought the otel-auto-yii did cover the framework.

**Comment by brettmc** [comment]
> I thought the otel-auto-yii did cover the framework.

The initial implementation for yii is pretty basic. You'll get one span per request (`Application::handleRequest`), and if your app also uses yii's controllers, you'll get a child span for that: https://github.com/open-telemetry/opentelemetry-php-contrib/blob/main/src/Instrumentation/Yii/src/YiiInstrumentation.php#L125
If the application is part of a distributed system (ie, incoming requests contain the `traceparent` header), then you'll also get remote context propagation.

> their is no Traceparent or Tracestate on any of the calls

Which calls are you expecting traceparent to be attached to? Does your app make outbound HTTP requests? If it does, then you might look at also installing instrumentation for your HTTP client. This auto-instrumentation doesn't do that.

**Comment by mxw-sec** [comment]
Okay that Makes more sense.. We are used to the information that Datadog provided and when we saw Zero Code from OTEL, just kind of expected the same level of coverage.   Thanks for the clarification.
