### ISSUE TITLE
[Question] [PHP-FTM] Peformance 

### ISSUE THREAD

**Issue by yahorsi** [open-telemetry/opentelemetry-php#1445]
Hi guys, Im new to the PHP, sorry if question is dumb :)

As far as I understand PHP-FTM model, every request gets executed in the process of the PHP workers, also, every request gets "fresh" state of the process, in this case:
1. Am I right PHP will have to open new HTTP connection to the OTEL Collector?
2. Am I right there is no caching of the traces/metrics/logs possible on the PHP side?
3. What happens if pushing metrics/traces/logs takes long for some reason, could it cause perf issues because worker process won't return to the pool fast?

Thanks, regards!

**Comment by brettmc** [comment]
Hi @yahorsi 
1. yes
2. yes
3. yes it can cause perf issues. we recommend having an opentelemetry collector located near to your application, per https://opentelemetry.io/docs/languages/php/exporters/#minimizing-export-delays

You could also look at https://www.php.net/manual/en/function.fastcgi-finish-request.php however that doesn't return workers to the pool faster, it just returns user responses faster.
