### ISSUE TITLE
Sampled flag should be exported to child span during fork operation

### ISSUE THREAD

**Issue by mattiabasone** [open-telemetry/opentelemetry-php#151]
**Steps to reproduce**
Create a Tracer (manually, since you cannot create a Tracer from TracerProvider with isSampled flag) with a SpanContext having isSampled = true.
When you try to add additional sub-spans, they will not be exported.

**What is the expected behavior?**
Child span, forked from sampled parent, should be sampled too

**What is the actual behavior?**
Child span will not be exported

**Additional context**
Maybe during `SpanContext::fork($parent->getTraceId());` we should inherit $parent->isSampled() status

**Comment by artem-prozorov** [comment]
Yes, I mentioned this in https://github.com/open-telemetry/opentelemetry-php/issues/148

**Comment by mattiabasone** [comment]
> Yes, I mentioned this in #148 (inability to pass isSampled from tracer)

Temporarily I'm using [this](https://github.com/mattiabasone/opentelemetry-php/commit/7e6591f5946516b5e4b6db4a8e49ad41392c31bd) solution and starting a Tracer manually (not using auto generated Tracer by TracerProvider)
