### ISSUE TITLE
Should we do a 0.x version release?

### ISSUE THREAD

**Issue by adhocore** [open-telemetry/opentelemetry-php#166]
It may be too early for v1.x release but till then should we just tag some releases in 0.x or 0.0.x versions?

Maybe, then we may not need `"minimum-stability": "dev"`

**Comment by bobstrecansky** [comment]
@adhocore - we are currently one ticket away from an alpha viable 0.2 release - 
https://github.com/open-telemetry/opentelemetry-php/issues/162

We will most likely create our first release after that PR has been completed and merged.

**Comment by adhocore** [comment]
PHP8 rc is around the corner - would be nice if we can do rc as we wait for #162 👍

**Comment by bobstrecansky** [comment]
In the channel we decided that we are going to do a 0.0.1 release to garner feedback from the community.  I'll do that tomorrow if there isn't any negative response from the community.

**Comment by bobstrecansky** [comment]
We have performed a 0.0.1 release that is still pre-alpha software to get feedback.
