### ISSUE TITLE
Naming Updates

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#174]
To follow the spec, we should apply naming updates that were added to the specification:

Spec updates to apply for each language:
HTTPText propagator renamed to TextMap propagator (https://github.com/open-telemetry/opentelemetry-specification/pull/793)
ProbabilitySampler renamed to TraceIdRatioBased (https://github.com/open-telemetry/opentelemetry-specification/pull/611)
ParentOrElse renamed to ParentBased (https://github.com/open-telemetry/opentelemetry-specification/pull/610)
OTLP exporter unified configuration for Tracing/Metrics (https://github.com/open-telemetry/opentelemetry-specification/pull/820)
Add Translation of InstrumentationLibraryInfo to Jaeger/Zipkin

Success criteria - renaming these parts of the codebase where applicable

**Comment by prondubuisi** [comment]
Hello @bobstrecansky I did not see any instances of  ParentOrElse in the codebase, any pointers on this? so I can send in a PR for ParentOrElse renamed to ParentBased (open-telemetry/opentelemetry-specification#610)

**Comment by beniamin** [comment]
@prondubuisi what you are looking for is AlwaysParentSampler which was renamed in the specifications to ParentOrElse in this commit: https://github.com/open-telemetry/opentelemetry-specification/commit/f9aabe2cb1cd6b329cf61375447d97a87113a84f#diff-c078fe79eabe5405ec976253a76d9de0

**Comment by prondubuisi** [comment]
Super thanks @beniamin I appreciate your help

**Comment by prondubuisi** [comment]
> open-telemetry/opentelemetry-specification#609

Looks like the latest Spec for this is renaming ParentOrElse  to ParentBased, I will update my PR to reflect this

**Comment by prondubuisi** [comment]
> @prondubuisi what you are looking for is AlwaysParentSampler which was renamed in the specifications to ParentOrElse in the PR: [open-telemetry/opentelemetry-specification#609](https://github.com/open-telemetry/opentelemetry-specification/pull/609)

Looks like the latest Spec for this is renaming ParentOrElse to ParentBased, I will update my PR to reflect this

**Comment by prondubuisi** [comment]
OTLP exporter unified configuration for Tracing/Metrics (open-telemetry/opentelemetry-specification#820)
Hello @beniamin @bobstrecansky I need help with understanding how to implement this specs on the codebase

**Comment by prondubuisi** [comment]
Hello@bobstrecansky are we skipping some of the tasks for this issue? as tasks From point 4 are still undone

**Comment by bobstrecansky** [comment]
@prondubuisi - I was assuming you were still looking into them.  I closed this inadvertently; my apologies.  Reopening.

**Comment by bobstrecansky** [comment]
The OTLP exporter has not yet been written.  I am planning on actively looking into that this week.  That can be tracked with this ticket:
https://github.com/open-telemetry/opentelemetry-php/issues/130

**Comment by prondubuisi** [comment]
> @prondubuisi - I was assuming you were still looking into them. I closed this inadvertently; my apologies. Reopening.

No problems @bobstrecansky I was just curious, maybe my PR's Magically solved every task mentioned. Thanks for reopening.

**Comment by bobstrecansky** [comment]
@prondubuisi - looks like this is almost finished; did you have any other changes to make?

**Comment by prondubuisi** [comment]
No @bobstrecansky. I think we are done. Thanks

**Comment by bobstrecansky** [comment]
Thank you @prondubuisi !
