### ISSUE TITLE
PHP Exporter Development

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-php#175]
This issue is features as a [Community Bridge](https://github.com/cncf/mentoring/blob/master/communitybridge/2020/q3-q4/project_ideas.md#opentelemetry-to-fluentbit-exporter) project for Q3-Q4 2020.

Develop some of the exporters for PHP that are found in the ([Spec Compliance Matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/master/spec-compliance-matrix.md#exporters)) that are not yet completed for PHP.  There are some really neat exporter implementations that would be excellent candidates:

- Zipkin
- Jaeger
- Prometheus
- OTLP

**Comment by riticksingh** [comment]
Sir , I am interested in this very project .

**Comment by SergeyKanzhelev** [comment]
@riticksingh welcome and thanks for the interest! If you want to contribute as a part of a Community Bridge, please register on Community Bridge site. There is a limited set of spots every quarter and there is an interview process to fill the spot.

**Comment by prondubuisi** [comment]
Hello @SergeyKanzhelev @bobstrecansky I have registered for this project on the community bridge website. Thanks
