### ISSUE TITLE
Update Zoom link in readme

### ISSUE THREAD

**Issue by prondubuisi** [open-telemetry/opentelemetry-php#176]
**Describe the solution you'd like**
 Tried Joining the call with the link from the calendar on the readme, looks like the link has moved to https://zoom.us/j/8287234601

**Comment by xukaren** [comment]
I'll get to work on this! 
cc: @alolita

**Comment by xukaren** [comment]
Fixed 
(cc: @alolita)

**Comment by prondubuisi** [comment]
I should be closing this now. Thanks @xukaren
