### ISSUE TITLE
Ensure the TraceContext conforms to the W3C TraceContext spec

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#181]
We should ensure that our TraceContext implementation follows the [w3c trace context specification](https://github.com/w3c/trace-context)

@Fahmy-Mohammed mentioned that he wanted to start working through this I believe.

**Comment by Fahmy-Mohammed** [comment]
Yes, I've started on this

**Comment by Fahmy-Mohammed** [comment]
The bulk of this work is completed in #213, #233, #251. This will be considered finished once #217 is completed any failing tests are fixed.
