### ISSUE TITLE
ExporterFactory, connection string selector support

### ISSUE THREAD

**Issue by dkarlovi** [open-telemetry/opentelemetry-php#184]
**Is your feature request related to a problem?**

Currently, the exporters are constructed and injected into the processor manually as instances.

When using this instrumentation in a dynamic environment, the endpoint might be determined by the ops setup, meaning it can be changed without the app needing to be changed.

**Describe the solution you'd like**

Allowing the exporter to be selected via the configuration string ("DSN"), like so

```
zipkin+http://zipkin:9411/api/v2/spans # Zipkin\Exporter
jaeger+http://jaeger:9412/api/v2/spans # Jaeger\Exporter
```
etc

This would mean you can do:

```php
$factory = new ExporterFactory('predefinedName');

// env var ENDPOINT= zipkin+http://zipkin:9411/api/v2/spans
$exporter = $factory->fromConnectionString(getenv('ENDPOINT'));

// $exporter instanceof Zipkin\Exporter
```

**Describe alternatives you've considered**

This is a pretty standard solution to this problem (see Doctrine).

**Additional context**

This would come in really handy when doing this for a Symfony bundle, which I'm currently looking into.

**Comment by beniamin** [comment]
I like the idea. I think that this proposal will fit more in the opentelemetry-specification repository, because the API should be common to other libraries.

**Comment by dkarlovi** [comment]
@beniamin so what would you propose as next steps? Implement it here or first discuss it there?

**Comment by beniamin** [comment]
I would say that a discussion should be started in opentelemetry-specifications.

**Comment by prondubuisi** [comment]
> @beniamin so what would you propose as next steps? Implement it here or first discuss it there?

Hello @dkarlovi  I think @beniamin is implying we start a discussion here https://github.com/open-telemetry/opentelemetry-specification for this

**Comment by dkarlovi** [comment]
Created an issue there: https://github.com/open-telemetry/opentelemetry-specification/issues/1071

**Comment by bobstrecansky** [comment]
Looks like we can put this one down into the backlog?

**Comment by dkarlovi** [comment]
@bobstrecansky not sure what the conclusion is in the other issue TBH. 😁

**Comment by bobstrecansky** [comment]
@dkarlovi - I think @bogdandrutu was saying that we should defer this work until after GA is complete.

**Comment by alexperez52** [comment]
Hi, 
I'd like to take this issue if it's available!

**Comment by bobstrecansky** [comment]
@prondubuisi - that alright with you? ^

**Comment by prondubuisi** [comment]
Hello @alexperez52, please go for it. It is available.

**Comment by alexperez52** [comment]
Hello, 
Both Jaeger and Zipkin exporters take the same arguments; However the Newrelic and Otlp exporters have a different arrangement of arguments.
Should they all still be produced through the same factory ?

**Comment by dkarlovi** [comment]
@alexperez52 yes, that's the idea.

**Comment by dkarlovi** [comment]
My general idea is to put common things into the base URL and put exporter-specific things into the query string, like so:

```
type+https://username:password@host:port/path?option1=a&option2=b
```

The options in the query string are exporter specific, for example for New Relic you'd pass the licence key using it.

ie:

```
newrelic+https://wherever.you/must/point/it/too?licenceKey=abcdefgh
```

You could do all this using for example https://github.com/Nyholm/dsn

**Comment by SeanHood** [comment]
Just saw the PR go past so thought I'd jump into the discussion. Firstly I really like this idea, looks to make it much easier to integrate the SDK into applications.

However I am curious how passing headers could be supported? For instance in the OtlpGrpc exporter headers can be set to pass write keys/dataset names; this is how services like Lightstep and Honeycomb.io work (can't find docs for OTLP ingestion from other services).

For example:
```
otlpgrpc+grpc://api.example.com:4317/?header_x-api-key=xyz&header_x-some-header=abc
```

**Comment by bobstrecansky** [comment]
cc:\ @zsistla for awareness here.

**Comment by bobstrecansky** [comment]
This is closed with https://github.com/open-telemetry/opentelemetry-php/pull/351
