### ISSUE TITLE
Add Psalm and PHPStan to Static Analysis tools to CI/CD tooling

### ISSUE THREAD

**Issue by prondubuisi** [open-telemetry/opentelemetry-php#196]
Based on discussions here https://github.com/open-telemetry/opentelemetry-php/pull/185, we are looking forward to adding the following static analysis tools

 [PHPStan](https://github.com/phpstan/phpstan)
 [Psalm](https://github.com/vimeo/psalm)

**Comment by bobstrecansky** [comment]
@prondubuisi - are you planning on taking this on?

**Comment by prondubuisi** [comment]
Yes @bobstrecansky

**Comment by prondubuisi** [comment]
Hello @bobstrecansky we only implemented one part of this. We are yet to add PHPStan

**Comment by bobstrecansky** [comment]
Ahhh yup; reopening until PHPStan is implemented.

**Comment by bobstrecansky** [comment]
We can close this now as PHPStan and Psalm are both implemented.
