### ISSUE TITLE
Dogfooding / User Research

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#206]
Put ourselves in the end user's shoes using the document below:

https://docs.google.com/document/d/1rXT2eEAniVM7r8KiikzgJJ-r36shOg_twZP6GPzNvao/edit#heading=h.19lsfyhsve8e

**Comment by dkarlovi** [comment]
Let me know how you'd like me to help. I can give you experience from integrating it in a **large** Symfony app.

**Comment by bobstrecansky** [comment]
Just following along with that document that is linked in the ticket!

**Comment by dkarlovi** [comment]
Done here:
https://docs.google.com/document/d/1n43oTVsnydmbpzvhN-5dgPAvRWKZCiugmmR_wg_8ziQ/edit?usp=sharing

Repo here
https://github.com/dkarlovi/opentelemetry-php-user-test

HTH :beers:
