### ISSUE TITLE
How to get rid of op.status_code and op.status_description tag?

### ISSUE THREAD

**Issue by adhocore** [open-telemetry/opentelemetry-php#209]
Using v0.0.1 of telemetry

![image](https://user-images.githubusercontent.com/2908547/98081496-ca767800-1ea9-11eb-9343-9a6901ff320c.png)

Wondering what these tags are for and how to get rid of them?
We have 1000s of spans so we don't want to have this tag getting in our way.

Is it possible to disable it by configuration?

Code that adds these tags is in
https://github.com/open-telemetry/opentelemetry-php/blob/v0.0.1/contrib/Zipkin/SpanConverter.php#L57-L60

**Comment by bobstrecansky** [comment]
Those are currently required fields as part of the spanConverter:

https://github.com/open-telemetry/opentelemetry-php/blob/2514c45b55b615b6a3dc81943ce14bf1fc143956/contrib/Zipkin/SpanConverter.php#L59-L60

I'd welcome a PR for making them optional if that's something y'all are interested in!

**Comment by bobstrecansky** [comment]
Was also considering - is there a reason this is labeled as a bug?  I believe it's intended behavior as defined by the spec.

**Comment by adhocore** [comment]
for us they are just chunk of unwanted extraneous tags that take up the space in elasticsearch backend and clutter up the ui and intrigue user as it was not like that before.

in the java based telemetry sdk we using, we don't have these tags - not sure though if that is because of using old version.

it was automatically labelled as bug (perhaps GH issue template played in), however it was purely a question.

**Comment by bobstrecansky** [comment]
Cool.  Appreciate your PR!  Following up with the other maintainers on this.

**Comment by bobstrecansky** [comment]
@adhocore - It appears the status code is required and the description is optional. I'm wondering if it'd be worth the added complexity of flagging just that one specific field.

**Comment by adhocore** [comment]
hmm ok let me close it then 😁
