### ISSUE TITLE
Correct type for __construct Span parameter

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#21]
@morrisonlevi mentioned that the correct type for this Span parameter is ?SpanContext:

https://github.com/open-telemetry/opentelemetry-php/pull/18/files#diff-fb862e90b17f754862ac86b494ddb0a4R22

Success Criteria: Update the Span parameter.

**Comment by AustinSchoen** [comment]
I looked over the Spec again, and it seems like this is not an optional parameter? Seems like every span should have an accompanying SpanContext?

**Comment by bobstrecansky** [comment]
I would think that should be the case.

**Comment by bobstrecansky** [comment]
I discussed this with Austin; we don't believe that this should be an optional parameter: https://github.com/open-telemetry/opentelemetry-php/blob/master/src/Tracing/Span.php#L39
