### ISSUE TITLE
W3C Trace Context Test Service

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#217]
After finishing the W3C Trace Context work, we'd like to validate the changes we make don't break the W3C spec.  The w3c provides the W3C Distributed Tracing Validation Service, which allows us to test against a service.  The service and definition can be found at the following link:

https://github.com/w3c/trace-context/tree/master/test

Success criteria - create a `Make` task that allows validation with this service. We'll add it into the Github actions workflow after we've determined it's necessary.

@Fahmy-Mohammed mentioned wanting to work on this task.

**Comment by bobstrecansky** [comment]
@Fahmy-Mohammed is working on this.

**Comment by Fahmy-Mohammed** [comment]
I'm working on this
