### ISSUE TITLE
User Research Feedback Improvements - Missing Exception

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#219]
@dkarlovi's [User Research Document](https://docs.google.com/document/d/1n43oTVsnydmbpzvhN-5dgPAvRWKZCiugmmR_wg_8ziQ/edit#) points out that no exception is raised.

In dev mode, he mentioned that not being able to flush spans or not recording any spans should result in an exception being thrown.

This bug report came from [this comment](https://docs.google.com/document/d/1n43oTVsnydmbpzvhN-5dgPAvRWKZCiugmmR_wg_8ziQ/edit#)

**Comment by bobstrecansky** [comment]
throwing exceptions:

1. NoSpansCreatedException
2. InvalidExporterEndpointException

in dev mode would definitely help

**Comment by zsistla** [comment]
I'll work on this.

**Comment by prondubuisi** [comment]
Hello @bobstrecansky @dkarlovi I would love to check this out, but I have some questions

While testing https://github.com/dkarlovi/opentelemetry-php-user-test with the wrong address, I had an exception

```
Ndubuisis-MacBook-Pro:otel-php-test prondubuisi$ bin/console app:hello
InvalidArgumentException {#17
  #message: "Unable to parse provided DSN"
  #code: 0
  #file: "/Users/prondubuisi/gitrepos/otel-php-test/vendor/open-telemetry/opentelemetry/contrib/Zipkin/Exporter.php"
  #line: 54
  trace: {
    /Users/prondubuisi/gitrepos/otel-php-test/vendor/open-telemetry/opentelemetry/contrib/Zipkin/Exporter.php:54 { …}
    /Users/prondubuisi/gitrepos/otel-php-test/bin/console:59 {
      ›     'My App name CLI',
      ›     'http://localhost:941277/api/v2/spans'
      › );
      arguments: {
        $name: "My App name CLI"
        $endpointUrl: "http://localhost:941277/api/v2/spans"
      }
    }
  }
}
2021-01-31T23:29:12+01:00 [critical] Uncaught Exception: Unable to parse provided DSN


```

I am wondering if we need to change this exception to `InvalidExporterEndpointException`

Also is there a way to look into docker or elsewhere within a codebase to suggest an appropriate endpoint from the SDK?
Lastly is there a way to tell if the SDK is being used in Dev Mode? or should we allow developers using the SDK to determine if they want to turn errors off or on using indicators particular to their implementation?

**Comment by bobstrecansky** [comment]
It does seem that needs to be changed to `InvalidExporterEndpointException` - good catch.

```
Also is there a way to look into docker or elsewhere within a codebase to suggest an appropriate endpoint from the SDK?
```

Not tracking this question exactly.  Are you talking about how to find the appropriate endpoint for the app?  If so, it probably wouldn't be worth digging into that, as the method for standing up that endpoint may vary greatly by implementation.


```
 Lastly is there a way to tell if the SDK is being used in Dev Mode? or should we allow developers using the SDK to determine if they want to turn errors off or on using indicators particular to their implementation?
```

There currently is not a dev mode for OpenTelemetry PHP.  What sort of information would you hope to garner from such a mode?

**Comment by prondubuisi** [comment]
Hello, @bobstrecansky I agree with all of the above. As regards the Dev Mode, We did mention it a lot in the course of this issue. See above. That said, I think displaying exception messages or not should be handled by the Apps using the SDK. 

I will get to work, on adding the InvalidExporterEndpointException to the SDK

**Comment by prondubuisi** [comment]
So how can I create custom exceptions for OpenTelemetry? I tried
`use InvalidExporterEndpointException;` 
and it turns out the class doesn't exist
Also, where do we get the exception classes currently used within the project?

**Comment by dkarlovi** [comment]
> There currently is not a dev mode for OpenTelemetry PHP. What sort of information would you hope to garner from such a mode?

I think a more correct term would be "debug mode". In debug mode (assumed to be used in the dev env), SDK could point out helpful (verbose) error messages and hints during the instrumentation process.

Symfony offers a debug mode which allows the entire framework to spring (pun intended) into action and provide the developer with loads of additional tools, hints, messages, etc, none of which is done in release mode because of performance.

The most obvious example is given in the task: if no spans were created, throw an exception which explains this to the developer, with hints how to proceed. If the exporter is unable to flush the spans, throw an exception instead of silently failing.

It could lead to more DX improvements in the future: there could be a specialized version of the Tracer (`HelpfulTracer`) which inspects the spans collected and try to hint at what could be done to improve them, like a "span linter", checking for best practice usage etc. Maybe the developer chose the wrong exporter (we might be able to detect that).

There's quite a bit of opportunity to ease the pain of doing this right.

**Comment by tidal** [comment]
Related: https://github.com/open-telemetry/opentelemetry-php/pull/460#issuecomment-962429788

**Comment by tidal** [comment]
Closing this issue as according to the [spec](https://github.com/open-telemetry/opentelemetry-php/pull/460#issuecomment-962429788) the API/SDK must not throw unhandled exceptions and using exceptions to handle logic is expensive.

General error handling is covered in https://github.com/open-telemetry/opentelemetry-php/issues/298

**Comment by dkarlovi** [comment]
@tidal this seems to be a misunderstanding: the exception thrown here doesn't relate to the spec in any way, it's a way to improve DX as you're implementing the SDK in your own app, warning of a common setup issue. It's meant to be thrown in `debug` mode only, assuming the SDK gets such a mode (as outlined in https://github.com/open-telemetry/opentelemetry-php/issues/219#issuecomment-816544097).

There's no "handling of logic with exceptions" here.

**Comment by tidal** [comment]
@dkarlovi 
Sorry, this ticket has been a bit all over the place. If you think there is a misunterstanding, I will try to address your concerns.

The ticket has initially been about missing exceptions, and what you describe is a bit more. We are trying to get rid of exceptions atm, and replace them with logging etc., so there will no silent failing 

In general there will probably no "debug mode" at least not for the API/SDK. Error handling and self-diagnostic are adressed in https://github.com/open-telemetry/opentelemetry-php/issues/298 and https://github.com/open-telemetry/opentelemetry-php/issues/299 which will allow for a bit more fined grained approach than simply havinga a debug flag, and there are people working on these issues atm. 
This does not stop any downstream projects/packages/etc. from introducing such a "debug mode" by leveraging the tools provided by the library, but for the SDK we cannot tunnel vision on any framework, etc. as we have to be as much "open" as possible.

Regarding Symfony, there will be no Symfony bundle, but there will be three different bundles. The bundle we have at the moment is merely a bridge between the SDK and Symfony, and is providing configuration for the SDK in Symfony. However 
this is subject to change, as there was no configuration for the SDK before, but is the works now. 
For the other two bundles I have created [tickets ](https://github.com/open-telemetry/opentelemetry-php-contrib/issues) now, as this has not been documented before. In essence one bundle addresses auto-instrumentation for/in Symfony, the other one debugging through the Symfony profiler.

However for the SDK and the Symfony bundle we can assume developers to have basic trouble shooting skills, and we will provide trouble shooting with the tools we have, as this is the purpose of telemetry data in the first place. There will not be much use for developers using the SDK, if they cannot use the tools provided by it to debug the SDK itself. However, again, that doesn't stop any downstream project or project using the SDK from providing a bit more hand holding approach.

As for the example of no spans being created: This is assuming that spans must be created in the first place. This might be addresses in an e2e tests, however in general there can be a lot of reasons why no spans are created. Distributed tracing is not of much use to be used only for one application, as there are better tools to find bottlenecks. So in general we have to assume dictributed tracing with at least two peers (what ever they are). In trace propagation there can be a lot of reasons why no traces are recorded, which may be dictated by a different application/peer. There are also samplers, which do not create spans for every request etc. in the first place to avoid to much unnecessary data.

So I hope you understand the decision for closing this ticket, but we were talking about opening the discussion board, and as a general idea this topic yould be put there.

---

btw.



> ```yaml
> opentelemetry:
>     debug: %kernel.debug%
> ```

This is not really needed as the bundle extension classes have [access to the container builder](https://github.com/open-telemetry/opentelemetry-php-contrib/blob/12472d143fcc6c49f97071e1a67af734d681b5df/src/Symfony/OtelSdkBundle/DependencyInjection/OtelSdkExtension.php#L789) anyway. On the other hand the configuration classes (usually) have no way of resolving container parameters, so this would be hard to validate, as ```%kernel.debug%``` is just a string for the config validation.

**Comment by dkarlovi** [comment]
@tidal you seem to have a much better idea where the work is going so I deferring to you to make these decisions, I wanted to clarify the point of the initial issue which was created based on my feedback on the (then) SDK state.

About the Symfony specific (no bundle, three bundles, config parsing), I don't think we need to discuss it in detail here. :+1: Thanks!
