### ISSUE TITLE
PHP Documentor

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#222]
We should create some autogenerated documentation.  

I'm going to propose that we use https://www.phpdoc.org/ but I'm also very open to suggestions on what to use for this autogenerated documentation.

**Comment by bobstrecansky** [comment]
We can currently generate something pretty simple using:

`docker run --rm -v ${PWD}:/data -v ${PWD}/docs:/tmp/docs phpdoc/phpdoc:3 -d ./api -d ./sdk -d ./contrib -t /tmp/docs`

**Comment by dkarlovi** [comment]
The documentation generated in this way is usually not what you'd want as a developer. This would generate what I'd call a "reference manual", listing the available API. What we need is human-generated content meant for human consumption, for example [Guzzle](https://docs.guzzlephp.org/en/stable/overview.html), [PHP HTTP](http://docs.php-http.org/en/latest/index.html), [Symfony](https://symfony.com/doc/current/index.html), etc.

The value and usage of this type of docs is so low [Symfony was thinking about removing them](https://twitter.com/fabpot/status/889797265203896323).

**Comment by bobstrecansky** [comment]
@dkarlovi - you think the result isn't worth the effort in generating this documentation?  Maybe we could perhaps improve the existing README.md or add additional documentation somewhere?

**Comment by dkarlovi** [comment]
I think starting to build real documentation is the right direction here. A good start would be using Github pages, this allows us to start working on this right away.

**Comment by prondubuisi** [comment]
The approach of putting in thoughtful work on the documentation makes sense. In the long run, we will all be better for it.  Please do tag me as this developes

**Comment by bobstrecansky** [comment]
@prondubuisi - were you thinking about creating this documentation, or were you just wanting to follow along as it is created?

**Comment by prondubuisi** [comment]
Both @bobstrecansky. Just tell me what is needed.

**Comment by bobstrecansky** [comment]
@prondubuisi - I think a great start would be some implementation documentation.  We have the readme info and the examples, but we don't have something akin to a "getting started guide" or the like.  I think that'd be a fantastic start!
