### ISSUE TITLE
User Research Feedback Improvements - Finish all Spans Feature

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#224]
We'd like to have a "Finish all Spans" feature.

This comes from [this comment](https://docs.google.com/document/d/1n43oTVsnydmbpzvhN-5dgPAvRWKZCiugmmR_wg_8ziQ/edit?disco=AAAAHTU6d40)

**Comment by prondubuisi** [comment]
Hello @dkarlovi can you please help us understand the issue here? Thanks

**Comment by dkarlovi** [comment]
@prondubuisi in general, all the details should be readable from the linked comment, no?

In this case, it's like this:

What's created:

```
span1:
    span2:
        EXCEPTION
```

What you get in Jaeger:
```
span2:
    EXCEPTION
```

The idea is: if this happens, *all* the spans created should be flushed, not just the ones where you called flush explicitly. If I created a span, that span should be flushed in 100% of the cases.

**Comment by bobstrecansky** [comment]
@dkarlovi - can you clarify with some example code?  @prondubuisi and I were looking into how to fix this, but without an example it becomes difficult to diagnose and troubleshoot!  Thanks in advance!

**Comment by dkarlovi** [comment]
Sure, I've just pushed an example here: https://github.com/dkarlovi/opentelemetry-php-user-test

Relevant code is:
```php
// index.php
$span = $tracer->startAndActivateSpan($request->getUri());

// controller
$span = $tracer->getActiveSpan();
$tracer->startAndActivateSpan('Child span');            

throw new \Exception('Ruh roh');
```

Setup the project and access http://127.0.0.1:8000/exception, you will get this, notice that the parent span is missing:

![Jaeger-UI](https://user-images.githubusercontent.com/209225/113996605-9f78c180-9857-11eb-9d18-6834cfd43e85.png)

**Comment by bobstrecansky** [comment]
Thank you @dkarlovi !

@prondubuisi - are you planning on working through this ticket?  I'll assign it to you.

**Comment by bobstrecansky** [comment]
@prondubuisi - are you still planning on working through this?
