### ISSUE TITLE
 User Research Feedback Improvements - Uncaught Exception in child span

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#226]
If an uncaught exception is thrown in a child span, it is not currently recorded as a span error.  In @dkarlovi's example, he's also missing the parent span, he only at this point receives the child span.

This ticket came from [this comment](https://docs.google.com/document/d/1n43oTVsnydmbpzvhN-5dgPAvRWKZCiugmmR_wg_8ziQ/edit?disco=AAAAHTU6d5Y)

**Comment by zsistla** [comment]
I'll work on this.

**Comment by siv2r** [comment]
Is this issue available to be worked on? `on hold` label to gives some red signal.

**Comment by bobstrecansky** [comment]
@siv2r - @zsistla is working on this, but it has a prerequisite task to complete before it can be completed.

**Comment by siv2r** [comment]
Okay :+1: 
Thanks for the info!!

**Comment by dkarlovi** [comment]
> he's also missing the parent span, he only at this point receives the child span.

This part is related to #224.

**Comment by prondubuisi** [comment]
Hello @dkarlovi does this mean we can consider this fixed, if we fix Issue #224

**Comment by bobstrecansky** [comment]
@zsistla - would you like me to assign this to someone else, or would you like to finish it up?
