### ISSUE TITLE
Adding InstrumentationLibrary to SDK

### ISSUE THREAD

**Issue by riticksingh** [open-telemetry/opentelemetry-php#228]
Adding instrumentation feature to opentelemetry-php to sdk mentioned here: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#additional-span-interfaces

While working for OTLP/GRPC , it requires Instrumentation library in sdk for dealing with proto files

Something like this : [opentelemetry-go reference ](https://github.com/open-telemetry/opentelemetry-go/blob/66db2d845ba72bae8fcc1b3d43965470cbe8f5c3/sdk/instrumentation/library.go)

**Comment by bobstrecansky** [comment]
@riticksingh - are you still planning on working on this?

**Comment by riticksingh** [comment]
I am not getting the exact definition for Instrumentation from specification repo

**Comment by bobstrecansky** [comment]
Have you asked in the specification gitter channel for more specifics?

**Comment by riticksingh** [comment]
Yup I asked the in channel of specification but doesn't got any reply

**Comment by lalex** [comment]
@riticksingh `InstrumentationLibrary` was added in #101 and then was replaced by `ResourceInfo` in #133, but the spec has been updated after (https://github.com/open-telemetry/opentelemetry-specification/pull/616).

**Comment by riticksingh** [comment]
Ok I will go through this

**Comment by bobstrecansky** [comment]
@riticksingh - what's the status of this?
