### ISSUE TITLE
Span Context does not conform to latest OTel spec

### ISSUE THREAD

**Issue by jodeev** [open-telemetry/opentelemetry-php#235]
There are some differences between our implementation and specs. 

For Span Context, the following gaps were identified for our current implementation:
* does not export binary TraceId and SpanId
* isValidContext should be renamed into isValid
* isRemoteContext should be renamed into isRemote
* TraceState should be changed into an object instead of an array - it will ease the actions on it described here: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#tracestate
* TraceState is not implemented in the sdk, or there is no possibility to change the TraceState.

**Comment by Fahmy-Mohammed** [comment]
The bottom two points were implemented in #233:
> - TraceState should be changed into an object instead of an array - it will ease the actions on it described here: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#tracestate
> - TraceState is not implemented in the sdk, or there is no possibility to change the TraceState.

**Comment by wRLSS** [comment]
https://github.com/open-telemetry/opentelemetry-php/pull/247

targets points 2 and 3
