### ISSUE TITLE
Implement "Standard" Span attributes 

### ISSUE THREAD

**Issue by jodeev** [open-telemetry/opentelemetry-php#236]
"Standard" Span Attributes as defined in "[standard attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/418016dc4014f0c64acea74881774d34178bf15a/specification/trace/semantic_conventions/README.md)" need to be implemented.

**Notes**
Spans are not meant to be used to propagate information within a process. To prevent misuse, implementations SHOULD NOT provide access to a Span's attributes besides its SpanContext.

Vendors may implement the Span interface to effect vendor-specific logic. However, alternative implementations MUST NOT allow callers to create Spans directly. All Spans MUST be created via a Tracer.

With the exception of the function to retrieve the Span's SpanContext and recording status, Span Attributes may NOT be called after the Span is finished.

**Comment by wRLSS** [comment]
The link in issue seems to be outdated, the specification under the link does not contain **standard attributes** part
