### ISSUE TITLE
Implement RecordException method for spans

### ISSUE THREAD

**Issue by jodeev** [open-telemetry/opentelemetry-php#237]
[RecordException](https://github.com/open-telemetry/opentelemetry-specification/blob/418016dc4014f0c64acea74881774d34178bf15a/specification/trace/api.md#record-exception) method is not implemented - this method is a specialized variant of AddEvent for recording exception events.

**Notes**
Spans are not meant to be used to propagate information within a process. To prevent misuse, implementations SHOULD NOT provide access to a Span's attributes besides its SpanContext.

Vendors may implement the Span interface to effect vendor-specific logic. However, alternative implementations MUST NOT allow callers to create Spans directly. All Spans MUST be created via a Tracer.

With the exception of the function to retrieve the Span's SpanContext and recording status, RecordException may NOT be called after the Span is finished.

**Comment by prondubuisi** [comment]
Hello @bobstrecansky, I want to work on this

**Comment by prondubuisi** [comment]
Hello @bobstrecansky I think we can close this issue.
