### ISSUE TITLE
Fix default span status

### ISSUE THREAD

**Issue by jodeev** [open-telemetry/opentelemetry-php#238]
Default span status should be `Unset`, but the current implementation uses `Ok`. 

Also the statusCodes list has been shrunk to only 3 statuses as described in the [SetStatus](https://github.com/open-telemetry/opentelemetry-specification/blob/418016dc4014f0c64acea74881774d34178bf15a/specification/trace/api.md#set-status) section and the current behaviour has been changed.

**Notes**
Spans are not meant to be used to propagate information within a process. To prevent misuse, implementations SHOULD NOT provide access to a Span's attributes besides its SpanContext.

Vendors may implement the Span interface to effect vendor-specific logic. However, alternative implementations MUST NOT allow callers to create Spans directly. All Spans MUST be created via a Tracer.

With the exception of the function to retrieve the Span's SpanContext and recording status, Span Status may NOT be changed after the Span is finished.

**Comment by zsistla** [comment]
I'll work on this.

**Comment by zsistla** [comment]
Please see PR: https://github.com/open-telemetry/opentelemetry-php/pull/258
