### ISSUE TITLE
Determining the Parent Span from a Context - should conform to latest OTel spec

### ISSUE THREAD

**Issue by jodeev** [open-telemetry/opentelemetry-php#239]
It seems that the linking between the Context/SpanContext/Span is not implemented properly. 

The OpenTelemetry spec says that the SpanContext should be encapsulated inside the Span, but the Tracer is able to create a new Span with a specific SpanContext, created outside of the Span. 

For example TraceContext::extract returns a SpanContext and Tracer::startAndActivateSpanFromContext receives SpanContext as parameter.

We should follow the spec for the implementation.

**Comment by alexperez52** [comment]
Hello, 
I'd like to take on this issue
