### ISSUE TITLE
Enable Travis CI for our repository

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#24]
Before opening a feature request against this repo, consider whether the feature should/could be implemented in the [other OpenTelemetry client libraries](https://github.com/open-telemetry). If so, please [open an issue in opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/issues/new) first.

**Is your feature request related to a problem?**
It is not.  We'd like to have automated test suites for commits

**Describe the solution you'd like**
We'd like to have CI run on PR open

**Describe alternatives you've considered**
Manual testing

**Comment by VictorAvelar** [comment]
I will take this one.
