### ISSUE TITLE
Implement Context Interaction

### ISSUE THREAD

**Issue by jodeev** [open-telemetry/opentelemetry-php#240]
Implement [Context Interaction](https://github.com/open-telemetry/opentelemetry-specification/blob/6589f46926dbbd11178a9f93889bf83a50ad2dd8/specification/trace/api.md#context-interaction) as per the specification.

**Comment by bobstrecansky** [comment]
@beniamin - are you still planning on working on this?

**Comment by Blacksmoke16** [comment]
Think this is resolved via #410.
