### ISSUE TITLE
Trace Provider should include name + version

### ISSUE THREAD

**Issue by jodeev** [open-telemetry/opentelemetry-php#241]
[TraceProvider](https://github.com/open-telemetry/opentelemetry-specification/blob/6589f46926dbbd11178a9f93889bf83a50ad2dd8/specification/trace/api.md#tracerprovider) should include name + version, as per the spec.

Current implementation identifies Tracers only by name, instead of name+version

**Comment by aman-raza** [comment]
If I make a change
The " optional " tag shouldn't be there

**Comment by YashKumarVerma** [comment]
Is this issue fixed?

**Comment by bobstrecansky** [comment]
Yes, I believe @wRLSS 's PR fixed this.  Closing.
