### ISSUE TITLE
Feedback request: adding engine definition to semantic conventions - beneficial to PHP community?

### ISSUE THREAD

**Issue by ivomagi** [open-telemetry/opentelemetry-php#254]
# Question

As the author of the PR https://github.com/open-telemetry/opentelemetry-specification/pull/1293 I am reaching out to PHP community to get feedback about whether or not the concept of `engine` introduced in the PR will or will not add value to PHP tracing. So if you take a look at the usecases described in the PR and comment about if and how this would also apply to PHP world. 

**What are you trying to achieve?**

Based on the feedback from other communities, a decision will be made whether the concept of `engine` is applicable as a generic semantic convention or it will be specific to Java.  

## Additional Context

The original PR clearly benefits the JVM community, which relies heavily on different Java EE application servers.  The question is asked to see where the PHP community stands in regards of the value of the information being exposed.

**Comment by bobstrecansky** [comment]
I think the concept of an "engine" would be good and we'd probably use it for a myriad of things!

**Comment by Oberon00** [comment]
>  for a myriad of things

That might hint that the definition of "engine" is too vague. Especially since you can only have one per process. Please also provide feedback on open-telemetry/opentelemetry-specification#1293 if possible.

**Comment by ivomagi** [comment]
@bobstrecansky indeed if you could provide examples of what would you use the `engine` for in PHP, it would help to understand the concerns @Oberon00 referred.

**Comment by bobstrecansky** [comment]
I'd think it would probably be used for things like php-fpm vs mod_apache or something similar
