### ISSUE TITLE
Change SpanContext to Baggage

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#259]
We should use the standard implementation of [Baggage](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/baggage/api.md)

@Fahmy-Mohammed mentioned he would work on this in our meeting today.

**Comment by Fahmy-Mohammed** [comment]
Yes, I can work on this

**Comment by jimshowalter** [comment]
@Fahmy-Mohammed Do you have a sense for how long it will take to make PHP support baggage, and do you want help?

**Comment by Fahmy-Mohammed** [comment]
I'll work on this over the weekend 👍🏾
