### ISSUE TITLE
Support for API only in absence of installed SDK

### ISSUE THREAD

**Issue by jodeev** [open-telemetry/opentelemetry-php#267]
Our current library does not have support to install only the API. 

We should support this and conform to ["Behavior of the API in the absence of an installed SDK"](https://github.com/open-telemetry/opentelemetry-specification/blob/418016dc4014f0c64acea74881774d34178bf15a/specification/trace/api.md#behavior-of-the-api-in-the-absence-of-an-installed-sdk) from the spec.

**Comment by bobstrecansky** [comment]
Hey!  I don't think we need to do this - this isn't a common PHP idiom.  We can revisit later if we decide to.
