### ISSUE TITLE
Update sampling behavior to conform to spec

### ISSUE THREAD

**Issue by jodeev** [open-telemetry/opentelemetry-php#268]
These gaps have been identified in our sampling:
* Default sampler should be ParentBasedSampler as described in [SDK Span Creation](https://github.com/open-telemetry/opentelemetry-specification/blob/418016dc4014f0c64acea74881774d34178bf15a/specification/trace/sdk.md#sdk-span-creation).
* The flag combination `SampledFlag == true` and `IsRecording == false` could cause gaps in the distributed trace, and because of this, our OpenTelemetry API MUST NOT allow this combination.
* SamplingResult
   * Sampling Decision values has been changed to: DROP, RECORD_ONLY, RECORD_AND_SAMPLE
must contain the Tracestate
   * Does not contain Links --> there may be an error in specs???

**Comment by lalex** [comment]
I can take this.
