### ISSUE TITLE
Update ParentBased sampler to conform to spec

### ISSUE THREAD

**Issue by jodeev** [open-telemetry/opentelemetry-php#269]
Our current implementation has these gaps:
* requires the root(Sampler) parameter. This root sampler should be called for spans with no parent.
* Optional parameters not implemented.
* Sampler behaviour should depend on parameters as described here: https://github.com/open-telemetry/opentelemetry-specification/blob/418016dc4014f0c64acea74881774d34178bf15a/specification/trace/sdk.md#parentbased

**Comment by lalex** [comment]
@jodeev this issue was probably fixed in #234.
