### ISSUE TITLE
SpanKind not propagate to Span constructor

### ISSUE THREAD

**Issue by MartaSadowskaBarankiewicz** [open-telemetry/opentelemetry-php#274]
**Steps to reproduce**
```
 $tracer = (new TracerProvider())->getTracer('io.opentelemetry.contrib.php');
 $context = SpanContext::generate(true);
 $span = $tracer->startAndActivateSpan('myspan', API\SpanKind::KIND_SERVER);
 var_dump($span);
$tracer->endActiveSpan();
```

**What is the expected behavior?**
SpanKind of span is set to the chosen one.

**What is the actual behavior?**
```
object(OpenTelemetry\Sdk\Trace\Span)#43 (14) {
  ["name":"OpenTelemetry\Sdk\Trace\Span":private]=>
  string(6) "myspan"
  ["spanContext":"OpenTelemetry\Sdk\Trace\Span":private]=>
  object(OpenTelemetry\Sdk\Trace\SpanContext)#36 (7) {
    ["traceId":"OpenTelemetry\Sdk\Trace\SpanContext":private]=>
    string(32) "9c46a6f23cc923062fd9299d8aa46abe"
    ["spanId":"OpenTelemetry\Sdk\Trace\SpanContext":private]=>
    string(16) "c361c55902716d0f"
    ["traceState":"OpenTelemetry\Sdk\Trace\SpanContext":private]=>
    NULL
    ["isSampled":"OpenTelemetry\Sdk\Trace\SpanContext":private]=>
    bool(true)
    ["isValid":"OpenTelemetry\Sdk\Trace\SpanContext":private]=>
    bool(true)
    ["isRemote":"OpenTelemetry\Sdk\Trace\SpanContext":private]=>
    bool(false)
    ["traceFlags":"OpenTelemetry\Sdk\Trace\SpanContext":private]=>
    int(1)
  }
  ["parentSpanContext":"OpenTelemetry\Sdk\Trace\Span":private]=>
  NULL
  ["spanKind":"OpenTelemetry\Sdk\Trace\Span":private]=>
  int(0)
...
```
SpanKind is set to `API\SpanKind::KIND_INTERNAL`, the default SpanKind.

**Additional context**
During span creation using Tracer functions `startAndActivateSpan` or `startAndActivateSpanFromContext`, spanKind passed as parameter isn't propagated to `generateSpanInstance` function and then it's not used in Span constructor call:
https://github.com/open-telemetry/opentelemetry-php/blob/9ee14027b6f7d3504a82f95f34a3309cb53e7ca7/sdk/Trace/Tracer.php#L85
https://github.com/open-telemetry/opentelemetry-php/blob/9ee14027b6f7d3504a82f95f34a3309cb53e7ca7/sdk/Trace/Tracer.php#L200
It's also not set later in any place. As a result, there is no possibility to use any other SpanKind than default `API\SpanKind::KIND_INTERNAL`.

**Comment by MartaSadowskaBarankiewicz** [comment]
I'd like to prepare fix for that.

**Comment by bobstrecansky** [comment]
Sure thing @MartaSadowskaBarankiewicz - I'll assign this issue to you.  Feel free to open a PR and we'll review it for you!
