### ISSUE TITLE
Update SpanProcessor parameters OnStart + OnEnd

### ISSUE THREAD

**Issue by jodeev** [open-telemetry/opentelemetry-php#278]
Conform to interfaces requirements in spec for SpanProcessor, see https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#interface-definition

**[OnStart](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#onstart)**
* Parameters should be:
  * `span` - a read/write span object for the started 'span'. It SHOULD be possible to keep a reference to this span object and updates to the span SHOULD be reflected in it. For example, this is useful for creating a SpanProcessor that periodically evaluates/prints information about all active span from a background thread.
  * `parentContext` - the parent `Context` of the span that the SDK determined (the explicitly passed `Context`, the current `Context` or an empty `Context` if that was explicitly requested).

**[OnEnd](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#onendspan)**
* Parameters:
  * `span` - a readable span object for the ended span. Note: Even if the passed Span may be technically writable, since it's already ended at this point, modifying it is not allowed.

**Comment by lalex** [comment]
I can work on it.
