### ISSUE TITLE
Event Attributes not accessible on both Zipkin and Jaeger for Otel-PHP examples 

### ISSUE THREAD

**Issue by prondubuisi** [open-telemetry/opentelemetry-php#283]
Otel-php provides examples for exporting traces to both Zipkin and Jaegar, and while span traces get displayed on both visualization tools, I have noticed that `attribute` arguments passed to events via `$span->addEvent()`, do not get displayed on both tools

On the other hand, attributes set to span using `$span->setAttribute()` appear as tags.

@zsistla I am wondering if you are able to see attributes passed via `addEvent()` with `AlwaysOnZipkinToNewrelicExample`

Here are steps to reproduce the error;
on the project repository

run `make examples`
navigate to `http://localhost:9411/zipkin/` to see example traces on Zipkin
navigate to `http://localhost:16686/search` to see example traces on Jaegar

It is worthy of note that the tests for attributes on both examples pass, also I have tried tweaking the timestamps for the [recordException method](https://github.com/open-telemetry/opentelemetry-php/blob/main/sdk/Trace/Span.php#L222) using the timestamp example here https://github.com/open-telemetry/opentelemetry-php/blob/bb0bbafec1d48509171aa12be68182075ef8e459/contrib/ZipkinToNewrelic/SpanConverter.php#L56 as suggested by @bobstrecansky 

notice that the attributes from both [Zipkin](https://github.com/open-telemetry/opentelemetry-php/blob/main/examples/AlwaysOnZipkinExample.php#L51) and [Jaegar](https://github.com/open-telemetry/opentelemetry-php/blob/main/examples/AlwaysOnJaegerExample.php#L51) are not visible 

Below is the screenshot for both Zipkin and Jaegar

![image](https://user-images.githubusercontent.com/22311928/111207483-fb8a5600-85c9-11eb-8d5e-3a5effe3191e.png)
![image](https://user-images.githubusercontent.com/22311928/111207621-25dc1380-85ca-11eb-8694-19e07dbf8656.png)

**Comment by bobstrecansky** [comment]
@prondubuisi - just wanted to follow up with you and check on the status of this issue.
