### ISSUE TITLE
Implement SpanExporter - Export() per spec

### ISSUE THREAD

**Issue by jodeev** [open-telemetry/opentelemetry-php#294]
Implement [Export()](https://github.com/open-telemetry/opentelemetry-specification/blob/b67faa4e0106cac194a837e3d419ae4fab9fc1c4/specification/trace/sdk.md#exportbatch) from [SpanExporter](https://github.com/open-telemetry/opentelemetry-specification/blob/b67faa4e0106cac194a837e3d419ae4fab9fc1c4/specification/trace/sdk.md#span-exporter) section of the spec.

For reference, these are the spec requirements:

**Export()**

Exports a batch of [readable spans](https://github.com/open-telemetry/opentelemetry-specification/blob/b67faa4e0106cac194a837e3d419ae4fab9fc1c4/specification/trace/sdk.md#additional-span-interfaces). Protocol exporters that will implement this function are typically expected to serialize and transmit the data to the destination.

Export() will never be called concurrently for the same exporter instance. Export() can be called again only after the current call returns.

Any retry logic that is required by the exporter is the responsibility of the exporter. The default SDK SHOULD NOT implement retry logic, as the required logic is likely to depend heavily on the specific protocol and backend the spans are being sent to.

Returns ExportResults which can be one of Success or Failure.

**Comment by bobstrecansky** [comment]
OTLP has this functionality, we should make sure we test this properly.

It has to pass all of the OTLP protocol tests!
