### ISSUE TITLE
Implement Jaeger exporter

### ISSUE THREAD

**Issue by jodeev** [open-telemetry/opentelemetry-php#296]
We currently use Zipkin exporter as Jaeger exporter, but the latter has diverged and should have its own implementation. 

See [Jaeger spec](https://github.com/open-telemetry/opentelemetry-specification/blob/418016dc4014f0c64acea74881774d34178bf15a/specification/trace/sdk_exporters/jaeger.md) .

**Comment by Grunet** [comment]
I'll go ahead and plan on tackling this.

1st thing is that the above Jaeger spec link is stale. [Here's one pointing to the latest version](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md).

From a quick skim of it it seems like there may be 2 or 3 sections shared with the Zipkin exporter, but it may make sense to just start from scratch and then see what shakes out/makes sense to refactor at the end. (I also don't recall any of the Java, Python, Go, or JS ones for Zipkin I looked at seeming like they were sharing code with a Jaeger implementation, but I might be wrong)

Per the [language SDK compliance matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md), it seems like Go, Java, Python, Ruby, and Rust have the best implementations of the spec so far.

Based on that, I think I'll take a look at/take notes on how Go, Java, and Python do their implementations for starters and use them to better understand the spec (with an ultimate aim of writing a PHP implementation based on theirs)

**Comment by Grunet** [comment]
In-flight PRs relevant to this to keep in mind

- #337 
- #482 

Interesting [issue](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1973) from Java that has some interesting info/context around this.  From there I found the [SDK env variables for Jaeger](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#jaeger-exporter), which also help to clarify what's needed in terms of serialization+communication protocols a little.

Jaeger docs

- Some details on [the Jaeger agent](https://www.jaegertracing.io/docs/1.29/deployment/#agent)
- Details on the [3 allowed serialization+communication protocols](https://www.jaegertracing.io/docs/1.23/apis/#thrift-over-udp-stable)

**Comment by Grunet** [comment]
- [Java's code](https://github.com/open-telemetry/opentelemetry-java/blob/e0854d6ac11cfe4c3794255d365b2272939674a4/exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/Adapter.java) for converting between OTLP and Jaeger's Thrift format looked reasonable enough to adapt from a first skim (at least I didn't notice anything obviously blocking, maybe excepting the [id handling](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md#ids) at the end). 
    - It does seem like they're relying on an [OpenTracing Jaeger client](https://mvnrepository.com/artifact/io.jaegertracing/jaeger-thrift) of some sort to handle actually transmitting data via Thrift to a Jaeger instance. Seems like [ jaeger-client-php](https://github.com/jonahgeorge/jaeger-client-php) could be the analog for PHP? Feels a little odd

- Can't quite grok Go or figure out where relevant code is yet, but I did notice [they mention](https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/jaeger#contributing) they have[ a copy of the Apache Thrift library](https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/jaeger/internal/third_party/thrift) in their source code. Seems like the [apache/thrift](https://packagist.org/packages/apache/thrift) package in PHP would be the analog?

- Here's [Python's implementation](https://github.com/open-telemetry/opentelemetry-python/blob/main/exporter/opentelemetry-exporter-jaeger-thrift/src/opentelemetry/exporter/jaeger/thrift/translate/__init__.py) of converting between OTLP and Jaeger format. Didn't look too different from Java's from a quick skim, though it maybe felt a little "short" (like something might be missing). Would probably be interesting to take detailed notes on both against the spec
    - For [handling transport](https://github.com/open-telemetry/opentelemetry-python/blob/main/exporter/opentelemetry-exporter-jaeger-thrift/src/opentelemetry/exporter/jaeger/thrift/send.py#L99), seems like they're using the standard [apache thrift package](https://pypi.org/project/thrift/) too for Python

So it seems like there might be a decision on which package to use (and how to use it) for handling sending thrift over http for PHP, but the adapting of the conversion logic appears somewhat straightforward.

**Comment by tidal** [comment]
> * [Java's code](https://github.com/open-telemetry/opentelemetry-java/blob/e0854d6ac11cfe4c3794255d365b2272939674a4/exporters/jaeger-thrift/src/main/java/io/opentelemetry/exporter/jaeger/thrift/Adapter.java) for converting between OTLP and Jaeger's Thrift format looked reasonable enough to adapt from a first skim

Yes, besides the class being called "Adapter" when it's not an adapter, but something like a [Message Translator](https://www.enterpriseintegrationpatterns.com/patterns/messaging/MessageTranslator.html).


> * It does seem like they're relying on an [OpenTracing Jaeger client](https://mvnrepository.com/artifact/io.jaegertracing/jaeger-thrift) of some sort to handle actually transmitting data via Thrift to a Jaeger instance. Seems like [ jaeger-client-php](https://github.com/jonahgeorge/jaeger-client-php) could be the analog for PHP? Feels a little odd


Yes,  relying on something, which OpenTracing is effectively trying to replace, seems to be a bit odd. We could use the client (as an interim solution) and decouple it by using Adapter Pattern, but the implementation seems to be quite different, so I don't think it would be worth the effort. However, I think [these](https://github.com/jonahgeorge/jaeger-client-php/tree/master/src/Jaeger/Thrift) are all the classes generated by Thrift.





> * Can't quite grok Go or figure out where relevant code is yet, but I did notice [they mention](https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/jaeger#contributing) they have[ a copy of the Apache Thrift library](https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/jaeger/internal/third_party/thrift) in their source code. Seems like the [apache/thrift](https://packagist.org/packages/apache/thrift) package in PHP would be the analog?

Yes. Unfortunately the package comes with the code for all other languages as well, so it's a rather huge. However, once the package mirrors for our sub-packages are in place, we could provide a thrift package which just extracts the php code from the apache/thrift repo and replaces the other one. So you can just work with the original one for now, and we would add a "replace" statement when we have our package mirror.



> So it seems like there might be a decision on which package to use (and how to use it) for handling sending thrift over http for PHP, but the adapting of the conversion logic appears somewhat straightforward.

The apache/thrift package comes with an [HTTP Client](https://github.com/apache/thrift/blob/master/lib/php/lib/Transport/THttpClient.php), however I don't trust code, which [suppresses error messages](https://github.com/apache/thrift/blob/master/lib/php/lib/Transport/THttpClient.php#L172), plus we are using PSR HTTP Clients for the other exporters. I will create a PR in the next days, which uses a unified HTTP Client for all HTTP-Exporters and is based on [PHP-HTTP](https://docs.php-http.org/). You can take a look at the [plugins ](https://docs.php-http.org/en/latest/plugins/index.html) to get an idea.

**Comment by Grunet** [comment]
FWIW I think I'll break this up into several PRs just to keep them a little smaller and less daunting for me to tackle... so like the first one to create the span converter, then the next to do the thrift over http transmission, then the next to add protobug/grpc support (if needed), etc...

**Comment by tidal** [comment]
@Grunet 
Fair enough. Do you also want to tackle the generation of the thrift files? 
They should go into a thrift/jaeger sub-directory and I think we will not need all of the thrift files, so for example the agent one might not be needed?

**Comment by Grunet** [comment]
Here are the remaining things from the spec needed for converting from OTEL to Jaeger Thrift spans (assuming "dropped" things are still not needed right now per the confusion in #427)

- [Resource](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md#resource)
- [Error flag](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md#resource)
- Allowing for more than just string-valued tags (per the [Attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md#attributes) section)
- [Links](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md#links)

And then making an exporter for Thrift over Http should be the final thing

(The next step would be proto/gRPC support as the spec has several carve outs for it specifically, but it might be worth double checking how many other language libraries support this first, as the compliance matrix showed few if any iirc)

**Comment by Grunet** [comment]
FYI all the Thrift aspects of the spec have been implemented to this point to my knowledge.

I'm still working out what gRPC/proto support is for exactly and why many of the other languages don't seem to have it

**Comment by tidal** [comment]
@Grunet 
Thanks for all your work!
Closing this.

**Comment by Grunet** [comment]
Yup np. 

And just to wrap up the gRPC/protobuf conversation, re-reading the [Jaeger doc section](https://www.jaegertracing.io/docs/1.32/apis/#span-reporting-apis) on this and also the feature request for this in [the .NET library](https://github.com/open-telemetry/opentelemetry-dotnet/issues/2122), it seems like the use cases break down as follows

- Using a local Jaeger Agent
    - the Jaeger Agent handles sending all spans over the network to Jaeger Collector (via gRPC)
- Not using a local Jaeger Agent (and so need to send spans over the network directly from PHP)
    - Using HTTP for transmission to Jaeger Collector OR
    - Using gRPC for transmission to Jaeger Collector

Since in the 2nd case we (in theory, I still have yet to functional test it...) support direct sending of spans over the network with 1 protocol (HTTP) it seems like we should cover that use case (unless someone has to use gRPC/protobuf because HTTP/Thrift just won't work for them maybe?).

I guess if that happens they can always open up a new issue for that? From what I could tell the changes required would be maybe 3-fold

1) Make a new exporter that will emit protobuf over gRPC
2) Refactor the existing HttpSender + SpanConverter + (other files?) logic in some form to enable outputting in the jaeger protobuf IDL format instead of using the Thrift classes as is currently the case (mentioned in [this doc section](https://www.jaegertracing.io/docs/1.32/apis/#protobuf-via-grpc-stable) as well as at the beginning of the spec)
3) Make the few small adjustments where the spec explicitly calls out different handling for the protobuf case (you can search for "proto" in the spec and that should bring them up)

That might be about it though afaik. But I can leave that be for now until someone brings it up.
