### ISSUE TITLE
Implement Error Handling: Self-Diagnostics

### ISSUE THREAD

**Issue by jodeev** [open-telemetry/opentelemetry-php#298]
See the [Error Handling](https://github.com/open-telemetry/opentelemetry-specification/blob/418016dc4014f0c64acea74881774d34178bf15a/specification/error-handling.md#error-handling-in-opentelemetry) in the spec, [Self-Diagnostics](https://github.com/open-telemetry/opentelemetry-specification/blob/418016dc4014f0c64acea74881774d34178bf15a/specification/error-handling.md#self-diagnostics). 

All OpenTelemetry libraries -- the API, SDK, exporters, instrumentations, etc. -- are encouraged to expose self-troubleshooting metrics, spans, and other telemetry that can be easily enabled and filtered out by default.

Whenever the library suppresses an error that would otherwise have been exposed to the user, the library SHOULD log the error using language-specific conventions. SDKs MAY expose callbacks to allow end users to handle self-diagnostics separately from application code.

**Comment by tidal** [comment]
Related: https://github.com/open-telemetry/opentelemetry-php/pull/460#issuecomment-962429788

**Comment by kpratyus** [comment]
I have started looking into the possible implementations for this issue. I had a discussion with @tidal in the last sig and there were few suggestions on how we could proceed. So I would be glad if this issue could be assigned to me.
Thanks

**Comment by tidal** [comment]
@stale: 滚!

**Comment by bobstrecansky** [comment]
@kpratyus are you still planning on finishing this?

**Comment by bobstrecansky** [comment]
@brettmc mentioned looking at the [PSR](https://www.php-fig.org/psr/psr-14/) for this.

**Comment by brettmc** [comment]
I think this is now done - we report on errors now. We can emit more errors in future, probably based on beta release feedback.
