### ISSUE TITLE
Establish an initial Performance Benchmark for the PHP OpenTelemetry API

### ISSUE THREAD

**Issue by jodeev** [open-telemetry/opentelemetry-php#300]
We must be able to measure and report the performance of OpenTelemetry SDKs. The goal of this benchmark is to provide a tool to get the basic performance overhead of the OpenTelemetry SDK for given events throughput on the target platform.

We need to:
* provide a tool
* establish an initial benchmark per the spec, see [Performance Benchmark of OpenTelemetry API](https://github.com/open-telemetry/opentelemetry-specification/blob/418016dc4014f0c64acea74881774d34178bf15a/specification/performance-benchmark.md#performance-benchmark-of-opentelemetry-api).

**Comment by dkarlovi** [comment]
I suggest looking at https://phpbench.readthedocs.io/en/latest/

**Comment by bobstrecansky** [comment]
I think we should complete this after https://github.com/open-telemetry/opentelemetry-php/issues/382

cc;\\ @ohamuy

**Comment by MagePsycho** [comment]
Any update on this thread?
I am having a huge performance issue so wanna perform the performance benchmark.
