### ISSUE TITLE
Implement Environment Variables

### ISSUE THREAD

**Issue by jodeev** [open-telemetry/opentelemetry-php#302]
Implement Environment Variables per the spec, we should follow the naming convention as specified, see [OpenTelemetry Environment Variable Specification](https://github.com/open-telemetry/opentelemetry-specification/blob/418016dc4014f0c64acea74881774d34178bf15a/specification/sdk-environment-variables.md#opentelemetry-environment-variable-specification).

SDKs MAY choose to allow configuration via the environment variables in this specification, but are not required to. If they do, they SHOULD use the names listed in this document.

**Comment by brettmc** [comment]
Implemented in https://github.com/open-telemetry/opentelemetry-php/pull/469 - I think this issue can be closed.
