### ISSUE TITLE
Github action to generate new proto files

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#307]
We'd like to generate proto files with a github action.  This could be done as part of a release process or when we are alerted there is a new version of the protobuf definition.

**Comment by alexperez52** [comment]
Hi 👋,
Can I be assigned to this ?
@alolita

**Comment by bobstrecansky** [comment]
This issue should be closed; this is going to be done upstream, this issue was never updated accordingly.

**Comment by bobstrecansky** [comment]
@alexperez52 - happy to help you find another issue to work on if you'd like!  You should be able to take any of the ones in the [Tracing Project](https://github.com/open-telemetry/opentelemetry-php/projects/1)

**Comment by alexperez52** [comment]
@benagricola Awesome, thank you !
