### ISSUE TITLE
OTLP/GRPC exporter implementation - Links aren't implemented.

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#324]
We need to improve the `links` implementation in our SDK and add functionality for them to be used in our OTLP/GRPC exporter implementation.

**Comment by brettmc** [comment]
@bobstrecansky  - I think this has been resolved by https://github.com/open-telemetry/opentelemetry-php/pull/406 - I just tried it out and I can add links via SpanBuilder, export them and see them in jaeger.
