### ISSUE TITLE
OTLP/GRPC exporter implementation - Test improvements

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#326]
the OTLP / GRPC Exporter could use some more tests (either acceptance or mocking the Grpc Client)

**Comment by Grunet** [comment]
I would like to take a crack at this (to also help give me a better sense for the repo/library)

From just a code review (not looked at the coverage data yet) it seems like the case where the [gRPC call succeeds](https://github.com/open-telemetry/opentelemetry-php/blob/main/contrib/OtlpGrpc/Exporter.php#L150) may be untested. 

I may start with trying to get a test case mocking the TraceServiceClient working, then work on improving it to actually make the gRPC call (to a local endpoint?) instead

**Comment by bobstrecansky** [comment]
Thanks @Grunet - assigned to you.  Let us know if you have any questions!

**Comment by Grunet** [comment]
Oh this one can actually be closed. I think I made the PR and it was merged but at the time didn't know how to reference this issue so it would auto-close on-merge.

I made a note to follow up on it but never did...

**Comment by tidal** [comment]
@Grunet 
Ok, thanks for the info.
Closing.
