### ISSUE TITLE
A new release please

### ISSUE THREAD

**Issue by adhocore** [open-telemetry/opentelemetry-php#330]
It has been more than 6 months since the first-ever release - even that was a pre-release.
So I strongly believe a new version release is a long-standing issue. One for we don't want to use `dev-master` in production but rather fixed version constraint per semver.

Please consider it.

(I had to ping it before as well #166)

---
Edit: It seems like we want to do a release once everything is very stable and solid but that's what pre v1.0.0 are for (It is okay for v0.x to come with some breaking changes)

**Comment by prondubuisi** [comment]
Hello @adhocore, we are very close to a new release. You can keep track of what we have pending to get [there](https://github.com/open-telemetry/opentelemetry-php/milestone/2).

**Comment by frazjp65** [comment]
Do we know when this will be out of alpha?

**Comment by bobstrecansky** [comment]
A new release has been published:
https://github.com/open-telemetry/opentelemetry-php/releases/tag/0.0.2

We aren't yet certain when we'll be out of alpha.  We have a bunch of open issues that need to get finished before we can cut a beta release.
