### ISSUE TITLE
OTLP HTTP support

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#347]
We'd like to implement OTLP http support to follow the OTLP protocol.

cc:\ @SeanHood, as he mentioned he'd like to work on this.

**Comment by SeanHood** [comment]
I'll have a go at this one

**Comment by bobstrecansky** [comment]
@SeanHood I think this can be closed?

**Comment by SeanHood** [comment]
Yes, thanks!
