### ISSUE TITLE
API as decoupled dependency

### ISSUE THREAD

**Issue by Nevay** [open-telemetry/opentelemetry-php#356]
The current separation between API and SDK (currently /api=API+SDK interfaces, /sdk=implementation) does not match the [design specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/library-guidelines.md#opentelemetry-client-generic-design), which describes the API package as a decoupled and self-sufficient dependency.

I went over the API specification for context and tracing (+ Java API interfaces for naming) to put a basic API package together (https://github.com/Nevay/opentelemetry-api-example). Would you be interested in having this merged, either to this repo or to a separate API repo?

Some notes / thoughts:
- SpanBuilder: the SpanBuilder (currently SpanOptions) abstraction seems to be mandatory due to the `::addLink()` method (["The Span creation API MUST provide: An API to record a single Link where the Link properties are passed as arguments."](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#specifying-links))
- Attributes: the Attributes abstraction feels too restrictive on instrumentation side / it added a `new Attribute($attributes)` on every call expecting attributes. I would restrict the Attributes abstraction to the SDK (and read-only as required for ReadableSpan?)
- Global context: I would opt for injecting a context storage to avoid relying on global state, applications can provide a global context storage in their framework-specific way (e.g. via DI-Container)

**Comment by bobstrecansky** [comment]
@Nevay - this sounds like a great thing to bring up on our weekly SIG meeting.  I'll be sure to add it to the agenda.

**Comment by alolita** [comment]
This should be clarified in the spec because this is a language dependent.

**Comment by bobstrecansky** [comment]
We brought this up in the Maintainers meeting today, I'll be working on an OTEP to update the spec accordingly.

**Comment by bobstrecansky** [comment]
@alolita and I are still working through this; stay tuned!

**Comment by dkarlovi** [comment]
Note, this doesn't need to be a separate repo to be a separate package. I'd suggest keeping it in the same repo to ease maintenance.

**Comment by bobstrecansky** [comment]
There is not a way to install only the API package today.  This is not currently on our roadmap.
