### ISSUE TITLE
Adding AWS X-Ray Support to the OpenTelemetry PHP Library

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-php#360]
*Is your feature request related to a problem?*
The OpenTelemetry (OTEL) PHP repository currently has no support for integration with AWS X-Ray. OTEL users are not able to use it’s efficient trace ingestion and exporting with X-Ray as a back end using the OTEL PHP library (API and SDK). The use of OTEL with AWS X-Ray provides developers an efficient method of tracking traces through their application, providing insight into requests and their paths in order to improve performance or pinpoint failures. X-Ray is particularly desirable for its ease of integration with other AWS services such as EC2, ECS, and EKS. 

*Describe the solution you'd like.*
Adding the following components would enable full OTEL integration with AWS X-Ray: 

* ID Generator
* Propagator
* Translating Captured Language-Specific Errors & Exceptions to AWS X-Ray Format
* Detectors
    * ECS
    * EC2
    * EKS
    * Lambda

*Describe alternatives you've considered.*
There exist no alternatives to this, implementation to support AWS X-Ray is necessary to use OTEL PHP SDK with AWS X-Ray.

**Comment by alolita** [comment]
@bobstrecansky please assign @ohamuy to this project. Many thanks!

**Comment by bobstrecansky** [comment]
Done, thanks @alolita!

**Comment by ohamuy** [comment]
This has been implemented in the contrib repository. Please visit there for more information
