### ISSUE TITLE
How can I send span data to Otel-collector

### ISSUE THREAD

**Issue by tydhot** [open-telemetry/opentelemetry-php#362]
I found that collector already have jaeger receiver new, can Otel-php just send span data to it now? If it can be done, which uri  should I write in code?
If it can't be, is there any other way to send span to collector?

**Comment by bobstrecansky** [comment]
@tydhot - I'm sorry, I completely missed this issue.

You should be able to use our examples to understand how to send data to the collector.

The [Makefile collector](https://github.com/open-telemetry/opentelemetry-php/blob/main/Makefile#L26-L29) command sends to a collector.

You should be able to run a `make collector` command (after you've run a `make install`) to be able to send some test examples to your collector.  Please let me know if you need additional assistance!

**Comment by tydhot** [comment]
@bobstrecansky Thank you for your reply:). I have found SkyWalking have a project https://github.com/SkyAPM/SkyAPM-php-sdk. It seemed that it can auto instrument php app lately. I think it is awesome. Do we have any plan to create a php sdk like that? It would be very helpful I think.

**Comment by bobstrecansky** [comment]
@tydhot - nothing on the roadmap for auto instrumentation yet.  If you would to open an issue for this, we can prioritize it accordingly

**Comment by tydhot** [comment]
@bobstrecansky ok I got it. I think auto instrumentation is an exciting feature for otel php user.

**Comment by bobstrecansky** [comment]
Closing this, as we have an issue directly for auto instrumentation here: https://github.com/open-telemetry/opentelemetry-php/issues/402
