### ISSUE TITLE
Tracer - remove tracer-scoped "active" span API in favor of global, context-scoped spans

### ISSUE THREAD

**Issue by Nevay** [open-telemetry/opentelemetry-php#363]
**Is your feature request related to a problem?**
Some of the current tracer API is centered around tracer-scoped active spans. These methods seem to predate the addition of the global context propagation, the global context should be used instead (as already done for `::startSpan()` in #264).

**Describe the solution you'd like**
Tracer-scoped spans should be replaced with usage of global, context-scoped spans:
- `::finishSpan()` & `::deactivateActiveSpan()` are neither used nor implemented
- `::getActiveSpan()` can be replaced by `Span::getCurrent()`
- `::endActiveSpan()` can be replaced by `Span::getCurrent()->end()`
- `::setActiveSpan()` can be replaced by `Span::setCurrent()`
- `::startAndActivateSpan()` can be replaced by `::startSpan()` followed by `Span::setCurrent()`

**Comment by bobstrecansky** [comment]
@Nevay - I think this can be closed?
