### ISSUE TITLE
exporter: metadataFromHeaders doesn't parse metadata from headers

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-php#366]
**Describe your environment** 
The behaviour should be the same in all environments.

**Steps to reproduce**
I tried passing the following grpc metadata `"key=value"` through the `OTEL_EXPORTER_OTLP_HEADERS` env var.

**What is the expected behavior?**
`metadataFromHeaders` should return an array of key-value pairs

**What is the actual behavior?**
`metadataFromHeaders` returns an empty array

**Additional context**
I believe the problems is that this code checks for a key that doesn't exist:
https://github.com/open-telemetry/opentelemetry-php/blob/d908922a790ca6cdd9b124ead61b6b8958a4810a/contrib/OtlpGrpc/Exporter.php#L182

**Comment by SeanHood** [comment]
I wrote this bug, thanks for the fix. I've since fixed this function in the OTLP/HTTP Exporter too: https://github.com/open-telemetry/opentelemetry-php/pull/352/files#diff-7647e46a46d56d0305529c854be2ed3e426753de16771166d2244f2b9a16405aR186-R204

**Comment by bobstrecansky** [comment]
This fix has been merged.
