### ISSUE TITLE
Full otel example

### ISSUE THREAD

**Issue by hrodic** [open-telemetry/opentelemetry-php#382]
**Is your feature request related to a problem?**
What is the recommended way to propagate trace between 2 distributed applications?

**Describe the solution you'd like**
I would like to have a full example (if possible docker-composed)  in examples/ folder that does something like this
1. service 1 trace starting and generation of spans
2. service 1 injects trace context to the headers and sends request to service 2
3. service 2 receives headers and extracts them to trace continuing it and adding more spans.
4. service 2 finishes
5. service 1 finishes
6. backend could be a otel-collector with debug active so you can see the trace (spans) coming in.

**Describe alternatives you've considered**
Using Guzzle, for example.

**Additional context**
This will help a lot of people testing this library and giving more feedback.

**Comment by bobstrecansky** [comment]
@ohamuy is planning on working on a full fledged AWS example, I'm going to tag him on this.

**Comment by ohamuy** [comment]
Hello @hrodic! I have implemented two example applications in the contributor repo. There is a README for all the necessary installations. These examples should work with other backends as well if you would want to use something alternative to AWS X-Ray

**Comment by ohamuy** [comment]
I hope it is sufficient for your request! In the future there should be more robust examples with actual web applications coming out

**Comment by brettmc** [comment]
@hrodic - there is an example now that covers your request. Please check it out, feedback welcome. Can this issue be closed now?

**Comment by brettmc** [comment]
Closing due to no feedback, I think the issue has been fixed now.
