### ISSUE TITLE
Alpha 0.2 Release Candidate

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#4]
The spirit of this release is to have a demo-able product that anybody can start playing with and start implementing instrumentation adaptors and data collectors for various scenarios.

**Comment by bobstrecansky** [comment]
@c24t mentioned to me - We are planning to release versions of the library for each of these milestones, but that's mostly as an exercise to keep the clients in sync as we develop them. The only people that are likely to use pre-GA clients are other developers -- and they're probably happy to build from source.  This ticket is essentially a placeholder for the release for context and ceremony.

**Comment by lizthegrey** [comment]
How close are you to 0.1 even if not 0.2? We need to know to update the OpenTelemetry website so y'all can look good onstage on Tuesday. cc @austinlparker

**Comment by lizthegrey** [comment]
How close are you to 0.1 even if not 0.2? We need to know to update the OpenTelemetry website so y'all can look good onstage on Tuesday. cc @austinlparker

**Comment by austinlparker** [comment]
The website milestones are generated from GitHub data (see https://github.com/open-telemetry/community/issues/201), please update the milestones in this repo accordingly and ping me on this thread and I can force a website refresh.

**Comment by bobstrecansky** [comment]
@lizthegrey - We are still a bit away from a 0.1 - the API is implemented, but we still could use a lot of participation.  We have had very little community involvement so far.

**Comment by bobstrecansky** [comment]
@austinlparker - I've updated the milestones! Thanks for the insight.

**Comment by bobstrecansky** [comment]
Closing this because we are going to eventually skip more towards a more recent alpha release.
