### ISSUE TITLE
Do we have any plan about auto instrumentation?

### ISSUE THREAD

**Issue by tydhot** [open-telemetry/opentelemetry-php#402]
I have found a project lately: https://github.com/SkyAPM/SkyAPM-php-sdk. It support auto instrument for php app. I think if we can support the auto instrumentation,  it will be an exciting feature for otel php user too.  Do we have any plan about this?

**Comment by bobstrecansky** [comment]
There is not currently a plan for auto-instrumentation.  Would love to hear suggestions / implementations if you have them!

**Comment by Grunet** [comment]
More of an experience report, but I had a chance to try out OTEL auto instrumentation for a simple (Node) Express server during a recent workshop (and it was super cool!), and from what I could tell the [npm package](https://www.npmjs.com/package/opentelemetry-instrumentation-express) being used specifically to instrument Express was doing some form of "monkey patching" of Express's methods (I think maybe hooking into Node's module require system iirc) to layer on the instrumentation from the core Node/JS OTEL library.

I'd be very curious if a pattern like that would be viable for PHP. Like say every framework/library got their own package on top of OTEL-PHP that would then monkey-patch (via reflection?) it the first time it gets used (maybe by adjusting autoloaders or similar?). I'm still new to PHP so I have no idea if that could even be possible...

**Comment by haad** [comment]
Hmm so what would be actual way how we can add auto tracers to quite simple sympfony based php application.

Is it even possible without extension and can it work without any library changes ?

**Comment by tidal** [comment]
@haad
In case of Symfony that's fairly easy and doesn't need any extension or changes to the library.
First off Symfoyn exposes life-cyle events, which are easy to hook into.
You can find an example here:
https://github.com/opentelemetry-php/otel-sdk-bundle-example-sf5/blob/main/src/EventSubscriber/OtelKernelSubscriber.php

But even without events it's possible to create decoraters for all types of "services" in Symfony in a bundle configuration and/or with compiler passes.

All of above is what should be implemented in the Symfony InstrumentationBundle: https://github.com/open-telemetry/opentelemetry-php/issues/568
