### ISSUE TITLE
Getting a Gitpod Workspace Setup for the Repo Takes ~20 Minutes

### ISSUE THREAD

**Issue by Grunet** [open-telemetry/opentelemetry-php#414]
Before opening a feature request against this repo, consider whether the feature should/could be implemented in the [other OpenTelemetry client libraries](https://github.com/open-telemetry). If so, please [open an issue in opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/issues/new) first.

**Is your feature request related to a problem?**
When I open this repo in Gitpod and run "make install", it takes ~20 minutes to finish

**Describe the solution you'd like**
If it could finish in a minute or 2 that'd be really nice.

**Describe alternatives you've considered**
I noticed that commenting out [the step in the Dockerfile](https://github.com/open-telemetry/opentelemetry-php/blob/4dc072524e026e3e450ec016b46d3415b49f4ee3/docker/Dockerfile#L15) that seems to be causing most of the slowness (around installing gRPC as a PHP extension) and also removing it's [associated line in composer.json](https://github.com/open-telemetry/opentelemetry-php/blob/main/composer.json#L9) drops the "make install" time down to 1-2 minutes

But then (perhaps unsurprisingly) some of the tests start to give warnings/errors., specifically for ExporterFactory and OtlpGrpcExporter. 

**Additional context**
This isn't a major roadblock for me personally rn, but wanted to get it documented in case any future folk using a cloud ephemeral dev environment run across it

**Comment by Grunet** [comment]
Verified it now takes ~1 minute (!!!) after the changes from #420 and/or #421 (not exactly sure which)

**Comment by bobstrecansky** [comment]
This was fixed with both #420 and #421 !
