### ISSUE TITLE
Move website_docs back to website repo? (Decide by Oct 1)

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry-php#423]
As discussed at the [Sept 9 Comms][cm] and [Sept 13 Maintainers][mm] meetings, @open-telemetry/php-maintainers have a choice to make regarding **how your docs** ([website_docs]) will be incorporated into **[opentelemetry.io]**.

For your **two choices** and other details, see https://github.com/open-telemetry/opentelemetry.io/issues/730. 

The Comms team can help implement either of these choices. We'd appreciate a **response by Oct 1**, after which we'll **assume** that you're ok with option (2) and initiate the **move  of [website_docs] back to [website repo][wr]**.

/cc @austinlparker

[website_docs]: https://github.com/open-telemetry/opentelemetry-php/tree/main/website_docs
[opentelemetry.io]: https://opentelemetry.io/
[cm]: https://docs.google.com/document/d/1wW0jLldwXN8Nptq2xmgETGbGn9eWP8fitvD5njM-xZY/edit#heading=h.brwue8g3voai
[mm]: https://docs.google.com/document/d/14lBtLAdzsV7M8xQNdhTJ0d2PxM1R7FByw-GttKJzVVw/edit#heading=h.vannhusrul2x
[wr]: https://github.com/open-telemetry/opentelemetry.io/

**Comment by bobstrecansky** [comment]
I'd love to keep the docs in `/websites_docs` rather than have them be in the opentelemetry.io repo.

**Comment by chalin** [comment]
Ok, I'll set it up as a submodule then.

**Comment by chalin** [comment]
Here's an invitation to reconsider your decision: https://github.com/open-telemetry/opentelemetry-php/issues/405#issuecomment-1041579478. If you agree, please reopen this issue @bobstrecansky. Thanks.

**Comment by bobstrecansky** [comment]
@chalin - I guess I'm not certain of the severity or timeline for this change.  If moving this to the opentelemetry.io repo will reduce friction for you, I'm happy to do so; we were just given the option earlier.

**Comment by chalin** [comment]
> ... If moving this to the opentelemetry.io repo will reduce friction

Yes, very much so!

> I'm happy to do so

Wonderful, @cartermp and I gladly accept your offer then! Could you please reopen this issue and assign it to me? I'll be moving the PHP docs over shortly.
