### ISSUE TITLE
PHP organization/naming pass

### ISSUE THREAD

**Issue by Blacksmoke16** [open-telemetry/opentelemetry-php#425]
Currently all of the source PHP code lives within their own folders in the root directory. From what I remember talking with @bobstrecansky is that this was just how the original creator of the lib set it up, and not some OTLP requirement.

Related to this, the API is defined under the `OpenTelemetry\Trace` namespace and are using names like `Span` for interfaces.

Because we are still in a pre-alpha state, I propose to makes some changes before it becomes impossible due to needing to maintain backwards compatibility.

These suggestions include:

* Follow https://www.php-fig.org/bylaws/psr-naming-conventions/
  * E.g. `Span` => `SpanInterface`
* Follow https://wiki.php.net/rfc/class-naming
* Redo the directory structure to have all source code under `src`. Something like:

```txt
.
├── src
│   ├── API
│   ├── Context
│   ├── Proto
│   └── SDK
└── tests
    ├── API
    ├── Context
    └── SDK
```
* Update the namespaces of the types to match the directory structure

_Originally posted by @Blacksmoke16 in https://github.com/open-telemetry/opentelemetry-php/pull/422#discussion_r712628145_

**Comment by bobstrecansky** [comment]
I'm happy for you to follow the PHP FIG conventions and class naming conventions.  This might be a large effort but if you feel that it's worth it, I'm happy to endorse it.

**Comment by Blacksmoke16** [comment]
@bobstrecansky Great! I don't actually think it'll be _too_ bad. PHPStorm's refactoring features should handle a lot of the work. I'll give it a go and see how it plays out.

**Comment by bobstrecansky** [comment]
PHPStorm is the hero we all need 🍡
