### ISSUE TITLE
Release baggage implementation

### ISSUE THREAD

**Issue by markvdlaan93** [open-telemetry/opentelemetry-php#443]
I see that the baggage implementation is on master. Is there already known when the baggage implementation will be released? https://github.com/open-telemetry/opentelemetry-php/commit/1109aa5628700a3ccaed9c3956eb025c12f3d757

**Comment by bobstrecansky** [comment]
@markvdlaan93 - we will be sure to cut a release soon.  Note that this is still alpha software, but we would be happy to receive feedback!
