### ISSUE TITLE
Support `schemaUrl`

### ISSUE THREAD

**Issue by Blacksmoke16** [open-telemetry/opentelemetry-php#445]
See https://github.com/open-telemetry/opentelemetry-specification/blob/v1.7.0/specification/trace/api.md#get-a-tracer and https://github.com/open-telemetry/oteps/blob/main/text/0152-telemetry-schemas.md.

_Originally posted by @Blacksmoke16 in https://github.com/open-telemetry/opentelemetry-php/pull/439#discussion_r723821913_

**Comment by tidal** [comment]
What kind of schema is this actually referring to? I could not find any answer to that in the spec or docs (or I'm blind).

**Comment by Blacksmoke16** [comment]
@tidal Mm yea, the spec doesn't make it super obvious what it is :/ I updated the OP to include some more context.

**Comment by tidal** [comment]
Since semantic conventions landed in https://github.com/open-telemetry/opentelemetry-php/pull/502, the respective constants can be used to implement this feature.

**Comment by brettmc** [comment]
It looks like this is partially addressed in #537

**Comment by tidal** [comment]
@stale
真的吗？

**Comment by yuktea** [comment]
#537, #607 and #627 have addressed parts of this PR. Can someone confirm if the issue should be closed or give some context if we still have something to cover?
