### ISSUE TITLE
Optimize `baggage` header parsing logic

### ISSUE THREAD

**Issue by Blacksmoke16** [open-telemetry/opentelemetry-php#447]
Current implementation works, but could be updated to be more performant/efficient.

_Originally posted by @bobstrecansky in https://github.com/open-telemetry/opentelemetry-php/pull/437#discussion_r721869389_

**Comment by tidal** [comment]
@stale
移动！

**Comment by amber0612** [comment]
Hi @bobstrecansky, I would like to work on this one incase you have less bandwidth

**Comment by brettmc** [comment]
hi @amber0612 do you still want this one?

**Comment by amber0612** [comment]
> hi @amber0612 do you still want this one?

Sure @brettmc

**Comment by brettmc** [comment]
I ran some benchmarks against baggage parsing, it's very fast (~2us per execution when run 10k times) and I couldn't see much room for improvement.
It looks like the original implementation was based on Java's, and I think our code is easier to read: https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/baggage/propagation/Parser.java#L45
