### ISSUE TITLE
Library has a dependency on PSR7/PSR17 interfaces - Exporter factory methods have a dependency on an concrete implementation (Guzzle)

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#448]
**Describe your environment** 
This bug occures in the 0.0.3 release as well as in current dev-main

**Steps to reproduce**
Run:
`composer require open-telemetry/opentelemetry nyholm/psr7 kriswallsmith/buzz`
Code:
`$factory = new OpenTelemetry\Sdk\Trace\ExporterFactory('foo)');`
`$exporter = $factory->fromConnectionString('jaeger+http://localhost:9412/api/v2/spans');`
or 
`$exporter = OpenTelemetry\Contrib\Jaeger\Exporter::fromConnectionString('http://localhost:9412/api/v2/spans');`
or trying to create other exporters using a PSR7 client in the same way.

**What is the expected behavior?**
An instance of an Exporter should be created

**What is the actual behavior?**
`PHP Fatal error:  Uncaught Error: Class "GuzzleHttp\Psr7\HttpFactory" not found`

**Additional context**
This issues can be fixed by using the [php-http/discovery](https://github.com/php-http/discovery) composer package.
The resulting code would look something like this:
```
[...]
$exporter = new JaegerExporter(
    'foo',
    'jaeger+http://localhost:9412/api/v2/spans',
    HttpClientDiscovery::find(),
    Psr17FactoryDiscovery::findRequestFactory(),
    Psr17FactoryDiscovery::findStreamFactory(),
);
```

**Comment by Blacksmoke16** [comment]
Related: https://github.com/open-telemetry/opentelemetry-php/issues/296.

Jaeger exporter needs extracted into its own type, versus relying on Zipkin.

**Comment by tidal** [comment]
@Blacksmoke16 
You might want to take a look at https://github.com/open-telemetry/opentelemetry-php/issues/451 where I outlined some of the issues with the factory. I'd appreciate your feedback/ideas.

**Comment by tidal** [comment]
Also it might be a good idea to create a dedicated http client/wrapper as suggested in https://github.com/open-telemetry/opentelemetry-php/issues/223 to only have one dependency in the http based exporters. 
[PHP-HTTP](https://docs.php-http.org/en/latest/) would come in handy in that case. It's kind of a defacto standard (sits on top of PSR7 and was the base for PSR18) and allows for plugins like caching etc. (Caching doesn't make much sense for exporters, but for example the AWS detectors make HTTP calls as well, while the response will be always the same.)

**Comment by tidal** [comment]
I will start to work on this issue, as well as on the related issues regarding the factory/factories and http transport (https://github.com/open-telemetry/opentelemetry-php/issues/452, https://github.com/open-telemetry/opentelemetry-php/issues/451) . I will try to create small PRs (starting with the bugs), so we later can maybe have a discussion on more opinionated things. For example, I have created a exporter factory for the Symfony bundle (just to get things done) which may or may not could be reused (but I'm not married to that solution at all). 

@SeanHood  Are you still working on https://github.com/open-telemetry/opentelemetry-php/issues/383? Or specifically the options implementation you outlined, as I think there could be some overlapping parts, and I want to avoid us both working on (possibly) conflicting implementations.

**Comment by SeanHood** [comment]
@tidal I haven't touched it in a while, the rabbit hole got deep. I have pushed the WIP: https://github.com/open-telemetry/opentelemetry-php/compare/main...SeanHood:otlp-config-opts

**Comment by tidal** [comment]
@SeanHood
Thanks, I will have a look and ponder a bit on what might be a good solution to have a unified approach for all exporters.
