### ISSUE TITLE
Exporter factory, factory methods and creation could use some rework/cleanup

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#451]
**Is your request related to a problem?**

At the moment the creation of span exporters (especially through the factory methods and the factory) class is inconsistent in behavior and in some scenarios broken. However in downstream instrumentations (for example Symfony Bundle) a generic way to instantiate exporters is needed to allow configuration.

1. ~~"fromConnectionString" factory methods in [Jaeger](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/Contrib/Jaeger/Exporter.php#L14), [Newrelic](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/Contrib/Newrelic/Exporter.php#L170), [OtlpHttp](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/Contrib/OtlpHttp/Exporter.php#L221), [Zipkin ](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/Contrib/Zipkin/Exporter.php#L134)and [ZipkinToNewrelic ](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/Contrib/ZipkinToNewrelic/Exporter.php#L158) exporters have a dependency on Guzzle library and will fail if other PSR7 implementations are used. see: [448](https://github.com/open-telemetry/opentelemetry-php/issues/)~~
2. "fromConnectionString" factory method in [OtlpGrpc ](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/Contrib/ZipkinToNewrelic/Exporter.php#L158) and [OtlpHttp](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/Contrib/OtlpHttp/Exporter.php#L221) exporters silently drop the passed "$endpointUrl" argument without using it and/or raising an error,
3.  [OtlpHttp](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/Contrib/OtlpHttp/Exporter.php#L83) exporter provides no way of configuring the endpoint (and a bunch of other options) programmatically, the only way is to provide a env var or using the default.
4.  "fromConnectionString" signature in [SpanExporterInterface](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Trace/SpanExporterInterface.php#L19) defines a "$name" parameter which is not needed in all exporters . (However the "$name" parameter refers to the service name which is a [required  resource attribute](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Resource/ResourceConstants.php#L20)
5. [ExporterFactory ](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Trace/ExporterFactory.php#L16)requires a "$name" constructor argument, which is not required by all exporters (see above)
6. "fromConnectionString" method  in [SpanExporterInterface](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Trace/SpanExporterInterface.php#L19) defines an untyped "$args" parameter, which suggests an array/list, but is only ever used a a string to pass the license key to [Newrelic](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/Contrib/Newrelic/Exporter.php#L170) and [ZipkinToNewrelic ](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/Contrib/ZipkinToNewrelic/Exporter.php#L158) exporters
7.  [SpanExporterInterface](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Trace/SpanExporterInterface.php#L19) requires all implementations to provide a "fromConnectionString" method, while future or custom implementations (for example for testing/debugging. see: [442](https://github.com/open-telemetry/opentelemetry-php/pull/442)) might not need a dsn/url at all. However [ExporterFactory](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Trace/ExporterFactory.php#L33) 's "fromConnectionString" requires a dsn/url to be provided.
8. [ExporterFactory](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Trace/ExporterFactory.php#L55) resolves the exporter to be created by an hard coded switch statement, which makes it hard to maintain. The only way to add custom exporters for users is to extend the factory class and override the entire "fromConnectionString" method. This violates Open/Closed Principle.
9. Exporter implementations have very different needs in terms of configuration. To provide an abstraction for the creation of exporters, there should be a way to instantiate an exporter from a set/array of options/parameters.
10. ~~The different exporter implementations have a lot of duplicate code.~~

**Describe the solution you'd like**

1.  see: [448](https://github.com/open-telemetry/opentelemetry-php/issues/)
2.  Pass "$endpointUrl" argument to constructor
3.  Make "$endpointUrl" an constructor parameter other options could be provided as an array in the constructor or get setters.
4. This is not too much of an issue, however maybe the "$name" paramter could be optional in the interface and/or the factory class could take the resource info as an optional(?) parameter and pull the service name from there (if given). The "fromConnectionString" could be put into a separate Interface which is only implemented by exporters which take/need the given parameters, this would also better respect Interface Segregation Principle.
5. See: 4.
6. The "$args" argument should be either an array or  expect a http query string.
7. The Factory class should only require the contrib name to be given. It should be theresponsibilty of the exporter implementation to check and validate a DSN/URL (if needed). 
8. The factory class should have some sort of registry or use a dedicated registry class for that purpose. This would make it easier to extend the list of exporter, especially for users of the SDK.
9. Exporters should provide a "fromOptions"/"fromArray" method or a  dedicated factory, which takes care of that. 
10. Duplicate code / behavior should be provided by [traits](https://www.php.net/manual/en/language.oop5.traits.php), to make the exporters easier maintainable and avoid inheritance.

**Describe alternatives you've considered**

For the [Symfony Bundle](https://github.com/open-telemetry/opentelemetry-php/issues/220) (and other instrumentations in the future) a consistent and reliable generic way to instantiate exporters is a must. I could solve most/all of above issues (which are relevant in this regard) in the Symfony Bundle (or opentelemetry-php-contrib). However I think it's better to tackle these issues in the SDK itself, than in downstream instrumentations.

**Additional context**

Since a lot of the issues above are sort of a blocker for me to finish the initial version of the Symfony Bundle, I would like to work on a fix. However before providing a PR, I would like to get some feeback and provide some examples of possible solutions. 

_**What do you think about the issues I outlined or do you think some are no issues at all? 
What do you think about the possible solutions?**_

To not reinvent the wheel, Point 9. could be solved by leveraging the standalone [Symfony OptionsResolver Component](https://symfony.com/doc/current/components/options_resolver.html) (or something similar). It provides a way for defining, validating, normalizing options and to provide defaults. However for the sake of the Dependency Inversion Principle I would be kind of hesitant to make the exporters directly depend on a third party library. So there should be an adapter and/or a dedicated factory which takes care of it. 

I created a working example of how such factory could look like for the Newrelic exporter. (In real implementations a lot of duplicate code for the exporter factories could be extracted out into traits. See 10.):
https://github.com/tidal/opentelemetry-php/blob/exporter_factory-options_resolver/src/Contrib/Newrelic/Factory.php

Because some (or all) exporters may not need a dedicated factory, I thought of a more generic kind of factory. This working example of e generic factory takes the fully qualified class name of an exporter as a constructor argument. It validates the class to implement SpanExporterInterface and configures the options by inspecting the class constructor via reflection.:
https://github.com/tidal/opentelemetry-php/blob/exporter_factory-options_resolver/src/SDK/Trace/GenericExporterFactory.php

You can see usage examples for both factories in the code comments.
I have no firm opinion on what might be a better solution if not both. They both have their pros and cons.

Those dedicated or generic factories could be used by the overall composite exporter factory to offload exporter creation to them. There is basically just some sort of mapping or registry needed (see 8.)
In addition to or as a replacement of the "fromConnectionString" in the composite factory a "fromOptions"/"fromArray" method could be added.

**Comment by tidal** [comment]
@Grunet 
I'm relaltively new to the repo  as well, though I gave the package a try some months ago.

These are just some things which popped up while figuring out a way to [provide configuration ](https://github.com/tidal/otel-apiplatform-example/blob/config-draft/api/config/packages/open_telemetry.yaml) for the SDK in the Symfony Bundle and wiring up the individual parts, so I ent through a lit of possible scenarios to be at least aware of the.

Regarding breaking changes. The only thing that may break something would be changing the signature of the "fromConnectionString" methods. As far as I have seen neither these factory methods nor the factory itself are parts of the spec. Only the factory uses these methods as for now, and the sf bundle would be the first package to use the factory.
As for now packagist only lists 2 packages depending on the SDK package. Ones seems to be not existing (URL leads to a 404), the other one is the Laravel package, which doesn't use the factory (methods).:
https://packagist.org/packages/open-telemetry/opentelemetry/dependents?order_by=downloads

**Comment by brettmc** [comment]
Closing, as I believe all of the issues originally identified have been resolved or are no longer relevant due to refactoring which has taken place over the past 12 months.
