### ISSUE TITLE
OtlpHttp Export: Duplication of error handling in export function

### ISSUE THREAD

**Issue by SeanHood** [open-telemetry/opentelemetry-php#458]
Noticed this recently, I think the `catch` will be used in reality but currently I think the tests are using the `if` statements.

Tests would need a refactor, but I think maybe it's best to drop the two `if` statements.

https://github.com/open-telemetry/opentelemetry-php/blob/08916531be23c6d1334cef5209403f8d4d59ce22/src/Contrib/OtlpHttp/Exporter.php#L162-L166

https://github.com/open-telemetry/opentelemetry-php/blob/08916531be23c6d1334cef5209403f8d4d59ce22/src/Contrib/OtlpHttp/Exporter.php#L168-L174

**Comment by bobstrecansky** [comment]
This makes sense to me.

**Comment by brettmc** [comment]
This exporter was refactored a little while back, and the http exporting logic was moved into a trait, `HttpSpanExporterTrait`. The try/catch has been updated during that refactor, but the if/then referred to here [is still there](https://github.com/open-telemetry/opentelemetry-php/blob/56cf2db1412198541773c8d0381961f111d907da/src/SDK/Trace/Behavior/HttpSpanExporterTrait.php#L56).
I think the logic is valid - it's up to the http client whether it throws an exception or not - e.g guzzle will by default, but can be configured to [not throw exceptions for 4xx errors](https://docs.guzzlephp.org/en/stable/quickstart.html#exceptions), which I think is what this logic was designed to cater for.
So, I think the logic is correct as is.

**Comment by bobstrecansky** [comment]
Sounds good; let's close this issue.
