### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#481]
The readme is a bit out of sync with latest development and could use some polishing as well.

- [X] Current requirements to install the library should be documented.
- Maybe add a short documentation of additional (or all) make targets.
- There is a lot of redundancy, which does not really help readability.

**Comment by tidal** [comment]
@stale
jehwoandersmakiern!

**Comment by yuktea** [comment]
@tidal I'll work on this 🙂
