### ISSUE TITLE
Proposal: Make gRPC PHP  extension optional

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#482]
Proposed change: 
- Move grpc-ext to dev requirements in composer.json
- Add a suggest entry for grpc-ext in composer.json
- Document in README (and docs). see: https://github.com/open-telemetry/opentelemetry-php/issues/481

Reasons for the proposal:
- The gRPC extension is not a dependency of the API or the SDK, but only one contrib exporter (atm).
- Compiling the extension can takes up to 10-20 minutes (Yes, this can be cached in container layers etc, but it can still be an issue in cascading build systems and other places)
- The binary of the gRPC extension can be as large as 100mb. That's not huge, it's massive.! (On my local system the binary was 101mb after compiling for PHP8. All other extension are around 1mb. Only swoole is 30mb, but it does a few more things than gRPC. Yes, the size of the binary can be reduced, [see this thread](https://github.com/grpc/grpc/issues/23626), but I don't think users should be expected to dig through github issues)
- A lot of providers and systems (Heroku or OpenShift's S2I for PHP for example), etc. still regard the grpc extension
 as kind of 'exotic', or in other words the extension is not (or cannot be) installed.
- Because of the above issues, there will propbably be Ops people, who will refuse or be reluctant to install the extension, when it's not really needed. (I have asked some), and thus the whole SDK cannot be used.

I am not aware, why the gRPC extension is a standard requirement atm, so there might be something I'm missing here.

**Comment by brettmc** [comment]
I assumed this would go ahead, and so made http+protobuf the default in #488
