### ISSUE TITLE
packagist auto-update

### ISSUE THREAD

**Issue by brettmc** [open-telemetry/opentelemetry-php#484]
`dev-main` on packagist.org is dated 11-Nov - is there an automated process to update packages?
eg, see https://packagist.org/about#how-to-update-packages

**Comment by bobstrecansky** [comment]
I'm not sure about this but I'd also be curious to know.

**Comment by brettmc** [comment]
There is a note on the [packagist page](https://packagist.org/packages/open-telemetry/opentelemetry) that `This package is *not* auto-updated` - I think that a maintainer would need to set this up (@nekufa is listed as the maintainer in packagist, perhaps one to discuss in SIG this week)

**Comment by nekufa** [comment]
Greet, glad to hear you are on the go to the release.
I can't configure autoupdate due my github repository permissions.
So, I've added @bobstrecansky as maintainer, and now anyone else can be added by Bob.

Hope this should be enough.
If i can help anything else - feel free to contact me.

**Comment by tidal** [comment]
@bobstrecansky 
Can the [packagist application](https://github.com/settings/connections/applications/a059f127e1c09c04aa5a) be added to the repo/org? 
Otherwise we probably need to call packgist from CI to update.

**Comment by bobstrecansky** [comment]
I've made a request to the maintainers of the opentelemetry project:

![image](https://user-images.githubusercontent.com/4099109/144858291-cd113192-75c6-4e21-850e-0dfc6a5d3fb1.png)

Hopefully we'll hear back from them shortly.

**Comment by bobstrecansky** [comment]
This has been completed for opentelemetry-php.  I'll need to request the same access for opentelemetry-php-contrib to do the same there.

**Comment by bobstrecansky** [comment]
I've completed the same for opentelemetry-php-contrib.  I believe this work has been completed.  I'm going to close this ticket.
