### ISSUE TITLE
Proposal: create an `experimental` dir

### ISSUE THREAD

**Issue by brettmc** [open-telemetry/opentelemetry-php#499]
Idea from @tidal in https://github.com/open-telemetry/opentelemetry-php/pull/498#issuecomment-984831495

> One thing thing I found in the repos of other SIGs is, that they often have a experimental directory besides the src one. Maybe we can adport this, so it would be easier to collaborate on certain things, and once everybody is happy, we move it to source?
> One reason is, that I find it way easier to review code locally, than in github's PR GUI (There are tools to help with this, but they don't work with the restrictions of the OTEL repos afaik)

To consider:
- namespace
- autoloader (dev only?)
- should not be published to packagist?

**Comment by tidal** [comment]
> * namespace

Yes! 
If it's a special one (eg. `OpenTelemetry/Experimental`) it could also host modified version of existing files.

> * autoloader (dev only?)

Yes!

> * should not be published to packagist?

Yes!

**Comment by Grunet** [comment]
Just for reference I think [this search](https://grep.app/search?q=%28&filter[repo.pattern][0]=open-telemetry&filter[path.pattern][0]=experimental) captures the other repos that do something like this (or at least some of them perhaps)

**Comment by tidal** [comment]
@Grunet 
Thank you, I did not know that such a great name like "grep.app" exists (no sarcasm, I love it!). 
The features are cool too, btw.

**Comment by brettmc** [comment]
Another thought - having `experimental` is good for trying things out, but it would also be useful to use it as a way to collaborate or have others try out prototype code. Having to submit a PR and merge to main is too much friction for collaboration.

**Comment by tidal** [comment]
@brettmc 
We could use the clones in https://github.com/otel-php for people to collaborate in the future.
I actually created them just to test the sub-splits, but we could keep them to have an easier way to collaborate.

**Comment by bobstrecansky** [comment]
It appears you've added this in https://github.com/open-telemetry/opentelemetry-php/pull/498, so I'm going to go ahead and close this issue for now.
