### ISSUE TITLE
Alpha 0.2 Tracing Requirement -  SDK

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#5]
These are the features in scope for an Alpha 0.2 SDK release from a tracing standpoint: 

- [ ] Built-in samplers (percentage sampler).
- [x] SpanProcessor interface
- [x] Batching SpanProcessor
- [x] Exporter interface
- [x] Jaeger and/or Zipkin exporter

Success criteria : Add these features to the 0.2 Alpha release candidate.
Full SDK specs for Alpha 0.2 can be found [here](https://github.com/open-telemetry/opentelemetry-specification/blob/master/milestones.md#sdk-specs-for-alpha-v02)

**Comment by bobstrecansky** [comment]
tracing won't work without context propagation, an item we are tracking in https://github.com/open-telemetry/opentelemetry-php/issues/6

Span processors/exporters won't work without a tracer API and minimal implementation, as caputred in https://github.com/open-telemetry/opentelemetry-php/issues/10

**Comment by jodeev** [comment]
There is one remaining outstanding piece of work to be closed: https://github.com/open-telemetry/opentelemetry-php/issues/162

**Comment by bobstrecansky** [comment]
Closing this because we are going to eventually skip more towards a more recent alpha release.
