### ISSUE TITLE
Create unified HTTP Client (Wrapper)

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#508]
In order to reduce dependencies in the HTTP exporters as unified HTTP Client (Wrapper) should be created.
The HTTP Client (Wrapper) should be configurable by users, if needed.
The HTTP Client (Wrapper) should be usable by other components (for exmple detectors).
The HTTP Client (Wrapper) must be able to work with PSR compatible implementations.

**Comment by tidal** [comment]
@stale
ickwarnda

**Comment by brettmc** [comment]
I believe we can close this, as `PsrTransport` achieves this?
