### ISSUE TITLE
tests crash on 8.1 with fiber support

### ISSUE THREAD

**Issue by brettmc** [open-telemetry/opentelemetry-php#515]
Test suite crashes on php 8.1 with fiber support: https://github.com/open-telemetry/opentelemetry-php/runs/4528730866?check_suite_focus=true#step:12:47
> The failure is caused by this line:
https://github.com/open-telemetry/opentelemetry-php/blob/main/src/Context/fiber/zend_observer_fiber.php#L34
If that line is removed, it results in a segfault though.
The part above that line is used to load the C headers once and only once, that's why FFI::scope throws an exception at the first time.
The scope can be preloaded, which would avoid the exception being thrown, but that's a PHP.ini setting -> https://www.php.net/manual/en/ffi.configuration.php#ini.ffi.preload

**Comment by Nevay** [comment]
This should preferably be fixed in the phpunit config, there is no reason that this constant should be serialized.

Could use a different approach to keep the FFI reference alive, tests pass locally with this patch:
```patch
diff --git a/src/Context/fiber/zend_observer_fiber.php b/src/Context/fiber/zend_observer_fiber.php
index afd96f2..3cc3515 100644
--- a/src/Context/fiber/zend_observer_fiber.php
+++ b/src/Context/fiber/zend_observer_fiber.php
@@ -14 +13,0 @@ namespace OpenTelemetry\Context;
-use function define;
@@ -34 +33,6 @@ return (function (): bool {
-        define(__NAMESPACE__ . '\\_ffi_fibers', $fibers);
+        /** @internal */
+        class FFIFiberHolder
+        {
+            public static FFI $fibers;
+        }
+        FFIFiberHolder::$fibers = $fibers;
```

**Comment by brettmc** [comment]
@Nevay - is the idea of keeping the reference alive related to garbage collection? If so, stashing it in a static variable makes sense.

**Comment by Nevay** [comment]
Yes, the registered observer callbacks become invalid if the FFI::load() instance is gc'ed; the callbacks then result in segfaults (FFI::scope() returns a persistent FFI instance that won't be freed - [ffi.c](https://github.com/php/php-src/blob/php-8.1.0/ext/ffi/ffi.c#L2314-L2337)).
