### ISSUE TITLE
[meta] php 8.1 support

### ISSUE THREAD

**Issue by brettmc** [open-telemetry/opentelemetry-php#516]
PHP 8.1 has been released, and there are some issues to fix to make the library compatible.

Issues that we are currently aware of with opentelemetry-php + 8.1:
- [x] #489 
- [x] #515 
- [ ] protobuf deprecation notices

**Comment by brettmc** [comment]
there are two PRs against protobuf which address 8.1 deprecation notices, so hopefully one will be accepted and will make its way through into a release. I've tested otel-php against my PR, and it removes/silences all notices.

**Comment by brettmc** [comment]
Nearly there - my google/protobuf PR has been merged, so whenever the next release comes out (3.19.5 or 3.20.0), our 8.1 tests should start passing.

**Comment by bobstrecansky** [comment]
I think we can close this now because this fix has been hotpatched upstream.
