### ISSUE TITLE
Unify Test Coding Style

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#529]
At the moment tests have very different coding styles. Some use a `@test` annotation, some use a `test`method prefix, Some use `snake-case`, some use `pascal-`or `camel-case` and mixtures of all those variants. 
This severly limits the readabilty of the tests, so they signatures of the test methods should be unified. 
As the specific style is a matter of taste and/or habit, the best way to find a unified style is to look for what style is used the most at the moment and to adjust the other tests acoordingly. As both these tasks can be tediuous and error prune, when done manually, it's best to use an automated approach by writing scripts to achieve said goals.

- Investigate the most common coding style in tests
- Adjust tests to follow the most common coding style

**Comment by sonro** [comment]
Hello, I would like to help with the testing improvements and I want to start with this issue. I have recently researched developer's preferences regarding snake_case vs camelCase in function/variable naming.

In modern PHP testing, it seems to be split pretty evenly between the two; with a slight edge to camelCase. However, from my research, people find snake_case preferable for longer function/method names.

Would it be acceptable to move the method naming to snake_case? I will start researching "test" annotating vs prefixing.

**Comment by tidal** [comment]
@sonro 
Hi, and thank you for wanting to contribute.
> Would it be acceptable to move the method naming to snake_case?

Yes, absolutely!

Do you want us to assign you to the issue?

**Comment by sonro** [comment]
> Do you want us to assign you to the issue?

Sure, go ahead.
