### ISSUE TITLE
AlwaysOnJaegerExamplePHP Fatal error: Uncaught Error: Call to undefined method OpenTelemetry\SDK\Trace\TracerProvider::addSpanProcessor()

### ISSUE THREAD

**Issue by sajjadgol** [open-telemetry/opentelemetry-php#539]
```
my php composer.json
{
    "minimum-stability": "dev",
    "require": {
        "php-http/guzzle7-adapter": "^1.0",
        "open-telemetry/opentelemetry": "dev-main",
        "guzzlehttp/psr7": "^2.1",
        "symfony/http-client": "^6.0"
    }
}

```
error :
Starting AlwaysOnJaegerExamplePHP Fatal error:  Uncaught Error: Call to undefined method OpenTelemetry\SDK\Trace\TracerProvider::addSpanProcessor() ....

section of my code : ( copy from  https://github.com/open-telemetry/opentelemetry-php/blob/0.0.4/examples/AlwaysOnJaegerExample.php)

**Comment by tidal** [comment]
related: https://github.com/open-telemetry/opentelemetry-php/issues/426

**Comment by sajjadgol** [comment]
thank you @tidal @brettmc
