### ISSUE TITLE
Context Propagation - How to get the context of a span?

### ISSUE THREAD

**Issue by markvdlaan93** [open-telemetry/opentelemetry-php#550]
Currently, I'm looking into implementing Context Propagation for cross-service tracing. I'm struggle to understand how to exactly implement this based on the current structure. The propagator expects a Context object to inject to. How to get the context to which a specific span is wired? It seems like I only have SpanContextInterface at my disposal. Here's my code:

```
$factory = new Psr17Factory();
$otlpExporter = new OtlpHttpExporter(new Client(), $factory, $factory);
$traceProvider = new TracerProvider(new BatchSpanProcessor($otlpExporter), new AlwaysOnSampler());

$tracer = $traceProvider->getTracer();

$spanBuilder = $tracer->spanBuilder('root');
$rootSpan = $spanBuilder->startSpan();

$arrayAccessGetterSetter = ArrayAccessGetterSetter::getInstance();
$carrier = [];
$key = 'context_uuid';
$value = '73903522-8b7e-4054-8299-bc42a874efa1';
$arrayAccessGetterSetter->set($carrier, $key, $value);

$propagator = new BaggagePropagator();
// HERE: getContext() refers to SpanContextInterface instead of Context
$propagator->inject($carrier, $arrayAccessGetterSetter, $rootSpan->getContext());

$rootSpan->activate();

**Comment by markvdlaan93** [comment]
I will close this question. I didn't understand why the Context class was implemented statically. Each request does have a different context which is why it shouldn't be a problem to just call Context::getCurrent();

**Comment by brettmc** [comment]
@markvdlaan93 - if you get this all working, we'd love an example to add to the collection :)

**Comment by markvdlaan93** [comment]
@brettmc I will for sure :-)

**Comment by elarity** [comment]
You can try the way below. That is : use storeInContext() method of a span object to "convert" it.

$ctx = $childSpan->storeInContext(Context::getCurrent());
TraceContextPropagator::getInstance()->inject($carrier, null, $ctx);

This is what I practiced.
