### ISSUE TITLE
Contributers onboarding.

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#552]
As discussed in the SIG meeting, we want to to create a github action which welcomes new contributers and adds more information tp the requierements for otel contributers, especially signing the CLA.

Also there should be a welcome message for people opening an issue for the first time.

Both  should be setup for the main and the contrib repo.

**Comment by brettmc** [comment]
There is a github [welcome-bot app](https://github.com/apps/welcome) which looks like it can do this. It does require some permissions on the repo (read/write on PRs and issues)

**Comment by tidal** [comment]
@brettmc 
The bot is an app, and installing an app requires otel bureaucracy.
This task can easily be done with github-script -> https://github.com/actions/github-script#welcome-a-first-time-contributor

**Comment by tidal** [comment]
@brettmc
If you want to give this a shot, just remove me and Bob from the assignees.  :o)
