### ISSUE TITLE
Context propagation - Extracting context remains empty

### ISSUE THREAD

**Issue by markvdlaan93** [open-telemetry/opentelemetry-php#557]
Currently, I'm trying to work out an example for context propagation. I have two services that communicate with each other through an endpoint. I injected a hardcoded uuid through the TraceContextPropagator class and I try to extract it in the other service but it remains empty. How to correctly set the traceparent so that the context is shared?

```
use Nyholm\Psr7\Factory\Psr17Factory;
use OpenTelemetry\Contrib\OtlpHttp\Exporter as OtlpHttpExporter;
use OpenTelemetry\SDK\Trace\TracerProvider;
use OpenTelemetry\API\Trace\SpanInterface;
use OpenTelemetry\API\Trace\TracerInterface;
use OpenTelemetry\Context\Context;
use OpenTelemetry\Context\Propagation\ArrayAccessGetterSetter;
use OpenTelemetry\Context\Propagation\TextMapPropagatorInterface;
use OpenTelemetry\SDK\Trace\Attributes;
use OpenTelemetry\SDK\Trace\Propagation\TraceContextPropagator;
use OpenTelemetry\SDK\Trace\Sampler\AlwaysOnSampler;
use OpenTelemetry\SDK\Trace\SpanProcessor\BatchSpanProcessor;


// SERVICE 1

$factory = new Psr17Factory();
$otlpExporter = new OtlpHttpExporter(new Client(), $factory, $factory);
$traceProvider = new TracerProvider(new BatchSpanProcessor($otlpExporter), new AlwaysOnSampler());

$tracer = $traceProvider->getTracer();

$spanBuilder = $tracer->spanBuilder('root');
$rootSpan = $spanBuilder->startSpan();
$rootSpan->activate();
$rootSpan->setAttribute('context_uuid', '12345678ab');

$spanBuilder = $tracer->spanBuilder('db_query_one');
$dbQueryOne = $spanBuilder->startSpan();
$dbQueryOne->setAttribute('query', 'one');

$dbQueryOne->end();

$arrayAccessGetterSetter = ArrayAccessGetterSetter::getInstance();
$carrier = [];
$arrayAccessGetterSetter->set($carrier, TraceContextPropagator::TRACEPARENT, 'dde92fc0-ac1c-4476-8c52-af29b2539bf5');

$propagator = new TraceContextPropagator();
$propagator->inject($carrier, $arrayAccessGetterSetter, Context::getCurrent());

$client = new Client();
$response = $client->get('https://service-2.test/traces');

$rootSpan->end();

// SERVICE 2

$factory = new Psr17Factory();
$otlpExporter = new OtlpHttpExporter(new Client(), $factory, $factory);
$traceProvider = new TracerProvider(new BatchSpanProcessor($otlpExporter), new AlwaysOnSampler());

$tracer = $traceProvider->getTracer();

$spanBuilder = $tracer->spanBuilder('root');
$rootSpan = $spanBuilder->startSpan();
$rootSpan->activate();
$rootSpan->setAttribute('context_uuid', '912345de');

$arrayAccessGetterSetter = ArrayAccessGetterSetter::getInstance();
$carrier = [
    TraceContextPropagator::TRACEPARENT => 'dde92fc0-ac1c-4476-8c52-af29b2539bf5',
];
$propagator = new TraceContextPropagator();
$context = $propagator->extract($carrier, $arrayAccessGetterSetter, Context::getCurrent());
// HERE: is empty
Log::info(json_encode($provider->extractPropagator()));

$spanBuilder = $tracer->spanBuilder('db_query_one');
$dbQueryOne = $spanBuilder->startSpan();
$dbQueryOne->setAttribute('query', 'one');

$dbQueryOne->end();

$rootSpan->end();

**Comment by tidal** [comment]
The "carrier" is supposed to transport tracing information over the wire. I case of HTTP calls it's usually done in the headers, but it could also be metadata in an gRPC call or a stamp in a messaging system and so on. That's why it's called "carrier" and not "headers".

The point of the TraceContextPropagator is to extract tracing information in W3C TraceContext format to and from HTTP headers.
In your example you are not sending anything, at least not headers, so the tracing data cannot reach the peer and thus cannot be extracted.
You can find an example how traces can be propagated between boundaries here: https://github.com/open-telemetry/opentelemetry-php/blob/main/examples/distributed-tracing/src/index.php#L47
This example is using Guzzle and a few middleware components, etc, but you can get the gist of it.

**Comment by brettmc** [comment]
It looks like you're trying to propagate trace headers for distributed tracing, in which case the example tidal suggested does this.
I thought from your previous question that you were trying to propagate arbitrary "other" data, which I believe is what [baggage](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/baggage/api.md#propagation) is for.

**Comment by markvdlaan93** [comment]
@brettmc My goal is to glue spans together into a single trace over multiple services. I thought the concept of baggage was used for that.

@tidal Thanks for the example. That will definitely help to make this working.

**Comment by markvdlaan93** [comment]
Thanks again for the example. After adding the carrier array to the request header, it worked.

**Comment by tidal** [comment]
@markvdlaan93 
No problem. Given that this is the most important use-case for tracing in the first place, it's really not well explained and documented at the moment. We are aware of that. 
In the future this will probably also be way easier to set up, as it's not very intuitive or easy to understand at the moment.

**Comment by aborigene** [comment]
The example link above is throwing a 404, does anyone have a valid example on context propagation?

**Comment by brettmc** [comment]
it moved, but not far: https://github.com/open-telemetry/opentelemetry-php/blob/main/examples/traces/demo/src/index.php#L47
