### ISSUE TITLE
Make it possible to pass OTEL_EXPORTER_OTLP_HEADERS and OTEL_EXPORTER_OTLP_ENDPOINT directly to the constructor of Otlp Exporter

### ISSUE THREAD

**Issue by markvdlaan93** [open-telemetry/opentelemetry-php#558]
**Is your feature request related to a problem?**
At the moment, it is only possible to set OTEL_EXPORTER_OTLP_ENDPOINT and OTEL_EXPORTER_OTLP_HEADERS through the environment:
```
use OpenTelemetry\Contrib\OtlpHttp\Exporter;

putenv('OTEL_EXPORTER_OTLP_ENDPOINT=https://my-otel-collector.example.com:443/v1/traces');
putenv('OTEL_EXPORTER_OTLP_HEADERS=testtest');

$factory = new Psr17Factory();
$otlpExporter = new Exporter(new Client(), $factory, $factory);
```

**Describe the solution you'd like**
I would like to pass the endpoint and headers directly to the constructor:
```
use OpenTelemetry\Contrib\OtlpHttp\Exporter;

$endpoint = 'https://my-otel-collector.example.com:443/v1/traces';
$headers = 'testtest';

$factory = new Psr17Factory();
$otlpExporter = new Exporter(
   new Client(),
   $factory,
   $factory,
   otelExporterOtlpEndpoint=$endpoint,
   otelExporterOtlpHeaders=$headers
);
```

**Describe alternatives you've considered**
I've used the current solution but putenv seems to be scoped based which means that when I create an exporter in a constructor (putenv called beforehand), the credentials aren't picked up.

**Additional context**
If there is any reason, why the current solution is only in place, please let me know. Otherwise, I would like to open a PR.

**Comment by brettmc** [comment]
I think `::fromConnectionString()` is the right the place to do this - it already accepts an endpoint url (but does nothing with it at the moment)

**Comment by brettmc** [comment]
Looking at the otlp http exporter, I think you're right - especially when comparing it with the grpc exporter, where everything is a constructor arg with defaults as required.
Also consider that the `::fromConnectionString` method could be improved, since it accepts an endpoint URL but does not use it.
