### ISSUE TITLE
[opentelemetry-php-contrib] Create Symfony DebugBundle

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#567]
The DebugBundle should enhance the Symfony [Profiler](https://symfony.com/doc/current/profiler.html) with a view of 
telemetry data collected by opentelemetry-php. Custom data-collectors and profiler templates need to be created for this to work.

**Comment by jdalmas** [comment]
I've try something in this PR https://github.com/open-telemetry/opentelemetry-php-contrib/pull/74 .
Like I say, I've put profiling logic into OtelSdkBundle instead of DebugBundle. I don't know if it's wrong or not.

**Comment by bobstrecansky** [comment]
@jdalmas - would you like us to merge this?

**Comment by jdalmas** [comment]
> @jdalmas - would you like us to merge this?

@bobstrecansky I've updated PR to use Instrumentation Interface & Trait. I you think this PR is ok, you can merge it.
