### ISSUE TITLE
[opentelemetry-php-contrib] SdkBundle: Extend documentation of configuration

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#574]
The SdkBundle documentation could use same be improvements in regards of the configuration. 
- [ ] Show how to enable/disable the SDK or parts of it in different environements (dev, staging, prod, etc.)
- [ ] Show how to configure Resource Limits and Attributes.
- [ ] Show how to configure different Span Samplers, especially the ParentBased Sampler and how to reference custom Samplers.
- [ ] Show how to configure Span Limits and Processors and and how to reference custom Processors .
- [ ] Show how to reference custom Span Exporters.
- [ ] Show how to reference environment variables in the configuration.

**Comment by kishannsangani** [comment]
@tidal can you assign this issue to me?

**Comment by kishannsangani** [comment]
@tidal can you remove the stale tag from this? I will work on this soon.
