### ISSUE TITLE
Use Environment constants and accessor in Environment Resource Detector.

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#586]
The [Environment Resource Detector](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Resource/Detectors/Environment.php) has been missed in the refactoring of the Env Var handling.

- Use [Environment Constants](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Common/Environment/Variables.php) in [Environment Resource Detector](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Resource/Detectors/Environment.php)
- Use [Environment Variable Accessor](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Common/Environment/Accessor.php) to fetch and validate Environment Variables in [Environment Resource Detector](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Resource/Detectors/Environment.php)

**Comment by kishannsangani** [comment]
Hey @tidal, can you assign this issue to me? I will be working on a similar issue related to the environment variable for the resource detector(#584).

**Comment by tidal** [comment]
@kishannsangani
Yes, sure. Thanks!

**Comment by tidal** [comment]
implemented in https://github.com/open-telemetry/opentelemetry-php/pull/592

Thanks @kishannsangani
