### ISSUE TITLE
Fix W3C  TraceContext Validation Tests.

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#589]
At the moment the [Tests ](https://github.com/open-telemetry/opentelemetry-php/tree/main/tests/TraceContext/W3CTestService) to tun the [W3C Distributed Tracing Validation Service](https://github.com/w3c/trace-context/tree/main/test) are broken and need to be fixed.
Also the tests setup is rather convoluted as it creates a Symfony project to run the tests against. This can be much more simplified by just using a single file as the entry point.

- Use the [Base Docker Image](https://github.com/open-telemetry/opentelemetry-php/pkgs/container/opentelemetry-php%2Fopentelemetry-php-base) in [the docker-compose file](https://github.com/open-telemetry/opentelemetry-php/blob/main/docker-compose.w3cTraceContext.yaml) to speed up the test setup
- Simplify test setup by using a single PHP file.
- Fix the tests and/or [TraceContextPropagator](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/API/Trace/Propagation/TraceContextPropagator.php)

**Comment by bobstrecansky** [comment]
@yuktea is going to work on this.
