### ISSUE TITLE
Support Per-Signal Environment Variables in OTLP Exporters.

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#590]
At the moment the OTLP [gRPC](https://github.com/open-telemetry/opentelemetry-php/blob/d2a90236325ea8ff6da5bf90d16e05e36ad0b8de/src/Contrib/OtlpGrpc/Exporter.php) and [HTTP](https://github.com/open-telemetry/opentelemetry-php/blob/d2a90236325ea8ff6da5bf90d16e05e36ad0b8de/src/Contrib/OtlpHttp/Exporter.php) Trace Exporters only allow for configuration via generic environment variables. 
(e.g. `OTEL_EXPORTER_OTLP_ENDPOINT`).
According to the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#configuration-options) : "Each configuration option MUST be overridable by a signal specific option." 
(e.g. `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT`).

Configuration should first check for the existence of a signal (traces) specific environment variable, and in absence fall back to the respective generic environment variable.

Special attention must be given to the [modification rules for endpoint URLs](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#endpoint-urls-for-otlphttp).

**Comment by yuktea** [comment]
I would like to try this out, could you please assign it to me? @tidal
