### ISSUE TITLE
Refactor SpanContext

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#618]
`OpenTelemetry\API\Trace\SpanContext` could use some refactorings.

- Remove `use OpenTelemetry\API\Trace as API;` 
- Move factory methods into dedicated factory
- Move validation methods into dedicated validatoe
- Move constructor and properties to the top

**Comment by kpratyus** [comment]
I can work on this issue. Could I get this assigned?

**Comment by tidal** [comment]
@kpratyus 
Sure, thank you!

**Comment by ditsuke** [comment]
@kpratyus, are you still working on this issue? If not, I'd love to take this up instead. :)

**Comment by Soockee** [comment]
since a related PR has been merged, could this be closed? @tidal
