### ISSUE TITLE
Move InstrumentationLibrary key generation out of TracerProvider

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#619]
The generation of a key for a InstrumentationLibrary should be moved out of the [TracerProvider class](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Trace/TracerProvider.php#L69) into a utility class in `SDK/Common/Util`,  since this funtionality is not only required in the `Trace` component/signal.

- Move key generation logic in `TracerProvider::getTracer`  into a dedicated Util class

**Comment by ditsuke** [comment]
@tidal I'd like to be assigned.
