### ISSUE TITLE
Implement factory for ResourceInfo

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#621]
At the moment most of the methods in [ResourceInfo](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Resource/ResourceInfo.php) are factory methods. To better comply with [SRP](https://en.wikipedia.org/wiki/Single-responsibility_principle) those methods should be extracted into a factory class.

**Comment by kishannsangani** [comment]
@tidal I would like to work on this. Can you help me?

**Comment by tidal** [comment]
@kishannsangani 
Sure, we'll talk on slack.
