### ISSUE TITLE
How to get the attributes of a SpanInterface?

### ISSUE THREAD

**Issue by markvdlaan93** [open-telemetry/opentelemetry-php#630]
For testing purposes, I would like to get the attributes of SpanInterface to check whether my code behaves as it should be. The SpanInterface only has methods to set attributes, not to get them. Is it possible to fetch the attributes of a SpanInterface after it is created?

**Comment by brettmc** [comment]
The easiest way is to just export your spans (eg using the ConsoleSpanExporter, from the examples). If you want to do it programatically, `getAttributes` is part of `SpanDataInterface`, and I think you can just call `toSpanData()` on either a ReadableSpanInterface or ReadWriteSpanInterface. Any span you've created should implement one of these interfaces.
