### ISSUE TITLE
Move stack trace formatting out of Span class

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#632]
The method [formatStackTrace ](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Trace/Span.php#L175) should be moved from `Span` into a dedicated Util/Formatter class in the `SDK\Common` namespace since formatting stack traces is not the responsibility of a `Span`.

- Move logic in `formatStackTrace`  from `Span` into a dedicated Util/Formatter class
- Add Backward compatibility by calling the new method from `Span::formatStackTrace` and tigger deprecation notice with [Compatibility\Util::triggerMethodDeprecationNotice](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Common/Dev/Compatibility/Util.php#L23)

**Comment by amber0612** [comment]
@tidal Please assign this issue to me. Thanks!
