### ISSUE TITLE
EndpointURL cannot set with no-environment variables when using OtlpGrpc exporter 

### ISSUE THREAD

**Issue by xinfeingxia85** [open-telemetry/opentelemetry-php#638]
**Describe your environment**
PHP: 8.1.3
OpenTelemetry-php: v0.0.8
PHP Framework: Lavarel

**Steps to reproduce**

```
use OpenTelemetry\Contrib\OtlpGrpc\Exporter;
$exporter  = new Exporter("otel-collector:4317");
```

**What is the expected behavior?**
I expect that all trace data can be sent successfully.

**What is the actual behavior?**
All trace data cannot be sent to OTLP collector. 
I found that the endpointUrl was always http://localhost:4318 with no-environment variable.
Because the following code have a problem.
https://github.com/open-telemetry/opentelemetry-php/blob/54066eb3eba059e224ab13117c70602bc7746825/src/Contrib/OtlpGrpc/Exporter.php#L79
```
 $this->client = $client ?? new TraceServiceClient(
            $this->getStringFromEnvironment(Env::OTEL_EXPORTER_OTLP_TRACES_ENDPOINT) ?:
            $this->getStringFromEnvironment(Env::OTEL_EXPORTER_OTLP_ENDPOINT, $endpointURL),
            $opts
        );
```
The method `getStringFromEnvironment` is always `http://localhost:4318` when using no environment variable.

I debugged and found that constant `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` and `OTEL_EXPORTER_OTLP_ENDPOINT`  caused this problem. 

https://github.com/open-telemetry/opentelemetry-php/blob/54066eb3eba059e224ab13117c70602bc7746825/src/SDK/Common/Environment/Defaults.php#L47

**Additional context**
Exporter log:
```
{"message":"Retryable error exporting grpc span","context":{"error":{"error":"DNS resolution failed for service: http://localhost:4318","code":14},"source":"OpenTelemetry\\Contrib\\OtlpGrpc\\Exporter"},"level":300,"level_name":"WARNING","channel":"local","datetime":"2022-03-28T05:39:07.129398-04:00","extra":{},"dd":{"trace_id":"3979934274549304821","span_id":"15375625160825378503"}}
```

**Comment by brettmc** [comment]
Thanks for the bug report. I've validated it, and agree that it is a bug.
