### ISSUE TITLE
PHP Contribution to the OpenTelemetry Demo Application

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#658]
The [OpenTelemetry Demo Application](https://docs.google.com/document/d/1nCV32KvYzowspjWk9ym6MoLOc-1D_RF-EcX7Dnf_VcE/edit) needs some input from the PHP crowd.

We'd like to help the end-to-end demo application include PHP!

**Comment by brettmc** [comment]
Completed in https://github.com/open-telemetry/opentelemetry-demo/pull/345 (quote service)
