### ISSUE TITLE
Ability to add a parent context to a span:  parent trace_id,  parent span_id

### ISSUE THREAD

**Issue by sergey-telpuk** [open-telemetry/opentelemetry-php#666]
Hello, how can I use `startAndActivateSpanFromContext` for setting traceID and root spanID ?
It looks after refactoring  @Blacksmoke16 #422  the logic was broken. Pls point how to do the same with new logic.

**Comment by tidal** [comment]
Could you please point us to what exactly you are referring to or give more context?
(Neither the TraceId or SpanId are meant to be set by a user).

**Comment by sergey-telpuk** [comment]
This startAndActivateSpanFromContext function was deleted. How can I set context without this function. Also this function wasn't deleted in tests. I guess we have invalid tests.

**Comment by tidal** [comment]
> How can I set context without this function.
```php
$span->storeInContext($context);
``` 

> Also this function wasn't deleted in tests. I guess we have invalid tests.

Could you please tell, what tests you are referring to?

**Comment by sergey-telpuk** [comment]
![image](https://user-images.githubusercontent.com/4964014/165688591-ffa2cfbf-f003-4955-9826-23f45c205ef3.png)

**Comment by sergey-telpuk** [comment]
Also, I found this solution instead of that function. Pls, say it's correct for embedding span from another microservice? I want to do the same as #244 
```php
   $spanContext = SpanContext::create(
            traceId: "f7f253774e5777d4bc25442c84db6f39",
            spanId: "49f84ed57eafdf9c",
            traceFlags: 1
        );

        $ctx = (new Context())->withContextValue(new NonRecordingSpan($spanContext));

        $newSpan = $tracer->spanBuilder('child')->setParent($ctx)->startSpan();
        $newSpan->activate();
        $newSpan->addEvent("new event",["sds"=>"sd"]);
        sleep($i*5);
        $newSpan->end();
```

**Comment by brettmc** [comment]
Hi @sergey-telpuk, it looks like you're trying to do [distributed tracing](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#tracing-signal)? The "right way" to do that is with [TraceContextPropagator](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/API/Trace/Propagation/TraceContextPropagator.php), and there is an example of using it in `examples/distributed-tracing`

**Comment by sergey-telpuk** [comment]
@brettmc Hi, I'm trying to add send trace_id, spain_id to another service for creating the child span and add to parent. I work with event drive design.

**Comment by brettmc** [comment]
If you are just generating one trace, then the current active span is stored in a static `ContextStorage` which will be used by span builder. So, you should not need to provide parent span context, as by default it will find the active span and use that as the parent.

**Comment by sergey-telpuk** [comment]
@brettmc thanks, one more question about using uber-trace-id, do you guys have example for it?

**Comment by bobstrecansky** [comment]
I believe `uber-trace-id` is an OpenTracing idiom, not an OpenTelemetry idiom.  What problem are you attempting to solve with `uber-trace-id`?

**Comment by sergey-telpuk** [comment]
Got it, I hoped that this repo has ready example like jagger uber-trace-id, thanks.

**Comment by bobstrecansky** [comment]
I think this can be closed.  @sergey-telpuk - please reopen if your issue isn't resolved.
