### ISSUE TITLE
Jager Exporter

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#67]
We'd like to be able to export metrics to Jaeger.  We can most likely use the [OpenCensus php exporter Jager](https://github.com/census-ecosystem/opencensus-php-exporter-jaeger) repo as a jumping point.

**Comment by bobstrecansky** [comment]
Tagging @beniamin as he mentioned he's like to work on this (and I couldn't assign this task to him).

**Comment by beniamin** [comment]
Started working on it in https://github.com/open-telemetry/opentelemetry-php/pull/70

**Comment by beniamin** [comment]
I think this cand be closed since #70 was merged.
