### ISSUE TITLE
Symfony Example

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#679]
Currently we have a [Symfony Integration Guide](https://github.com/open-telemetry/opentelemetry-php/blob/main/docs/laravel-integration.md](https://github.com/open-telemetry/opentelemetry-php/blob/main/docs/symfony-integration.md)) that is aimed at very new contributors.

We'd love to have an example that uses more of Symfony best practices as described by their [documentation](https://symfony.com/doc/current/index.html).

**Comment by DrLuke** [comment]
The [SDK bundle](https://github.com/open-telemetry/opentelemetry-php-contrib/tree/main/src/Symfony/OtelSdkBundle) had a readme that explains exactly what you need to do to get started with adding open-telemetry to your existing symfony application. Using a bundle is the best practice for a case like this.

I think having a symfony integration guide that start by explaining how to set up a symfony app is wildly out of scope for this project. (not to mention that it currently doesn't even remotely follow best practices).

I'd recommend to add a link to the bundle for symfony users and to remove any symfony related documentation from this project.
