### ISSUE TITLE
Zipkin zxamples do not work because of malformed timestamp format 

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#69]
Our examples currently do not store any records to Zipkin due to malformed timestamp format caused by `OpenTelemetry\Sdk\Internal\Clock`

Success criteria - fix the timestamps so that we can successfully execute examples again.

**Comment by lalex** [comment]
It seems the root of the error is in `ZipkinExporter` [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/d21bdeb673c22d7e166bc667bccd77996824a49b/specification/exporter-zipkin.md#unit-of-time), where time has a float representation.
It also has a reference to a [zipkin.proto](https://github.com/openzipkin/zipkin-api/blob/master/zipkin.proto), it requires Timestamp and Duration to be in integer format.

**Comment by bobstrecansky** [comment]
More information about the timestamp and duration can be found in the spec here:
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-tracing.md#timestamp

@morrisonlevi mentioned we should bump the minimum PHP requirement to 7.3 and use the hrtime function in order to get the timestamps correct.

https://www.php.net/manual/en/function.hrtime.php

**Comment by morrisonlevi** [comment]
This is also performance sensitive work, as we could potentially have two instances of whatever time format we choose per span. We should be sensitive to that while balancing usage and other concerns.

**Comment by beniamin** [comment]
Also current implementation rounds the timestamp to milliseconds, but Zipkin expects microseconds. So instead of using round, the timestamp should be multiplied with 1000. I will fix this issue in https://github.com/open-telemetry/opentelemetry-php/pull/70

**Comment by bobstrecansky** [comment]
Sounds good.  Thanks @beniamin !
