### ISSUE TITLE
Implement PropagatorFactory

### ISSUE THREAD

**Issue by kishannsangani** [open-telemetry/opentelemetry-php#690]
**Is your feature request related to a problem?**
According to the opentelemetry-specification [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#general-sdk-configuration), OTEL_PROPAGATORS variable can be used to configure propagators from the environment but currently, there is no mechanism to retrieve the list of propagators from the environment variable and configure it.

**Describe the solution you'd like**
Create a PropagatorFactory that will retrieve the list of propagators from the OTEL_PROPAGATORS environment variable and configure it.

**Describe alternatives you've considered**
None.

**Additional context**
With B3Multi propagator implemented [here](https://github.com/open-telemetry/opentelemetry-php/pull/680), PropagatorFactory will be useful in setting up an example to demonstrate the same from the existing [distributed-tracing](https://github.com/open-telemetry/opentelemetry-php/tree/main/examples/distributed-tracing) example.

**Comment by kishannsangani** [comment]
@brettmc, @tidal, @bobstrecansky 
Can you assign this issue to me?

**Comment by brettmc** [comment]
As well as a PropagatorFactory, I think maybe we also need a singleton class which holds a collection of propagators (a bit like `MultiSpanProcessor`). and that's the class we'd interact with (I'm imagining that it also implements appropriate propagator interfaces (`TextMapPropagatorInterface`?), then iterates over defined propagators. The factory could be used by its `getInstance()` method, if nothing else has been explicitly set?

**Comment by kishannsangani** [comment]
@brettmc that is a great idea! I will raise a couple of PRs to get this implemented, starting with `TextMapPropagatorInterface`.

**Comment by brettmc** [comment]
Discussed in SIG today, agreed that initial implementation should be in API (since the spec requires that propagators work with an API-only installation)

**Comment by brettmc** [comment]
@kishannsangani the spec also requires a [composite propagator](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#composite-propagator) - do you think that could be part of this issue, or separate?
