### ISSUE TITLE
Alpha 0.2 Metrics Requirement - SDK

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#7]
The SDK specs for an Alpha 0.2 release contain metrics.  These are the features in scope for an Alpha 0.2 release from a metrics standpoint:

- [ ] MetricsProcessor interface
- [ ] Aggregation MetricsProcessor
- [ ] Exporter interface
- [ ] Prometheus Exporter

Success criteria : Add these features to the 0.2 Alpha release candidate.
Full SDK specs for Alpha 0.2 can be found [here](https://github.com/open-telemetry/opentelemetry-specification/blob/master/milestones.md#sdk-specs-for-alpha-v02)

**Comment by bobstrecansky** [comment]
Metrics work doesn't depend on anything else, even context propagation, so this is probably a good first issue for someone.

**Comment by artem-prozorov** [comment]
Can I take this one?

**Comment by bobstrecansky** [comment]
You sure can!  I know @Fahmy-Mohammed started work on the meter interface, but I don't think that should preclude you from working on any of the other pieces of this!  Issue for reference:

https://github.com/open-telemetry/opentelemetry-php/issues/113

**Comment by artem-prozorov** [comment]
@bobstrecansky I need some consultation, I haven't found term "MetricsProcessor" in the spec https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md
Did you mean Metrics Provider ?
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#meter-provider

**Comment by bobstrecansky** [comment]
@artem-prozorov - Correct.  This spec has changed since this ticket was created.  The general gist of this ticket is to get Metrics ready for a 0.2 release.  The [project status](https://opentelemetry.io/project-status/) also changed a bit, so the 0.2 release doesn't need to contain a metrics package.  This means the name of this ticket should probably also be changed to Alpha 0.3 Metrics Requirement.  That shouldn't stop you from starting to develop a metrics implementation based on the spec.

**Comment by artem-prozorov** [comment]
Got it, thanks

**Comment by bobstrecansky** [comment]
Sure thing!  If you have any questions, feel free to ask here or in the [gitter channel](https://gitter.im/open-telemetry/opentelemetry-php)!

**Comment by bobstrecansky** [comment]
Closing this because we are going to eventually skip more towards a more recent alpha release.
