### ISSUE TITLE
OTLP exporter for metrics

### ISSUE THREAD

**Issue by DrLuke** [open-telemetry/opentelemetry-php#700]
Currently there is only a [`PrometheusExporter`](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/Contrib/Prometheus/PrometheusExporter.php) available to export metrics.

otel-col can read prometheus metrics and convert them to OTLP, but it would be a lot nicer to avoid this unnecessary conversion step.

**Comment by erdemkose** [comment]
@DrLuke @tidal FYI; I see that it is implemented in https://github.com/open-telemetry/opentelemetry-php/pull/750
