### ISSUE TITLE
Defining attributes at span creation

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#704]
The spec compliance matrix defines:

Documentation defines adding attributes at span creation as preferred [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#span-creation)

Let's implement this.

**Comment by amber0612** [comment]
Hey @bobstrecansky, Can u please assign this issue to me. Thanks.

**Comment by brettmc** [comment]
Discussed in SIG. We think that all this ticket is asking for is that documentation be added/updated/confirmed (probably just inline phpdoc, as we don't have good usage documentation yet). The doco/comment should inform users of the API that "adding attributes at span time is preferred over adding them after span creation" (for reasons we don't fully understand, but that is what the spec says).

**Comment by brettmc** [comment]
@amber0612 - thinking about this more, I think the idea is that samplers _could_ use attributes to make sampling decisions (although none of the default ones do)... eg "sample 100% of requests where country=USA", and if those attributes are not provided at span creation time, they're not available to make sampling decisions from.
