### ISSUE TITLE
`SpanProcessor` incorrect calls to `SpanExporter::forceFlush()`

### ISSUE THREAD

**Issue by Nevay** [open-telemetry/opentelemetry-php#715]
- `SimpleSpanProcessor::forceFlush()` has to force-flush exporter
- `BatchSpanProcessor::onEnd()` shouldn't force-flush exporter

**Comment by brettmc** [comment]
I agree with `SimpleSpanProcessor::forceFlush()`, but the conditional flush in `BatchSpanProcessor::onEnd()` seems critical to the batching functionality. Is the issue that we're using the `forceFlush()` mechanism not for its intended purpose?

**Comment by Nevay** [comment]
The batching functionality doesn't depend on force-flushing; the batch processor should still call `::export()` with the batch in `::onEnd()`, just without calling `::forceFlush()` afterwards.

[SpanExporter::forceFlush()](https://github.com/open-telemetry/opentelemetry-specification/blob/5fb819c72e34cb21fe1ce5acba1dc93c2216ecb1/specification/trace/sdk.md#forceflush-2)
> ForceFlush SHOULD only be called in cases where it is absolutely necessary, such as when using some FaaS providers that may suspend the process after an invocation, but before the exporter exports the completed spans.

**Comment by amber0612** [comment]
I would like to work on this one. Can you please assign it to me. thanks

**Comment by brettmc** [comment]
Fixed by #788
