### ISSUE TITLE
Refactor TraceState's __toString method

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#727]
[TraceState's __toString method](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/API/Trace/TraceState.php#L98) should be refactored for better performance and readability

- Remove unnessesary cloning of current instance
- Reverse check to a guard clause:
```php
if (empty($this->traceState)) {
    return '';
}
```

**Comment by amber0612** [comment]
Please assign this to me @tidal.
