### ISSUE TITLE
Make open-telemetry/opentelemetry an All-in-One Package

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#730]
Since we now distribute the different components of the library as separated packages, we want to make the global package [open-telemetry/opentelemetry](https://packagist.org/packages/open-telemetry/opentelemetry) an all-in-one package which comes with all necessary dependencies. This should make it easy to try out the functionality of the library.

- Add a `psr/http-factory-implementation` to the `require` section of the main `composer.json`
- Add a `php-http/async-client-implementation` to the `require` section of the main `composer.json`
- Add a `psr/log` implementation to the `require` section of the main `composer.json`
- Document changes in `README`

**Comment by Jimlah** [comment]
Hello @tidal, I noticed these have already been done.

**Comment by brettmc** [comment]
Agreed, done. Closing.
