### ISSUE TITLE
Remove ResourceConstants

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#749]
The [ResourceConstants](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Resource/ResourceConstants.php) class  has been deprecated since the introduction of semantic conventions in release[ 0.0.4](https://github.com/open-telemetry/opentelemetry-php/releases/tag/0.0.4). It should be removed now, since it's not used anywhere in the library or the contrib repository's components.

**Comment by CalinBolea** [comment]
I'll take this.
