### ISSUE TITLE
Demo is not working?

### ISSUE THREAD

**Issue by trboltom** [open-telemetry/opentelemetry-php#754]
**Describe your environment** 
Docker image provided in the example (`ghcr.io/open-telemetry/opentelemetry-php/opentelemetry-php-base:8.1`), tested on MacOS Monteray and Ubuntu. 

**Steps to reproduce**
1. clone this repository
2. follow steps provided in https://github.com/open-telemetry/opentelemetry-php/tree/main/examples/traces/demo
3. In browser go to http://localhost:16686/search

**What is the expected behavior?**
In the left menu I expect to see `service-one` `service-two` and `service-three` listed under `services` input after successful `curl` execution in the previous step.

**What is the actual behavior?**
I see only`jaeger-query`, no services from this demo are here
<img width="487" alt="image" src="https://user-images.githubusercontent.com/7612146/177985048-565d1253-e7bb-49d3-907b-4c2c09940a1b.png">

**Additional context**
- In the logs of `zipkin`, `collector` and `jaeger` containers I see only logs that services correctly started, but didn't find anything related to the traffic/span collection.
- In the `composer.json` I tried versions `0.0.12`, `0.0.11`, `0.0.10` and `0.0.9` but all with same result. 

Collector logs
![image](https://user-images.githubusercontent.com/7612146/177985380-58598491-003a-49c7-b469-004a875c9fdc.png)

Jaeger logs
![image](https://user-images.githubusercontent.com/7612146/177985411-d7e846f4-a7aa-4b64-b869-427f0e527cb3.png)

Zipkin logs
![image](https://user-images.githubusercontent.com/7612146/177985443-6a02601c-7d12-424b-881e-27b155530272.png)

**Comment by faysh** [comment]
It still not working. When I change OTEL_TRACES_EXPORTER to console I see spans in console. But with collector it doesn't work

**Comment by faysh** [comment]
Solution was pretty simple. You should add schema and protocol for exporter here
https://github.com/open-telemetry/opentelemetry-php/blob/main/examples/traces/demo/docker-compose.yml#L7

just replace collector:4317 by http://collector:4317
