### ISSUE TITLE
Fix Class Names and Directory Structure of Contrib Unit Tests.

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#769]
At the moment all [unit tests in the Contrib package](https://github.com/open-telemetry/opentelemetry-php/tree/main/tests/Unit/Contrib) just live in one single directory. The name of the tests and the directory structure should reflect the ones of the tested classes.

**Comment by sumit-158** [comment]
Hi, @tidal can I work on this?
