### ISSUE TITLE
Tracer data can't be sent using 0.0.12 ~0.0.13 and main version

### ISSUE THREAD

**Issue by xinfeingxia85** [open-telemetry/opentelemetry-php#789]
**Describe your environment** 
PHP: 8.1.7
OpenTelemetry-php: >=0.0.12 | main
PHP Framework: Lavarel

**Steps to reproduce**
1. OpenTelemetry PHP Version: main
```
$tracer_provider = new TracerProvider($span_processor, $sampler, $resource_info);
ShutdownHandler::register([$tracerProvider, 'shutdown']);
```
2. OpenTelemetry PHP Version: 0.0.12 | 0.0.13
```
$tracer_provider = new TracerProvider($span_processor, $sampler, $resource_info);
```
**What is the expected behavior?**
I expect that all trace data can be sent successfully.

**What is the actual behavior?**
All the tracer data aren't sent, even though register_shutdown_function executed.

- OpenTelemetry PHP Version: 0.0.12 | 0.0.13

    I found that  the code below caused this problem, as follow:
 ```
 self::$tracerProviders[spl_object_id($tracerProvider)] = WeakReference::create($tracerProvider);
```
   I modify the code and  the data can be sent, as follows:  

```
 private static function registerShutdownFunction(TracerProvider $tracerProvider): void
    {
        if (self::$tracerProviders === null) {
            register_shutdown_function(static function (): void {

                $tracerProviders = self::$tracerProviders;
                self::$tracerProviders = null;

                // Push tracer provider shutdown to end of queue
                // @phan-suppress-next-line PhanTypeMismatchArgumentInternal
                register_shutdown_function(static function (array $tracerProviders): void {
                    foreach ($tracerProviders as $reference) {
                        //if ($tracerProvider = $reference->get()) {
                            $tracerProvider->shutdown();
                        //}
                    }
                }, $tracerProviders);

            });
        }

        self::$tracerProviders[spl_object_id($tracerProvider)] = $tracerProvider;
    }

 ```
I think that the class WeakReference can't pass data, because  `self::$tracerProviders` always is null.
So it work fine without WeakReference::create.

- OpenTelemetry PHP Version: main
```
private static function registerShutdownFunction(): void
    {
        if (self::$handlers === null) {
            register_shutdown_function(static function (): void {
                $handlers = self::$handlers;
                self::$handlers = null;
                self::$weakMap = null;

                // Push shutdown to end of queue
                // @phan-suppress-next-line PhanTypeMismatchArgumentInternal
                register_shutdown_function(static function (array $handlers): void {
                    foreach ($handlers as $handler) {
                        $handler();
                    }
                }, $handlers);
            });
        }
    }
```
 `self::$handlers` also always is null,  so  I use  `register_shutdown_function([$tracer_provider, 'shutdown']);` and the data can be sent.

**Comment by Nevay** [comment]
Starting with 0.0.12 you have to keep a reference to the created `TracerProvider`, and preferably call `::shutdown()` explicitily at the end of your application.

**Comment by xinfeingxia85** [comment]
> Starting with 0.0.12 you have to keep a reference to the created `TracerProvider`, and preferably call `::shutdown()` explicitily at the end of your application.

OK, I have known why.
I will immediately call `TracerProvider::__destruct` if there is no reference to the TracerProvider.
