### ISSUE TITLE
Poor performance otlp+grpc exporter

### ISSUE THREAD

**Issue by asv** [open-telemetry/opentelemetry-php#811]
**Describe your environment** 

Host:
```
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

Application under docker:
```
$ docker version
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:57 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:03 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

PHP version
```
$ php -v
PHP 8.0.19 (cli) (built: May 10 2022 08:07:35) ( NTS gcc x86_64 )
Copyright (c) The PHP Group
Zend Engine v4.0.19, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.19, Copyright (c), by Zend Technologies
    with Xdebug v3.1.4, Copyright (c) 2002-2022, by Derick Rethans
```

opentelemetry-php (0.0.15).

**Steps to reproduce**
Instrument your code with opentelemetry-php (my case is Laravel application).
Configure otlp+grpc (to opentelemetry-collector).

**What is the expected behavior?**
Fast and low overhead telemetry.

**What is the actual behavior?**
High overhead (extra 100-300ms per request my application).

**Additional context**

I've profiled an application using php-spx and see a HUGE number of protobuf related function calls that eat up performance ruthlessly.

![opentelemetry-php-profile](https://user-images.githubusercontent.com/20145/188476594-7a4786c5-a2ad-4717-a623-f409f167c851.png)

Does it really take that many calls protobuf to send 16 spans?

**Comment by brettmc** [comment]
Hi @asv are you using the protobuf C extension, or the php library (eg installed via composer) ?

We know that performance is significantly better with the C extension, and that's the recommended approach: https://github.com/protocolbuffers/protobuf/blob/main/php/README.md

> The pure PHP package is intended to provide usability to wider range of PHP platforms, while the c extension is intended to provide higher performance

**Comment by brettmc** [comment]
If this does turn out to be that the native php implementation sucks, I'll move it from a `suggest` to a `require` when installing the otlp exporters...

**Comment by asv** [comment]
Hi @brettmc. Native extension is superduper fast. Now we can even run telemetry collection on our production environment!
Thanks a lot!

**Comment by brettmc** [comment]
Thanks for the update, that's very useful feedback. I'll make the extension the default if installing one of the otlp exporters.
