### ISSUE TITLE
add documentation for InstrumentationInterface

### ISSUE THREAD

**Issue by brettmc** [open-telemetry/opentelemetry-php#815]
Create documentation on how https://github.com/open-telemetry/opentelemetry-php/tree/main/src/API/Common/Instrumentation/InstrumentationInterface should be used. It was created to standardize 3rd party instrumentations (eg AWS SDK over in -contrib repo), there are some comments in `InstrumentationTrait` that describe how it is meant to be used which might be helpful.

**Comment by amber0612** [comment]
Hey @brettmc, I can take this up.

**Comment by brettmc** [comment]
Keep an eye on #822 @amber0612

**Comment by brettmc** [comment]
Closing. Nobody cares and we don't use the interface anywhere (except aws, which could update to not)
