### ISSUE TITLE
Fatal Error OpenTelemetry\Contrib\OtlpHttp\Exporter::__construct()

### ISSUE THREAD

**Issue by erickneverson** [open-telemetry/opentelemetry-php#836]
**Describe the bug**
The following works with another php app but does not for a separate app even while the dependencies are the same:

```
use GuzzleHttp\Client;
use GuzzleHttp\Psr7\HttpFactory;
use OpenTelemetry\Contrib\OtlpHttp\Exporter as OTLPExporter;
...
$exporter = new OTLPExporter(
            new Client(),
            new HttpFactory(),
            new HttpFactory()
        );
```

Getting Fatal error: Uncaught TypeError: Argument 1 passed to OpenTelemetry\Contrib\OtlpHttp\Exporter::__construct() must be an instance of OpenTelemetry\SDK\Common\Export\TransportInterface

**Steps to reproduce**
dependencies
```
"guzzlehttp/psr7": "^2.4.x-dev",
        "guzzlehttp/guzzle": "7.4.5",
        "symfony/http-client": "^5.4.x-dev",
        "open-telemetry/opentelemetry": "dev-main",
        "open-telemetry/sdk": "dev-main",
        "open-telemetry/sdk-contrib": "dev-main"
```

**What did you expect to see?**
I expected to see normal application activity where transactions are sent to the agent.

**What did you see instead?**
An exception was thrown (see above)

**What version did you use?**
See above.  PHP 7.4.

**What config did you use?**
composer.json

**Environment**
Ubuntu 20.04 (ubuntu:focal-20200423)

**Comment by brettmc** [comment]
Hi @erickneverson 
Our codebase is not stable, and it looks like you've picked up some recent breaking changes in main.
You have options:
1. go back to the latest tagged version (0.0.15) where your current code should work (but will break in the next release)
2. consult [https://github.com/open-telemetry/opentelemetry-php/blob/main/examples/traces/features/exporters/otlp.php](the examples) on how to set up with current main (which is more likely to work in the future)

**Comment by erickneverson** [comment]
@brettmc thanks for the feedback.  I'll future proof myself by looking into option 2.  

~ Best

**Comment by bobstrecansky** [comment]
@erickneverson - is it okay if we close this issue?
