### ISSUE TITLE
Span are not exported by the BatchSpanProcessor

### ISSUE THREAD

**Issue by jderusse** [open-telemetry/opentelemetry-php#852]
**Describe your environment**

Since #788 spans are not all flushed.

- in the `onEnd` methods, spans are pushed to the `batch` array buffer.
- the `batch` buffer is moved to the `queue` stack by the `enqueueBatch` method
- the `enqueueBatch` is called:
  -  when the `batch` buffer has more than `maxExportBatchSize` traces
  - Or when `shouldFlush` return true and `queue` is empty => this requires `autoFlush + $this->clock->now() > $this->nextScheduledRun`

There are cases (less span than `maxExportBatchSize` and process finish in less than `scheduledDelayNanos`) Where spans are not moved from `batch` buffer to `queue` stack and thus not flushed / exported

**possible solution**

Adds `if ($this->batch !== []) { $this->enqueueBatch();}` in `shutdown` and `forceFlush` and ask people to call these methods (or call `shutdown` on `__destruct`)

**Comment by bobstrecansky** [comment]
@tobiasstadler - wanted to check with you that you approve of this approach before we implemented it.

**Comment by Nevay** [comment]
Calling `::shutdown()` is [necessary](https://github.com/open-telemetry/opentelemetry-php/tree/0b43fac7292e0f6efa4f881526bcbf750833486f#set-up-a-tracer) and should flush all enqueued spans (`::shutdown()` adds the current batch id to the `$this->flush` queue); do you have a reproducer that calls `::shutdown()`?
> It's important to run the tracer provider's shutdown() method when the PHP process ends, to enable flushing of any enqueued telemetry.

**Comment by jderusse** [comment]
indeed, calling `shutdown` fixes the issue. Sorry for the noise
