### ISSUE TITLE
[opentelemetry-php-contrib] SdkBundle: How to receive parent context?

### ISSUE THREAD

**Issue by DrLuke** [open-telemetry/opentelemetry-php#855]
I have instrumented my nginx server with `opentelemetry-cpp-contrib` and am propagating the context into my Symfony application. I can confirm that the relevant W3C headers arrive in my app:

```
  "HTTP_TRACEPARENT" => "00-b2a29a9de66179f3b15c568425c2b316-7899b873a3143646-01"
  "HTTP_BAGGAGE" => ""
  "HTTP_TRACESTATE" => ""
```

How do I configure the bundle to read the header and connect my traces?

**Comment by brettmc** [comment]
I'm not very fluent in Symfony, but it looks to me like it should be happening in `RequestListener::startRequest` - https://github.com/open-telemetry/opentelemetry-php-contrib/blob/main/src/Symfony/src/OtelBundle/HttpKernel/RequestListener.php#L103
