### ISSUE TITLE
Calling forceFlush() does not clear metrics

### ISSUE THREAD

**Issue by erdemkose** [open-telemetry/opentelemetry-php#857]
**Describe your environment** 

PHP 7.4
Latest commit (https://github.com/open-telemetry/opentelemetry-php/commit/92e7a0d0706f2bf37c4023d19247c2ac6b3511d4)

**Steps to reproduce**

Calling `MeterProvider::forceFlush()` repeatedly will export the same metrics again and again.

```php
<?php

declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

use OpenTelemetry\SDK\Common\Time\ClockFactory;
use OpenTelemetry\SDK\Metrics\Data\Temporality;
use OpenTelemetry\SDK\Metrics\MeterProviderBuilder;
use OpenTelemetry\SDK\Metrics\MetricExporter\InMemoryExporter;
use OpenTelemetry\SDK\Metrics\MetricReader\ExportingReader;

$exporter = new InMemoryExporter(Temporality::CUMULATIVE);
$reader = new ExportingReader($exporter, ClockFactory::getDefault());
$meterProvider = (new MeterProviderBuilder())->addReader($reader)->build();
$meter = $meterProvider->getMeter('test-meter');
$counter = $meter->createCounter('test-counter');
$counter->add(1);

var_dump(count($exporter->collect())); // 0

$meterProvider->forceFlush();
var_dump(count($exporter->collect())); // 1

$meterProvider->forceFlush();
var_dump(count($exporter->collect())); // 2

$meterProvider->forceFlush();
var_dump(count($exporter->collect())); // 3
```

**What is the expected behavior?**

Calling `MeterProvider::forceFlush()` exports and clears the metrics queue

**What is the actual behavior?**

Calling `MeterProvider::forceFlush()` exports the metrics but does not clear the queue

**Comment by Nevay** [comment]
Exporting the same metrics on repeated `::forceFlush()` calls is expected behavior with `Temporality::CUMULATIVE` (see also (T<sub>0</sub>, T<sub>2</sub>] in the [Synchronous example: Cumulative aggregation temporality](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/supplementary-guidelines.md#synchronous-example-cumulative-aggregation-temporality)).

**Comment by erdemkose** [comment]
> Exporting the same metrics on repeated `::forceFlush()` calls is expected behavior with `Temporality::CUMULATIVE` (see also (T0, T2] in the [Synchronous example: Cumulative aggregation temporality](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/supplementary-guidelines.md#synchronous-example-cumulative-aggregation-temporality)).

OK. I see that I lack basic understanding of temporality. I will start looking into that. Thanks for the reply.

**Comment by brettmc** [comment]
@erdemkose AFAIK you're one of the very first testers of metrics...we'd love documentation patches if you're able 🙂
