### ISSUE TITLE
Implement the ShouldSample decision as a function of the TraceID

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#86]
The specification for this is [ready](https://github.com/open-telemetry/opentelemetry-specification/blob/e0bd41739a92304c0be5d68840f434e281b5f8b2/specification/trace/sdk.md#shouldsample)

We should update our implementation accordingly [here](https://github.com/open-telemetry/opentelemetry-php/blob/master/sdk/Trace/ProbabilitySampler.php#L50)

Success criteria - update the `shouldSample` function accordingly.

**Comment by shovnik** [comment]
Hi, can I work on this issue? - cc @alolita

**Comment by bobstrecansky** [comment]
You certainly may work on this issue!  Feel free to open a PR to the repo when ready.
