### ISSUE TITLE
Global tracer provider

### ISSUE THREAD

**Issue by tillkruss** [open-telemetry/opentelemetry-php#860]
I'm working on a wrapper for the [Relay](https://github.com/cachewerk/relay) extension for PHP and we're wondering if there is a "global tracer provider" in OpenTelemetry's PHP package, yet?

I've read about that in the docs for other languages.

**Comment by brettmc** [comment]
Hi. Yes there is, in our `main` branch but not yet in a released version. You should start by looking at the `SdkBuilder` (see `examples/sdk_builder.php`) to get an idea of how it works. In progress is a mechanism to automatically create the tracer provider, and you might also be interested in our prototype [auto-instrumentation extension](https://github.com/open-telemetry/opentelemetry-php-instrumentation)

**Comment by tillkruss** [comment]
Thanks a lot @brettmc, I'll wait until it's "finalized" the next release.

**Comment by brettmc** [comment]
@tillkruss you can get the provider that way yes, but _something_ needs to configure/create the global provider (working on having that automagically happen, but it's not ready yet).
By default, `Globals` will give you a no-op provider. You can take a look at how `SdkBuilder` registers the global provider (via `Configurator`) for now.

**Comment by tillkruss** [comment]
Thanks. I expect the system itself to register the global provider, or pass one to my code. This is great thanks!
