### ISSUE TITLE
Support for 16 character trace IDs

### ISSUE THREAD

**Issue by svenwltr** [open-telemetry/opentelemetry-php#863]
**Is your feature request related to a problem?**

We are using Traefik in front of a PHP application and we want to connect the traces of both. Currently they are not connected, because Traefik sends a 16 char trace ID and opentelemetry-php [expects 32 chars](https://github.com/open-telemetry/opentelemetry-php/blob/0.0.16/src/API/Trace/SpanContextValidator.php#L17).

**Describe the solution you'd like**

According to the B3 specs and to the Open Telemetry specs the trace ID is either 16 or 32 chars long. Therefore opentracing-php should allow both tracing lengths.

> The first position of the b3 value is the 32 or 16 lower-hex character TraceId. Unless propagating only the Sampling State, the TraceId is required. — https://github.com/openzipkin/b3-propagation#traceid-2

> TraceId is the identifier for a trace. It is worldwide unique with practically sufficient probability by being made as 16 randomly generated bytes. — https://opentelemetry.io/docs/reference/specification/overview/#spancontext

**Describe alternatives you've considered**

~We tried making Traefik send 32 char trace IDs, but did not find any config option for this.~

Edit: Traefik offers a [gen128bit](https://doc.traefik.io/traefik/observability/tracing/jaeger/#gen128bit) option that somehow results in 32 chars. While this works for us, requiring 32 chars is still not what the specs say.

**Additional context**

None

**Comment by brettmc** [comment]
Hi @svenwltr it looks like this has come up in other language SIGs and they've solved it by left-padding an 8-byte/16 hex char trace id, out to 32 bytes: https://github.com/open-telemetry/opentelemetry-go/issues/686
I'll put a patch together to do the same so you can test it out.

**Comment by brettmc** [comment]
@svenwltr are you able to test this: #869 ?
