### ISSUE TITLE
Allow tracking of Beta & GA milestones for tracing

### ISSUE THREAD

**Issue by willarmiros** [open-telemetry/opentelemetry-php#865]
Hi everyone, while this project is in alpha status for tracing, it cannot be used in production applications. It would be really helpful if perhaps we revived [the tracing project board](https://github.com/open-telemetry/opentelemetry-php/projects/1) to track Beta/GA requirements or even just opened issues to track these statuses. This way as a user of the library I can plan around when to implement it in production/consider it stable.

**Comment by bobstrecansky** [comment]
We have marked this as beta, so this issue being closed is okay! 🙂
