### ISSUE TITLE
Propegators API

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#89]
We should implement the Propagators API

The Spec for this API is found [here](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/context/api-propagators.md)

Success criteria - implement the propagators API according to the spec.

**Comment by beniamin** [comment]
I think this issue was already resolved in https://github.com/open-telemetry/opentelemetry-php/pull/57

**Comment by bobstrecansky** [comment]
I think you're right.  Closing.
