### ISSUE TITLE
Can it be applied to swoole?

### ISSUE THREAD

**Issue by omigafu** [open-telemetry/opentelemetry-php#892]
Before opening a feature request against this repo, consider whether the feature should/could be implemented in the [other OpenTelemetry client libraries](https://github.com/open-telemetry). If so, please [open an issue in opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/issues/new) first.

**Is your feature request related to a problem?**
swoole is coroutine framework, but I can't see how to apply it on swoole.

**Describe the solution you'd like**
I need to apply it on swoole.

**Describe alternatives you've considered**
no

**Additional context**
I try to use example to swoole, but there will be concurrency problems in the same process, so I am looking for a solution.
thanks.

**Comment by brettmc** [comment]
Hi @omigafu and welcome.
I see you've already found the contrib swoole module: https://github.com/open-telemetry/opentelemetry-php-contrib/tree/main/src/Context/Swoole

I'm aware of a couple of community members successfully using the otel swoole context library with swoole, so hopefully one of them will see this and provide some feedback. We'd love some documentation.

The only clue that I can give to you from #867  is that you need to set context storage to the swoole one.
I'm only guessing here, but something like `Context::setStorage(new SwooleContextStorage(Context::getStorage())` ?

**Comment by omigafu** [comment]
@brettmc thanks reply!
Your reply makes me suddenly see the light, but I don't know how and where to use it.  :(

**Comment by omigafu** [comment]
> Hi @omigafu and welcome. I see you've already found the contrib swoole module: https://github.com/open-telemetry/opentelemetry-php-contrib/tree/main/src/Context/Swoole
> 
> I'm aware of a couple of community members successfully using the otel swoole context library with swoole, so hopefully one of them will see this and provide some feedback. We'd love some documentation.
> 
> The only clue that I can give to you from #867 is that you need to set context storage to the swoole one. I'm only guessing here, but something like `Context::setStorage(new SwooleContextStorage(Context::getStorage())` ?

I think I have solved this problem, My approach is to add code like 
`Context::setStorage(new SwooleContextStorage(Context::storage()));
return;` 
to the head of the file `initialize_fiber_handler.php` or any custom files that can be automatically require.
@brettmc thanks for giving me direction.

**Comment by GuillaumeBrook** [comment]
@omigafu Any chances that you could provide a sample on how you did to export traces with Swoole + Otel ?

**Comment by brettmc** [comment]
@GuillaumeBrook I haven't used swoole much before, but I was able to generate traces using some of the examples in https://github.com/deminy/swoole-by-examples by:
* composer install open-telemetry/sdk
* `include 'vendor/autoload.php'`
* `Context::setStorage(new SwooleContextStorage(Context::storage()));` (as described above)

I used sdk autoloading and console exporter. For bonus points, I added an auto-instrumentation on `Swoole\Server::task` since the example I was using (servers/http1-integrated.php) called it, and it generated two related spans.

I think the key is setting storage early on, then using OpenTelemetry as you would in any other scenario.

**Comment by GuillaumeBrook** [comment]
@brettmc Thanks for you prompt answer, it helped me.

I managed to make basic things kinda work.
I don't use `Swole\Server::task` I just use the `$server->on('request', ...` FYI.

I didn't manage to make hooks on this function, so I made the code directly inside it.

So doing one http call correctly send the trace to DD.
Some things are a bit off, like the PDOs spans named "root", but this isn't really important.

However, when doing multiple http calls in //, I have a ton of warnings :
`ab -c 10 -n 10 -k http://localhost:9501/`

```
Warning: Swoole\Coroutine::getContext(): Context of this coroutine has been destroyed in /var/www/vendor/open-telemetry/context-swoole/src/SwooleContextHandler.php on line 59
Warning: Swoole\Coroutine::getContext(): Context of this coroutine has been destroyed in /var/www/vendor/open-telemetry/context-swoole/src/SwooleContextHandler.php on line 53
```

Then no traces are send.

Final code looks like that :
```
<?php

declare(strict_types=1);

use OpenTelemetry\API\Trace\Span;
use OpenTelemetry\API\Trace\SpanKind;
use OpenTelemetry\Context\Context;
use OpenTelemetry\Contrib\Context\Swoole\SwooleContextStorage;
use OpenTelemetry\SDK\Trace\TracerProviderFactory;
use Swoole\Constant;
use Swoole\Http\Request;
use Swoole\Http\Response;
use Swoole\Http\Server;

require_once __DIR__ . '/conf/ini.php';
require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/Models/PDOC.php';

$tracerProvider = (new TracerProviderFactory())->create();
$tracer = $tracerProvider->getTracer('datadog');

$server = new Server('0.0.0.0', 9501);
$server->set(
    [
        Constant::OPTION_HTTP_COMPRESSION       => true,
        Constant::OPTION_HTTP_COMPRESSION_LEVEL => 5
    ]
);

$server->on(
    'request',
    function (Request $request, Response $response) use ($tracer) {
        $span = \OpenTelemetry\API\Globals::tracerProvider()
            ->getTracer('manual-instrumentation')
            ->spanBuilder('api-http-request')
            ->setSpanKind(SpanKind::KIND_SERVER)
            ->setAttribute('service.name', 'api-http-request')
            ->startSpan();
        Context::setStorage(new SwooleContextStorage(Context::storage()));
        Context::storage()->attach($span->storeInContext(Context::getCurrent()));

        $pdoc = new Models\PDOC();
        $pdoc->doQuery();
        $response->status(200);
        $response->end("Hello OKKKKK");

        $scope = Context::storage()->scope();
        $scope->detach();
        $span = Span::fromContext($scope->context());
        /*if ($exception) {
            $span->recordException($exception);
            $span->setStatus(\OpenTelemetry\API\Trace\StatusCode::STATUS_ERROR);
        }*/
        $span->end();
    }
);

$server->start();
```
I don't really know opentelemetry for now so the code about spans might be not really ok.

 I'll look into it tomorrow.

**Comment by brettmc** [comment]
I also got some errors like that when playing around, and it was due to an error on the server side (usually misconfiguration on my part).
Looking at your code:
* don't set storage on each request, just set it once right up top of your script, after autoloading
* I don't know if that code between span start/end can throw exceptions, but if that's at all a possibility, then wrap it in a try/catch/finally so that scope detach definitely always runs

**Comment by brettmc** [comment]
> For now, I don't know if I did something wrong or if this is even possible.

It looks like it should, coroutines feature heavily through the swoole context handler. Can you turn your example into a self-contained docker-based example in your github?
