### ISSUE TITLE
[contrib] update symfony sdk bundle to work with otel beta/GA

### ISSUE THREAD

**Issue by brettmc** [open-telemetry/opentelemetry-php#901]
The [Symfony SDK Bundle ](https://github.com/open-telemetry/opentelemetry-php-contrib/tree/main/src/Symfony) needs some work to make it compatible with opentelemetry-php beta.

For the time being, its composer dependencies have been pinned to `0.0.15`, which is the latest pre-release version that it successfully builds against.

**Steps to reproduce**
- update composer.json, `"open-telemetry/opentelemetry": "^1"`
- PHP_VERSION=8.1 PROJECT=Symfony make all

**Comment by bobstrecansky** [comment]
@anthonyptetlow, do you have any insight here?

**Comment by anthonyptetlow** [comment]
So I had tried to get it up and running with version 1 when I first looked into it and couldn't at that point as a lot seemed to have changed. Hoever that was when I was first digging into the otel stuff so likely have a much better handle on it now so when I get some spare time I'll take another look.

**Comment by wadjei** [comment]
@brettmc I've been continuing to work with this package and believe I have something compatible with the current open-telemetry/contrib-symfony-instrumentation-bundle library.

Does https://github.com/opentelemetry-php/contrib-sdk-bundle/pull/2 work for you?

**Comment by brettmc** [comment]
I left a couple of comments on that PR, but you'll need to resubmit it against the contrib repo.

**Comment by brettmc** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-php-contrib/pull/169
