### ISSUE TITLE
OpenTelemetry to XRay on Lambda — data not flowing 

### ISSUE THREAD

**Issue by sc0ttdav3y** [open-telemetry/opentelemetry-php#906]
Hi,

First, let me say I'm super-excited about the potential of this project, and thanks to the contributors for their efforts to date. As a PHP developer running on AWS Lambda, I'm seeing this as a fantastic opportunity to fill an important gap.

I'm currently trying to get open-telemetry running on PHP on Lambda without success. I understand things are in their early days, and I'm finding the docs and examples outdated at present. I've given it my best but I'm not able to get a result.

I've been reading widely on blog posts, github issues, the AWS XRay docs and the Open Telemetry docs, but so far I can't find an up to date reference that puts it all together. 

**Describe your environment**

I'm running Bref on AWS Lambda with php 7.4 (yeah, I know) and open-telemetry 0.0.17, as follows:

```
    "open-telemetry/contrib-aws": "0.0.17",
    "open-telemetry/opentelemetry": "0.0.17",
    "open-telemetry/opentelemetry-php-contrib": "0.0.17",
```

* I've built a custom layer for the collector as described [here](https://github.com/open-telemetry/opentelemetry-lambda/blob/main/collector/README.md).
* I've built a wrapper class in PHP [here](https://gist.github.com/sc0ttdav3y/0d320d08a726dd0ed204a47bd8ebb78b) that puts all the OpenTelemetry code in one place.

**Steps to reproduce**

I've shared a gist with my open-telemetry PHP code [here](https://gist.github.com/sc0ttdav3y/0d320d08a726dd0ed204a47bd8ebb78b)

Steps:

1. Push the collector layer and configure it into the function
2. Push the code containing my gist and the composer deps above
3. Run `setUp()` in my code, and then `startSpan()` and `endSpan()` to collect some data
4. Look in AWS XRay to see the data

**What is the expected behavior?**

I expect to see the data in AWS XRay.

**What is the actual behavior?**

XRay shows me my lambda function, but not the PHP trace.

**Additional context**

I can see logs such as this, which I presume are generated from the collector.

```
2023-01-08T11:43:42 {"level":"info","ts":1673178222.7031276,"msg":"TracesExporter","kind":"exporter","data_type":"traces","name":"logging","#spans":1}
2023-01-08T11:43:42 {"level":"info","ts":1673178222.7031856,"msg":"ResourceSpans #0\nResource SchemaURL: \nResource attributes:\n     -> faas.name: Str(XXXXX)\n     -> faas.version: Str($LATEST)\n     -> cloud.region: Str(ap-southeast-2)\n     -> cloud.provider: Str(aws)\nScopeSpans #0\nScopeSpans SchemaURL: \nInstrumentationScope io.opentelemetry.contrib.php \nSpan #0\n    Trace ID       : 63baac6e38c7d4ad3a7b755834919a73\n    Parent ID      : 84bfa37214deb991\n    ID             : d810f21b345baa63\n    Name           : XXXX::YYYY::ZZZZ\n    Kind           : Internal\n    Start time     : 2023-01-08 11:43:42.607256547 +0000 UTC\n    End time       : 2023-01-08 11:43:42.695558894 +0000 UTC\n    Status code    : Unset\n    Status message : \nAttributes:","kind":"exporter","data_type":"traces","name":"logging"}
```

I can confirm the "Trace ID" in that payload matches the Lambda invocation trace ID.

If I misconfigure the open-telemetry transport then I get a connection error, so I know it's connecting :-)

When I look in AWS, I see my Lambda invocation but no subsequent PHP trace.

I'm not sure how to debug this further to work out whether it's open-telemetry or the collector or something-something AWS.

Given the state of the docs around the use of AWS XRay with open-telemetry, I suspect my problem lies somewhere in my `setUp()` method I shared in the gist above. There's about 40 lines in there from 94 - 136 that I suspect .

If anyone can take a look and offer some advice, that would be appreciated. 

If I can get this going, I'd be happy to contribute an up-to-date example back to opentelemetry-php to help others on PHP + Bref + Lambda + XRay.

Thanks in advance, Scott.

**Comment by brettmc** [comment]
Hi Scott, and welcome.

The code in your gist looks ok to me, and the fact that PHP is exporting a trace which is received by the collector is a good sign that the PHP side is configured correctly.

Can you share your collector config? Given that a valid-looking trace is being received by the collector, I'd be looking at whether it's being successfully exported by the collector to wherever the next destination is (AWS?)

**Comment by sc0ttdav3y** [comment]
Hi @brettmc, thanks for helping out — here's my collector config.

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  awsxray:
    region: ap-southeast-2
  awsemf:
    region: ap-southeast-2
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, awsxray]
    metrics:
      receivers: [otlp]
      exporters: [awsemf]
  telemetry:
    logs:
      level: debug
```

This was pretty-much taken from the docs I was following that I linked to originally. I'm not 100% across it all, to be honest, but from my understanding, the presence of `awsxray` as an exporter should be enough.

I also tried the out-of-box version in the opentelemetry-lambda/collector/config.yaml first, with the key differences being `service.pipelines.traces.exporters` path didn't have `xray` in the original version.

Thanks again for your help... Scott

**Comment by brettmc** [comment]
That config looks ok to me, exactly what I was expecting to see from the documentation I was reading. Does xray itself produce any logging that you can see in aws? I'm thinking there could warnings about invalid data, or invalid credentials, etc, which could be helpful.
I've also pinged a contact at AWS, so hopefully my message gets through and somebody with some working knowledge can chime in :)

**Comment by sc0ttdav3y** [comment]
There's nothing in AWS that I can see. I've got a support ticket waiting at AWS for the same question.

**Comment by bobstrecansky** [comment]
@brettmc reached out to an XRay team member, she is working to replicate this issue as well.

**Comment by carolabadeer** [comment]
Responded on the same issue in [aws-observability/aws-otel-php](https://github.com/aws-observability/aws-otel-php/issues/4) :)

**Comment by carolabadeer** [comment]
Closing as issue has been resolved in https://github.com/aws-observability/aws-otel-php/issues/4

**Comment by brettmc** [comment]
Closing, resolved in issue linked above.
