### ISSUE TITLE
[opentelemetry-php-contrib] Create PDO Instrumentation

### ISSUE THREAD

**Issue by pdelewski** [open-telemetry/opentelemetry-php#910]
This is a placeholder regarding adding auto-instrumentation support for PDO (https://www.php.net/manual/en/book.pdo.php).
That would significantly extend auto-instrumentation coverarge

**Comment by brettmc** [comment]
Closing, as PDO instrumentation has been added in `-contrib` repository: https://github.com/open-telemetry/opentelemetry-php-contrib/tree/main/src/Instrumentation/PDO
