### ISSUE TITLE
Basic Symfony auto-instrumentation should work with Drupal

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#912]
We'd like to ensure that basic Symfony auto-instrumentation should work with Drupal.  We are not sure exactly what classes or interfaces to hook into.  We should probably follow up with someone on the Symfony team in order to start this integration.

**Comment by brettmc** [comment]
I played around with this a little bit on the weekend, using drupal's "umami" demo site.
I got as far as creating a root span by observing symfony's `HttpKernelInterface::handle`, and immediately noticed that drupal uses a bunch of kernels (something like middleware). It sort of worked, but was confusing to look at with just this much instrumentation.
If I change it to observer `DrupalKernel::handle` then it looks more sensible - so maybe we will actually need to auto-instrument drupal itself?
The other thing to try is the symfony SDK bundle over in our contrib repo - it uses symfony events and so may work better.

**Comment by mikkeschiren** [comment]
Maybe some hints from: https://www.drupal.org/project/o11y/
Which uses: https://www.drupal.org/project/tracer

**Comment by mikkeschiren** [comment]
I guess events should be a good fit.

**Comment by pdelewski** [comment]
@brettmc  I opened https://github.com/open-telemetry/opentelemetry-php-contrib/pull/114, however I hooked into `https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/HttpKernel/HttpKernel.php#L68` instead of `HttpKernelInterface::handle`. As a result I got something like that

![image](https://user-images.githubusercontent.com/102958445/220121845-4d8567f8-5a0b-4449-8508-8bbcc6f54693.png)

**Comment by brettmc** [comment]
That looks pretty good to me, I think we can say that it does work with Drupal? Do we need any doc updates to make it more obvious that we've validated that basic functionality works against drupal?

**Comment by pdelewski** [comment]
Yes, I think it would be good to mention that somewhere, at least we create main span for Drupal.
