### ISSUE TITLE
Try find how to define service.name because it's unknown_service in jaeger

### ISSUE THREAD

**Issue by ddurieux** [open-telemetry/opentelemetry-php#915]
I have search in this repository and many others repositories, and nos find how to change the unknown_service in traces sent to jaeger.

Seems the attribute `service.name` but when set in `tracer->spanBuilder('root')`, not works.
I have try too in `$tracer = $tracerProvider->getTracer('/v1/config/type', null, null, ['service.name' => 'fusionsuite']);` but not works too.

Somebody know how to set it? or perhaps it's a bug, really not sure.

**Comment by brettmc** [comment]
Hi @ddurieux 
You can do it by providing resources when creating the tracer provider: https://github.com/open-telemetry/opentelemetry-php/blob/main/examples/traces/features/span_resources.php#L30
It's also possible to provide it via environment/php.ini: https://github.com/open-telemetry/opentelemetry-php/blob/main/examples/traces/features/configuration_from_environment.php#L10

**Comment by ddurieux** [comment]
Oh thank you, it works nicely ;)
I use resources because environment variables as config is a very bad practice for me.

Thanks for the time spent for me !
