### ISSUE TITLE
Unit Test case is failing for Power(ppc64le) <Failed asserting that stdClass Object is null>.

### ISSUE THREAD

**Issue by Pratikt2312** [open-telemetry/opentelemetry-php#924]
Hi Team,
I am working on validating opentelemetry-php master version on Power(ppc64le) architecture.
As I firstly tried it on ppc64le arch. then also checked it on x86_64 architecture but the same test case is failing 
on both architectures.
Unit test case is failing with the following error:

  There was 1 failure:
    1) OpenTelemetry\Tests\Unit\API\Trace\TraceTest::test_does_not_keep_argument_references
        Failed asserting that stdClass Object &0000000073880ce20000000020da0cb4 () is null.

        /opentelemetry-php/tests/Unit/API/Trace/TraceTest.php:120
       /opentelemetry-php/src/API/Trace/functions.php:35
       /opentelemetry-php/tests/Unit/API/Trace/TraceTest.php:121

FAILURES!
 

To Reproduce
1. Installation of php
2. Cloning the repo
3. composer install
4. php -dzend.assertions=1 vendor/bin/phpunit

Additional context
   I have also follow the CI jobs/steps and replicate the same on Ubuntu:20.04 and got the results 
   as per CI logs,So not getting any test case failure on ubuntu image.

Attached the logs :
[Build_and _test_logs_otel-php_ppc64le.txt](https://github.com/open-telemetry/opentelemetry-php/files/10728956/Build_and._test_logs_otel-php_ppc64le.txt)

[Build_and _test_logs_otel-php_x86.txt](https://github.com/open-telemetry/opentelemetry-php/files/10728959/Build_and._test_logs_otel-php_x86.txt)

[Otel-php-ubuntu-logs.txt](https://github.com/open-telemetry/opentelemetry-php/files/10728960/Otel-php-ubuntu-logs.txt)

Any suggestions and pointers regarding the same will be helpful.

**Comment by brettmc** [comment]
I can't tell which branch of our repo you are testing against, but I'm pretty sure it's not a recent version of `main`. I see `cloudevents/sdk-php` being installed, which is no longer a dependency and has not been for a few releases.

**Comment by Pratikt2312** [comment]
I have tested on the main branch as well as version 1.0.0beta1 and 0.0.17 but it fails with the same test case.

**Comment by brettmc** [comment]
Regarding power architecture, we unfortunately do not have access to that architecture to develop/test against, so the best suggestion I have is to attach a debugger and step through the code. The test in question relates to weak references, do they work in the architecture you're testing against?

When you say that you tested on x86_64 architecture, can you provide more details? We develop against x86_64, and that's what our CI runs against, so is there something different between your architecture and ours?

**Comment by Pratikt2312** [comment]
Hi, I have retested it on x86_64 architecture (UBI: 8.5 container) against commit id (19b9326) on main branch,
But observed the same problem.
Attached the whole logs:
[x86_64_main_19b9326_ubi8_otel-php_logs.txt](https://github.com/open-telemetry/opentelemetry-php/files/10752274/x86_64_main_19b9326_ubi8_otel-php_logs.txt)
We are also debugging from our end, but if we are missing something or any pointers would be helpful.

**Comment by brettmc** [comment]
How strange. This is as close as I can get my dev environment to yours (almost identical versions of everything):
```shell
/usr/src/myapp $ php -dzend.assertions=1 vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --testsuite unit
Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.17.0.1:9003 (through xdebug.client_host/xdebug.client_port).
PHPUnit 9.6.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.27
Configuration: /usr/src/myapp/phpunit.xml.dist
Warning:       XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set

.............................................................   61 / 1249 (  4%)
.............................................................  122 / 1249 (  9%)
.............................................................  183 / 1249 ( 14%)
.............................................................  244 / 1249 ( 19%)
.............................................................  305 / 1249 ( 24%)
.............................................................  366 / 1249 ( 29%)
.............................................................  427 / 1249 ( 34%)
.............................................................  488 / 1249 ( 39%)
.............................................................  549 / 1249 ( 43%)
.............................................................  610 / 1249 ( 48%)
.............................................................  671 / 1249 ( 53%)
.............................................................  732 / 1249 ( 58%)
.............................................................  793 / 1249 ( 63%)
.............................................................  854 / 1249 ( 68%)
.............................................................  915 / 1249 ( 73%)
...........................................S.................  976 / 1249 ( 78%)
............................................................. 1037 / 1249 ( 83%)
............................................................. 1098 / 1249 ( 87%)
............................................................. 1159 / 1249 ( 92%)
............................................................. 1220 / 1249 ( 97%)
.............................                                 1249 / 1249 (100%)

Time: 00:00.741, Memory: 34.00 MB

There was 1 skipped test:

1) OpenTelemetry\Tests\Unit\SDK\Metrics\Stream\MetricStreamTest::test_synchronous_reader_limit_does_not_apply_if_gmp_available

/usr/src/myapp/tests/Unit/SDK/Metrics/Stream/MetricStreamTest.php:369

OK, but incomplete, skipped, or risky tests!
Tests: 1249, Assertions: 2049, Skipped: 1.
/usr/src/myapp $ arch
x86_64
/usr/src/myapp $ php -v
PHP 8.0.27 (cli) (built: Feb 11 2023 11:07:35) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.27, Copyright (c) Zend Technologies
    with Xdebug v3.2.0, Copyright (c) 2002-2022, by Derick Rethans
```

I'm only guessing from looking at the tested function, but if you drop this test somewhere, what do the results look like for you?
```php
   public function test_weak_ref(): void
    {
        $o = new stdClass();
        $r = WeakReference::create($o);
        $this->assertNotNull($r->get());
        $o = null;
        $this->assertNull($r->get());
    }
```

**Comment by Pratikt2312** [comment]
Hi, I have put this test in the same file i.e. TraceTest.php and tested it, so the test case is passing successfully 
for the same environment setup.

   public function test_weak_ref(): void
    {
        $o = new stdClass();
        $r = WeakReference::create($o);
        $this->assertNotNull($r->get());
        $o = null;
        $this->assertNull($r->get());
    }

Logs for the same : 
[root@5c34947e1b9e opentelemetry-php]# php -dzend.assertions=1 vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --testsuite unit
PHPUnit 9.6.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.27
Configuration: /opentelemetry-php/phpunit.xml.dist
Warning:       XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set

.............................................................   61 / 1260 (  4%)
.............................................................  122 / 1260 (  9%)
.....................................F.......................  183 / 1260 ( 14%)
.............................................................  244 / 1260 ( 19%)
.............................................................  305 / 1260 ( 24%)
.............................................................  366 / 1260 ( 29%)
.............................................................  427 / 1260 ( 33%)
.............................................................  488 / 1260 ( 38%)
.............................................................  549 / 1260 ( 43%)
.............................................................  610 / 1260 ( 48%)
.............................................................  671 / 1260 ( 53%)
.............................................................  732 / 1260 ( 58%)
.............................................................  793 / 1260 ( 62%)
.............................................................  854 / 1260 ( 67%)
.............................................................  915 / 1260 ( 72%)
......................................................S......  976 / 1260 ( 77%)
............................................................. 1037 / 1260 ( 82%)
............................................................. 1098 / 1260 ( 87%)
............................................................. 1159 / 1260 ( 91%)
............................................................. 1220 / 1260 ( 96%)
........................................                      1260 / 1260 (100%)

Time: 00:01.305, Memory: 38.00 MB

There was 1 failure:

1) OpenTelemetry\Tests\Unit\API\Trace\TraceTest::test_does_not_keep_argument_references
Failed asserting that stdClass Object &0000000027f4a0850000000012853ae3 () is null.

/opentelemetry-php/tests/Unit/API/Trace/TraceTest.php:129
/opentelemetry-php/src/API/Trace/functions.php:35
/opentelemetry-php/tests/Unit/API/Trace/TraceTest.php:130

--

There was 1 skipped test:

1) OpenTelemetry\Tests\Unit\SDK\Metrics\Stream\MetricStreamTest::test_synchronous_reader_limit_does_not_apply_if_gmp_available

/opentelemetry-php/tests/Unit/SDK/Metrics/Stream/MetricStreamTest.php:369

FAILURES!
Tests: 1260, Assertions: 2069, Failures: 1, Skipped: 1.

[root@5c34947e1b9e opentelemetry-php]# php -dzend.assertions=1 vendor/bin/phpunit --filter test_weak_ref
PHPUnit 9.6.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.27
Configuration: /opentelemetry-php/phpunit.xml.dist

.                                                                   1 / 1 (100%)

Time: 00:00.056, Memory: 24.00 MB

OK (1 test, 2 assertions)
