### ISSUE TITLE
Implement the Samplers

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#93]
the sampler bits never get used in the SDK.  They are implemented and tested, but nothing currently uses them.   Implement the sampler into the tracer and trace provider.

**Comment by bobstrecansky** [comment]
@morrisonlevi - are you still planning on working on this?

**Comment by zsistla** [comment]
Working on this and status is `in progress`.

**Comment by zsistla** [comment]
Please see PR #204:
https://github.com/open-telemetry/opentelemetry-php/pull/204
