### ISSUE TITLE
Laravel auto instrumentation cause error on laravel login feature

### ISSUE THREAD

**Issue by eliseuborges** [open-telemetry/opentelemetry-php#944]
**Describe your environment** 
- Laravel framework: 10.1
- php 8.1
- larval/ui: 4.2.1
- open-telemetry/opentelemetry-auto-laravel:0.0.1

**Steps to reproduce**
After input my credentials on laravel login feature, the application shows this error

`OpenTelemetry\Contrib\Instrumentation\Laravel\LaravelInstrumentation::OpenTelemetry\Contrib\Instrumentation\Laravel\{closure}(): Argument #3 ($response) must be of type ?Illuminate\Http\Response, Illuminate\Http\RedirectResponse given, called in /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php on line 155`

**What is the expected behavior?**
No errors

**What is the actual behavior?**

`
OpenTelemetry\Contrib\Instrumentation\Laravel\LaravelInstrumentation::OpenTelemetry\Contrib\Instrumentation\Laravel\{closure}(): Argument #3 ($response) must be of type ?Illuminate\Http\Response, Illuminate\Http\RedirectResponse given, called in /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php on line 155
`

**Additional context**
I think the solution is change $reponse type, adding Illuminate\Http\RedirectResponse
```
...
post: static function (Kernel $kernel, array $params, Response|RedirectResponse|null $response, ?Throwable $exception) {
..
```

**Comment by wand2016** [comment]
JsonResponse may cause the same issue.
