### ISSUE TITLE
PHP-FPM child segfault. Possibly on die or exit func calls

### ISSUE THREAD

**Issue by xvilo** [open-telemetry/opentelemetry-php#951]
### Environment
Our environment runs on Kubernetes in a FPM only pod. This pod's base is created as such:
```
ARG PHP_VERSION=8.2
FROM php:${PHP_VERSION}-fpm-alpine as build

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions open-telemetry/opentelemetry-php-instrumentation@1.0.0beta2
[...]
```
Some PHP version info
```
$ php -v
PHP 8.2.4 (cli) (built: Mar 29 2023 22:47:02) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.4, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.4, Copyright (c), by Zend Technologies
```
Some OTEL info
```
$ php -i | grep otel
/usr/local/etc/php/conf.d/docker-php-ext-otel_instrumentation.ini,
otel_instrumentation
otel_instrumentation support => enabled

$ php -i | grep proto 
/usr/local/etc/php/conf.d/docker-php-ext-protobuf.ini,
protobuf
protobuf.keep_descriptor_pool_after_request => 0 => 0
```

**Steps to reproduce**
It's a bit difficult I think in other cases and was not able to create a simple set-up to demonstrate it, yet. It appears FPM segfaults with the following logs in normal:
```
[30-Mar-2023 11:48:53] WARNING: [pool www] child 66 exited on signal 11 (SIGSEGV - core dumped) after 7644.186788 seconds from start
[30-Mar-2023 11:48:53] NOTICE: [pool www] child 1131 started
```

With debug logging, we're seeing this:
```
[....]
":"http://redacted.example/bla/","method":"GET"} {"requestId":"36620a09-b398-4914-b86e-646dc6219d06"}
[30-Mar-2023 12:59:22.889846] DEBUG: pid 1, fpm_event_loop(), line 435: event module triggered 1 events
[2023-03-30T12:59:22.897970+00:00] app.DEBUG: [Redacted in app monolog log] [] {"requestId":"36620a09-b398-4914-b86e-646dc6219d06"}
[30-Mar-2023 12:59:22.898127] DEBUG: pid 1, fpm_event_loop(), line 435: event module triggered 1 events
[2023-03-30T12:59:22.899596+00:00] app.INFO: [Redacted in app monolog log] {"requestId":"36620a09-b398-4914-b86e-646dc6219d06"}
[30-Mar-2023 12:59:22.899777] DEBUG: pid 1, fpm_event_loop(), line 435: event module triggered 1 events
[2023-03-30T12:59:22.938389+00:00] app.INFO: [Redacted in app monolog log] {"tag":"JsonWspClient"} {"requestId":"36620a09-b398-4914-b86e-646dc6219d06"}
[30-Mar-2023 12:59:22.938656] DEBUG: pid 1, fpm_event_loop(), line 435: event module triggered 1 events
[2023-03-30T12:59:22.938698+00:00] app.DEBUG: [Redacted in app monolog log] [] {"requestId":"36620a09-b398-4914-b86e-646dc6219d06"}
[30-Mar-2023 12:59:22.938815] DEBUG: pid 1, fpm_event_loop(), line 435: event module triggered 1 events
[2023-03-30T12:59:22.939777+00:00] app.INFO: [Redacted in app monolog log] {"requestId":"36620a09-b398-4914-b86e-646dc6219d06"}
[30-Mar-2023 12:59:22.940063] DEBUG: pid 1, fpm_event_loop(), line 435: event module triggered 1 events
[2023-03-30T12:59:23.003724+00:00] app.INFO: [Redacted in app monolog log] {"requestId":"36620a09-b398-4914-b86e-646dc6219d06"}
[30-Mar-2023 12:59:23.003952] DEBUG: pid 1, fpm_event_loop(), line 435: event module triggered 1 events
[2023-03-30T12:59:23.005059+00:00] app.DEBUG: [Redacted in app monolog log] [] {"requestId":"36620a09-b398-4914-b86e-646dc6219d06"}
[30-Mar-2023 12:59:23.005143] DEBUG: pid 1, fpm_event_loop(), line 435: event module triggered 1 events
[30-Mar-2023 12:59:23.134352] DEBUG: pid 1, fpm_pctl_perform_idle_server_maintenance(), line 398: [pool www] currently 1 active children, 31 spare children, 32 running children. Spawning rate 1
[30-Mar-2023 12:59:23.326724] DEBUG: pid 1, fpm_event_loop(), line 435: event module triggered 1 events
[30-Mar-2023 12:59:23.326780] DEBUG: pid 1, fpm_got_signal(), line 82: received SIGCHLD
[30-Mar-2023 12:59:23.326789] DEBUG: pid 1, fpm_event_loop(), line 435: event module triggered 2 events
[30-Mar-2023 12:59:23.326850] WARNING: pid 1, fpm_children_bury(), line 258: [pool www] child 71 exited on signal 11 (SIGSEGV - core dumped) after 78.266474 seconds from start
[30-Mar-2023 12:59:23.326887] DEBUG: pid 1, fpm_children_make(), line 407: blocking signals before child birth
[30-Mar-2023 12:59:23.327734] DEBUG: pid 1, fpm_children_make(), line 431: unblocking signals, child born
[30-Mar-2023 12:59:23.327827] NOTICE: pid 1, fpm_children_make(), line 437: [pool www] child 87 started
10.42.4.24 - - [30/Mar/2023:12:59:23 +0000] "GET /bla/ HTTP/1.1" 502 166 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15"
[....]
```

From as far as I was able to trace it this happens when we call a `redirect` method in our in-house framework. This method does some checks, sets the redirect header and then calls `exit()`. Commenting the exit "fixes" the segfault. Adding `die()` statements around the `redirect` method call also yields in a segfault. HOWEVER, adding a `die()` in our index after vendor autoload include but before returning symfony runtime config it does work. 

**What is the expected behavior?**
Cleanly stop code execution on `die()` or `exit()` call. 

**What is the actual behavior?**
Segfault.

**Additional context**
While the logs from the FPM process state there was a core dump created, we could not find anything in the pod or on the worker node. We have some logs from the process while running `strace`, but I'm not that keen on sharing those publicly, unless it doesn't contain app specific stuffs

**Comment by xvilo** [comment]
I expected this maybe to be an issue with shutdownhandlers, but with the following test:
```
<?php

putenv('OTEL_PHP_AUTOLOAD_ENABLED=true');
putenv('OTEL_TRACES_EXPORTER=otlp');
putenv('OTEL_METRICS_EXPORTER=none');
putenv('OTEL_LOGS_EXPORTER=none');
putenv('OTEL_EXPORTER_OTLP_ENDPOINT=grpc');
putenv('OTEL_EXPORTER_OTLP_ENDPOINT=https://tempo-uxdtransip.nl.team.blue:443/otlp');
putenv('OTEL_PHP_TRACES_PROCESSOR=batch');
putenv('OTEL_SERVICE_NAME=customer-frontend');
putenv('OTEL_LOG_LEVEL=debug');
putenv('OTEL_PROPAGATORS=baggage,tracecontext');
putenv('OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf');
putenv('OTEL_EXPORTER_OTLP_INSECURE=true');
putenv('OTEL_RESOURCE_ATTRIBUTES=frontend.name=customer');

include 'vendor/autoload.php';

register_shutdown_function(function () {
    echo 'some output!';
});

for ($i = 1; $i <= 300; $i++) {
    echo '.';
    if ($i === 200) {
        die('no!');
    }
}
```

The output was expected:
```
$ docker run --rm -it -v ${PWD}:/app docker.io/xvilo/php:test php /app/test2.php
........................................................................................................................................................................................................no!some output!
```

**Comment by piotrantosik** [comment]
maybe my case will be helpful here https://github.com/open-telemetry/opentelemetry-php-instrumentation/issues/40

**Comment by xvilo** [comment]
Still happens with beta 3 release installed from pecl

**Comment by brettmc** [comment]
@xvilo what happens in your example above if the die/exit happens whilst a hooked function is executing? (ie, the `pre` function has executed, but not the `post` yet)

**Comment by xvilo** [comment]
Sorry for the late response, for some reason when I have the following:
```php
<?php
// docker run --rm -it -v ${PWD}:/app docker.io/xvilo/php:test php /app/test.php

putenv('OTEL_PHP_AUTOLOAD_ENABLED=true');
putenv('OTEL_TRACES_EXPORTER=otlp');
putenv('OTEL_METRICS_EXPORTER=none');
putenv('OTEL_LOGS_EXPORTER=none');
putenv('OTEL_EXPORTER_OTLP_ENDPOINT=grpc');
putenv('OTEL_EXPORTER_OTLP_ENDPOINT=https://xxxxx.example.com:443/otlp');
putenv('OTEL_PHP_TRACES_PROCESSOR=batch');
putenv('OTEL_SERVICE_NAME=xxxx-yyyyy');
putenv('OTEL_LOG_LEVEL=debug');
putenv('OTEL_PROPAGATORS=baggage,tracecontext');
putenv('OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf');
putenv('OTEL_EXPORTER_OTLP_INSECURE=true');
putenv('OTEL_RESOURCE_ATTRIBUTES=frontend.name=yyyyy');

include 'vendor/autoload.php';

use function OpenTelemetry\Instrumentation\hook;

register_shutdown_function(function () {
    echo 'some output!';
});

hook(
    'TestClass',
    'countFunction',
    static function ($object, array $params, string $class, string $function, ?string $filename, ?int $lineno) {
        echo 'pre' . PHP_EOL;
    },
    static function ($object, array $params, string $class, string $function, ?string $filename, ?int $lineno) {
        echo 'post' . PHP_EOL;
    }
);

echo 'before' . PHP_EOL;
TestClass::countFunction();
echo 'after' . PHP_EOL;

class TestClass {
    public static function countFunction(): void
    {
        echo 'start' . PHP_EOL;
        for ($i = 1; $i <= 300; $i++) {
            echo '.';
            if ($i === 200) {
                die('no!');
            }
        }
    }
}
```

I just see the following output and then it exists properly
```
$ docker run --rm -it -v ${PWD}:/app docker.io/xvilo/php:test php -i | grep tel 
/usr/local/etc/php/conf.d/docker-php-ext-opentelemetry.ini,
Protocols => dict, file, ftp, ftps, gopher, gophers, http, https, imap, imaps, mqtt, pop3, pop3s, rtsp, smb, smbs, smtp, smtps, telnet, tftp, ws, wss
opentelemetry
opentelemetry support => enabled

$ docker run --rm -it -v ${PWD}:/app docker.io/xvilo/php:test php /app/test.php
before
pre
start
........................................................................................................................................................................................................no!
```

**Comment by pdelewski** [comment]
@xvilo `post` function has incorrect parameters
should be
```
    post: static function ($object, array $params, mixed $ret, ?\Throwable $exception ) {
        echo 'post' . PHP_EOL;
    }
```

**Comment by xvilo** [comment]
Great to hear it was reproducible. Regarding the method signature, I don't think there is some easy way to auto inspect this through your IDE yet?

**Comment by pdelewski** [comment]
> Great to hear it was reproducible. Regarding the method signature, I don't think there is some easy way to auto inspect this through your IDE yet?

Don't think that's possible, but good question

**Comment by pdelewski** [comment]
@xvilo Is it any reason for using `die` there? (`return` works correctly) Seems like corner case. This might be more general problem with observer API as `die` seems to have some side-effects, but requires deeper investigation

**Comment by xvilo** [comment]
Well, currently I'm instrumenting a couple of base methods within our homebrew-framework. One of these has a `SomePageController::redirect(string $url): never` method. This method sets the redirect header to PHP, then preforms a `die()`. Normally, everything is flushed to the browser at that point, including the redirect headers. 

It's not the best, but it's from the 2009-ish era. I expect this being a generic case. 

In the controller it can be called as:
```
$this->redirect(
   'https://example.com/',
    HttpStatusCode::HTTP_FOUND
);
```

And the logic for it should be:
```
public function redirect(
    string $url,
    $type = HttpStatusCode::HTTP_FOUND,
) {
    // Some removed checking and security codes

    header('Location: ' . $url);

    // Some removed checking and security codes

    exit();
}
```

**Comment by pdelewski** [comment]
Seems that root cause of crash is incorrect `$exception` parameter type which seems to be `UnwindExit` in case of exit call. As I workaround I can suggest to change post hook signature to 
```
    post: static function ($object, array $params, mixed $ret, mixed $exception ) {
        echo 'post' . PHP_EOL;
    }
```

until we will fix it.

**Comment by pdelewski** [comment]
@xvilo Have you maybe tried a workaround I mentioned some time ago just to check if that will solve issue?

Change post signature to:
```
    post: static function ($object, array $params, mixed $ret, mixed $exception ) 
```

**Comment by pdelewski** [comment]
@xvilo Could you provide signatures of your hook functions from your production env?

**Comment by ahkui** [comment]
open-telemetry/opentelemetry-php-instrumentation#59

same here

**Comment by brettmc** [comment]
@ahkui are you able to create a docker container which will cause segfault? That will help pdelewski to debug the issue - I can't help, it's beyond my skills :(

**Comment by xvilo** [comment]
The code from our production env for the hook call would be like this:
```php
use OpenTelemetry\API\Common\Instrumentation\CachedInstrumentation;
use function OpenTelemetry\Instrumentation\hook;

private static function _hook(CachedInstrumentation $instrumentation, string $class, string $function, string $name): void
{
    // object, array $params, mixed $ret, mixed $exception
    hook(
        class: $class,
        function: $function,
        pre: static function ($object, ?array $params, ?string $class, string $function, ?string $filename, ?int $lineno) use ($instrumentation, $name): void {
            // stuffs to start span
        },
        post: static function ($object, ?array $params, mixed $return, ?Throwable $exception): void {
            // Stuffs to end span
        }
    );
}
```

**Comment by xvilo** [comment]
I did some tests yesterday and applied the following patches to vendored code:
```patch
@package open-telemetry/opentelemetry-auto-symfony

--- src/SymfonyInstrumentation.php	2023-06-09 15:58:24
+++ src/SymfonyInstrumentation.php	2023-06-10 16:50:56
@@ -69,7 +69,7 @@
                 HttpKernel $kernel,
                 array $params,
                 ?Response $response,
-                ?\Throwable $exception
+                mixed $exception
             ): void {
                 $scope = Context::storage()->scope();
                 if (null === $scope) {
```
```patch
@package open-telemetry/api

--- Trace/NonRecordingSpan.php	2023-05-03 00:59:57
+++ Trace/NonRecordingSpan.php	2023-06-11 21:53:17
@@ -52,7 +52,7 @@
     }

     /** @inheritDoc */
-    public function recordException(Throwable $exception, iterable $attributes = []): SpanInterface
+    public function recordException(mixed $exception, iterable $attributes = []): SpanInterface
     {
         return $this;
     }
```
```patch
@package open-telemetry/sdk

--- Trace/Span.php	2023-05-17 00:34:51
+++ Trace/Span.php	2023-06-11 21:54:28
@@ -213,7 +213,7 @@
     }

     /** @inheritDoc */
-    public function recordException(Throwable $exception, iterable $attributes = [], ?int $timestamp = null): self
+    public function recordException(mixed $exception, iterable $attributes = [], ?int $timestamp = null): self
     {
         if ($this->hasEnded) {
             return $this;
```
```patch
@package open-telemetry/api

--- Trace/SpanInterface.php	2023-05-03 00:59:57
+++ Trace/SpanInterface.php	2023-06-11 21:51:29
@@ -70,7 +70,7 @@
     /**
      * @see https://github.com/open-telemetry/opentelemetry-specification/blob/v1.6.1/specification/trace/api.md#record-exception
      */
-    public function recordException(Throwable $exception, iterable $attributes = []): SpanInterface;
+    public function recordException(mixed $exception, iterable $attributes = []): SpanInterface;

     /**
      * @see https://github.com/open-telemetry/opentelemetry-specification/blob/v1.6.1/specification/trace/api.md#updatename
```

I was able to see these as the TypeError above, but after doing this, it started segfaulting again. I also must add that when it is installed, but not enabled through the ini file everything works as expected again

**Comment by pdelewski** [comment]
> I did some tests yesterday and applied the following patches to vendored code:
> 
> ```diff
> @package open-telemetry/opentelemetry-auto-symfony
> 
> --- src/SymfonyInstrumentation.php	2023-06-09 15:58:24
> +++ src/SymfonyInstrumentation.php	2023-06-10 16:50:56
> @@ -69,7 +69,7 @@
>                  HttpKernel $kernel,
>                  array $params,
>                  ?Response $response,
> -                ?\Throwable $exception
> +                mixed $exception
>              ): void {
>                  $scope = Context::storage()->scope();
>                  if (null === $scope) {
> ```
> 
> ```diff
> @package open-telemetry/api
> 
> --- Trace/NonRecordingSpan.php	2023-05-03 00:59:57
> +++ Trace/NonRecordingSpan.php	2023-06-11 21:53:17
> @@ -52,7 +52,7 @@
>      }
> 
>      /** @inheritDoc */
> -    public function recordException(Throwable $exception, iterable $attributes = []): SpanInterface
> +    public function recordException(mixed $exception, iterable $attributes = []): SpanInterface
>      {
>          return $this;
>      }
> ```
> 
> ```diff
> @package open-telemetry/sdk
> 
> --- Trace/Span.php	2023-05-17 00:34:51
> +++ Trace/Span.php	2023-06-11 21:54:28
> @@ -213,7 +213,7 @@
>      }
> 
>      /** @inheritDoc */
> -    public function recordException(Throwable $exception, iterable $attributes = [], ?int $timestamp = null): self
> +    public function recordException(mixed $exception, iterable $attributes = [], ?int $timestamp = null): self
>      {
>          if ($this->hasEnded) {
>              return $this;
> ```
> 
> ```diff
> @package open-telemetry/api
> 
> --- Trace/SpanInterface.php	2023-05-03 00:59:57
> +++ Trace/SpanInterface.php	2023-06-11 21:51:29
> @@ -70,7 +70,7 @@
>      /**
>       * @see https://github.com/open-telemetry/opentelemetry-specification/blob/v1.6.1/specification/trace/api.md#record-exception
>       */
> -    public function recordException(Throwable $exception, iterable $attributes = []): SpanInterface;
> +    public function recordException(mixed $exception, iterable $attributes = []): SpanInterface;
> 
>      /**
>       * @see https://github.com/open-telemetry/opentelemetry-specification/blob/v1.6.1/specification/trace/api.md#updatename
> ```
> 
> I was able to see these as the TypeError above, but after doing this, it started segfaulting again. I also must add that when it is installed, but not enabled through the ini file everything works as expected again

I don't think these changes are needed. Following should do the same 
```
    post: static function ($object, array $params, mixed $ret, mixed $exception ) {
        echo 'post' . PHP_EOL;
    }
``` 
@xvilo Have you check that?

**Comment by ahkui** [comment]
> @ahkui, is this still an issue for you?

yes, but no idea how to reproduce

**Comment by xvilo** [comment]
Yes, my post argument looks like this current:
```
post: static function ($object, array $params, mixed $ret, mixed $exception): void {
    self::end($exception);
}
```

But while I think about it, `self::end` currently looks like this:
```
private static function end(?Throwable $exception): void
{
// Logic
}
```

So I'll change this too

**Comment by xvilo** [comment]
Alright, deployed the change and also with the updated `end` method it still segfaults, current method defintion is as follows:
```
private static function end(mixed $exception): void;
```

**Comment by brettmc** [comment]
I did a little bit of investigation on this today. I wasn't able to replicate the segfault in `1.0.0beta5`, but I think there is still a problem with `UnwindExit`...
According to https://github.com/php/php-src/blob/master/Zend/zend_exceptions.c#L46 `UnwindExit` is an:

> Internal pseudo-exception that is not exposed to userland. Throwing this exception *does not* execute finally blocks.

So IMO changing the typehint to `mixed` or otherwise is just working around the problem. We should not be passing an `UnwindException` to the `post` callback.

So what are the alternatives?

1. if `die` should not execute finally blocks, should it execute the `post` callback? https://www.php.net/manual/en/function.exit.php didn't really give me many hints; shutdown functions and destructors are still executed, but, die/exit really means "exit as soon as possible", right? I wouldn't expect any further code to run after a call to `die`, including generating telemetry (and so any uncompleted spans would be lost).
2. translate `UnwindExit` to something else that implements `Throwable`? This doesn't feel right, as there wasn't an exception.
3. Don't pass the `UnwindExit` to the post callback. The callback would run (since that param is nullable), and emit telemetry without logging an exception (which is fair - there was no exception)

**Comment by pdelewski** [comment]
> So IMO changing the typehint to mixed or otherwise is just working around the problem. 
@brettmc  If I'm correct @xvilo is experiencing the problem even after changing to `mixed`

> We should not be passing an UnwindException to the post callback.
Sounds good to me

**Comment by brettmc** [comment]
@xvilo - patch applied to the extension which stops `UnwindExit` from being sent to the post function. It's not in a released version yet, are you able to install from `main` and test it out?

**Comment by brettmc** [comment]
@xvilo - beta6 just released

**Comment by xvilo** [comment]
I believe it works fine now with beta 6, thanks. I'll keep it enabled on our internal testing environment so we can see what happens in the coming days/weeks.

To be sure, @ahkui are you able to confirm whether beta 6 works for you too or not?
