### ISSUE TITLE
Newest beta is leaving behind the current LTS version of Symfony

### ISSUE THREAD

**Issue by MetalArend** [open-telemetry/opentelemetry-php#954]
As mentioned in #953, we ran into trouble with our Composer installations. So of course we tried to upgrade to the newest beta release, jump on the wagon so to speak.

**Problem**
We noticed it is not able to be installed in a project running the current Symfony LTS (which receives bugfixes until November 2024, that's still 1,5 years).

**Reason**
The reason for the conflict is using the ^6 version of Symfony's http-client. I looked at the used code of the Symfony dependencies, and unless I missed something, I do not really see any "^6"-only features being used in this codebase.

**Possible solution**
Is it possible to reconsider the ^6 lock, and stay with the LTS version (^5.4|^6)? It can be tested by using the --prefer-lowest flag with Composer.

**Comment by brettmc** [comment]
Hi @MetalArend no problem at all with making it `^5|^6`. I'll get it done in the next day or 2, but you are also welcome to submit a PR for it.

**Comment by brettmc** [comment]
Hi @MetalArend I created 1.0.0beta1 which should resolve this, can you check it out please?

**Comment by MetalArend** [comment]
Only if you promise not to remove that tag in the near future? ;) :D All kidding aside, thanks for the quick release.

Just came out of standup, and sadly cannot allocate the time right now, some more urgent things right now to work on (which also means we have to disable the opentel package in our Composer). But I'll try to find the time to upgrade from 0.0.5 to 1.0.0beta1 (and all the pain that will come with it ;) ) this evening after hours, instead of waiting til later this week. :racehorse:

**Comment by MetalArend** [comment]
I'm testing on it now, and it is giving me an error on `\Google\Protobuf\Internal\Message` being used in `ExportTraceServiceRequest`, but not being available. I'm guessing that's a bug :)

**Comment by MetalArend** [comment]
I required the `google/protobuf` library, and all seems to work. But maybe that should be added as a dependency?

Another small thing I don't seem to find any information on, is that there's no easy way anymore to overwrite the `OTEL_SERVICE_NAME` by passing a name to for example the tracer. Is overwriting `$_SERVER['OTEL_SERVICE_NAME']` really the best way to go to have separated services in Jaeger?

**Comment by brettmc** [comment]
`google/protobuf` was just removed as a dependency in #949 but added to the `recommend` section.
We used to require the extension (due to it being way faster), but some devs want to use the native implementation for convenience.

re: `OTEL_SERVICE_NAME`, if you are manually creating an exporter, you can use resources to provide service name, see `examples/traces/features/span_resources.php`

**Comment by MetalArend** [comment]
Regarding `google/protobuf`, I guessed it is not meant to be a dependency anymore, but somehow it still is very much depending on it, as the `ExportTraceServiceRequest` is still extending from `\Google\Protobuf\Internal\Message`, which only exists in that library.

Regarding `OTEL_SERVICE_NAME`, thanks for the quick answer. But that example is still very much in the SDK (and SemConv) namespace. As I understood it, I should try to avoid using things outside the API namespace, no? Or is it okay once I deep dive like this?

**Comment by MetalArend** [comment]
`but whether you choose the extension or the native library is up to you` - I did not find a way to manually create a TracerProvider without the dependency. If the dependency is being moved to the recommended section, I would at least expect it to be possible to start tracing without it, instead of getting errors because it is missing.

Another issue I'm bumping into right now, is the `shutdown` method that is not being present on the API TracerProviderInterface, but it is on the SDK TracerProviderInterface. (I hope it's okay to pass these things on in here, I'm simply trying things out for the moment, and passing feedback as I encounter it - pretty sure I'm completely butchering my code, so it could all be only my fault :D )

**Comment by MetalArend** [comment]
Regarding the SDK vs API TracerProvider interface, I found out what is messing things up: the NoopTracerProvider is implementing the API TracerProviderInterface, the SDK TracerProvider is extending from both SDK and API TracerProviderInterface, but the shutdown function is only present on the SDK TracerProviderInterface, which is not common to both the NoopTracerProvider and TracerProvider. But now that I understand it, I can work around it.

**Comment by brettmc** [comment]
This is getting off-topic, it might be easier in our slack channel where there are also more people to contribute.

**Comment by MetalArend** [comment]
I'll move the `google/protobuf` dependency issue to another issue, and close this one, as the original issue of Symfony 5 is resolved. Thanks a lot, see you in slack (if I can find it).
