### ISSUE TITLE
RuntimeException(code: 400)

### ISSUE THREAD

**Issue by pdelewski** [open-telemetry/opentelemetry-php#969]
Following example https://github.com/open-telemetry/opentelemetry-php/blob/main/examples/traces/exporters/otlp_http_json.php
fails with following issue 
```
[2023-04-12T12:18:06.647406+00:00] otlp-example.ERROR: Export failure {"exception":"[object] (RuntimeException(code: 400): Bad Request at /Users/pdelewski/Projects/agent-apm-php/vendor/open-telemetry/sdk/Common/Export/Http/PsrTransport.php:106
```
It seems to be related to incorrect format of `trace_id` and `span_id`

**Comment by pdelewski** [comment]
I made some additional investigation. `trace_id` and `span_id` are encoded as base64 which is according to proto3 json mapping. Unfortunately opentelemetry uses different format which is base16 https://opentelemetry.io/docs/reference/specification/protocol/otlp/#json-protobuf-encoding

**Comment by brettmc** [comment]
I haven't looked very deeply yet, but I'm wondering whether you can override protobuf's setters for some fields. It would be cool if we could populate fields with an object that was aware of whether it was being encoded for json vs protobuf, and return the appropriate value. In theory that would cover the two use-cases we currently have (span/trace id format, enum format).

**Comment by Nevay** [comment]
> It would be cool if we could populate fields with an object

Protobuf validates and converts the value to the expected type using [`GBPUtil::checkString`](https://github.com/protocolbuffers/protobuf/blob/c7d979dbf47c80a179dd8dbb115c5694c7c0c461/php/src/Google/Protobuf/Internal/GPBUtil.php#L94) / [`to_string`](https://github.com/protocolbuffers/protobuf/blob/c7d979dbf47c80a179dd8dbb115c5694c7c0c461/php/ext/google/protobuf/convert.c#L333) etc., I don't think it's possible to override this behavior.

The extension seems to have an [option](https://github.com/protocolbuffers/protobuf/blob/c7d979dbf47c80a179dd8dbb115c5694c7c0c461/php/ext/google/protobuf/php-upb.c#L4727) that allows writing enums as ints, but this option is not exposed in [`Message::serializeToJsonString()`](https://github.com/protocolbuffers/protobuf/blob/main/php/ext/google/protobuf/message.c#L811).
