### ISSUE TITLE
Class 'Prometheus\Storage\Redis'

### ISSUE THREAD

**Issue by ZweiEuro** [open-telemetry/opentelemetry-php#994]
All dockerized. I am trying to make some kind of minimal working example from the example shown in this repo (prometheus version)

**Steps to reproduce**
I made a repo
git@github.com:ZweiEuro/reproduce_redis.git

clone it and run "docker-compose up"

**What is the expected behavior?**
Not a redis throw in localhost:80 
Also some ability to navigate to my root files of the server

**What is the actual behavior?**
localhost: 
`
Fatal error: Uncaught Error: Class 'Prometheus\Storage\Redis' not found in /var/www/public/index.php:5 Stack trace: #0 {main} thrown in /var/www/public/index.php on line 5`

the others produce "file not found"

** Note **:
Is redis even neccessary for this to run? Why is the example so complexly setup with changing php paths and idk what else.
As far as i can tell there is no clean "php demo" that just out of the box monitors some http requests so it can be monitored with jaeger or prometheus.

**Comment by brettmc** [comment]
Hmmm. That example is ancient. I'm not sure whether the concept even still applies - looking at [the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md), it doesn't look like anybody has even decided whether exporting directly to prometheus is a thing that OpenTelemetry should do.

What you can do, though, is export metrics via opentelemetry and have the collector forward them to prometheus.

@open-telemetry/php-maintainers - should we just delete that example? It's badly broken and a cause for confusion!

**Comment by ZweiEuro** [comment]
Is there a more up to date example somwhere ? 
I wasted quite a few hours trying to understand it, now that I know its broken the struggle makes a lot more sense xD

**Comment by brettmc** [comment]
@ZweiEuro the other examples in the `examples/metrics` directory do work and generate some metrics, which will be sent to an opentelemetry collector.
The collector can forward metrics to prometheus. We don't have a full example of doing this from PHP, but that part should be the same for all language implementations, and I know that the opentelemetry-demo project had it all set up: https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/otelcollector/otelcol-config.yml

**Comment by brettmc** [comment]
Removed the example in #996

**Comment by brettmc** [comment]
Closing as I don't think there's any more to do, please do re-open or create a new issue if you have more problems with metrics.
